# coding=utf-8
""" lsfix2_parm.py
"""
skips = []
targetobj2 = {
 # 
 'pwga': {'dictcode': 'pwg',
    'lscode': 'R. ed. Bomb.', 'nparms': [3,4],
    'skip': skips,
    'skip1': [],
         },
 'pwgb': {'dictcode': 'pwg',
    'lscode': 'R.', 'nparms': [2,3,4],
    'skip': skips,
    'skip1': ['<ls>R. GORR.', '<ls n="R. GORR.',
              '<ls>R. SCHL.', '<ls n="R. SCHL.',
              '<ls>R. ed. Bomb.', '<ls n="R. ed. Bomb.',
              '<ls>R. ed. GORR.', '<ls n="R. ed. GORR.',
              '<ls>R. ed. SCHL.', '<ls n="R. ed. SCHL.',
              '<ls>R. ed. Ser.', '<ls n="R. ed. Ser.',
              '<ls>R. (ed. ŚRĪR.)', '<ls>R. ed. ŚRĪR.',
              '<ls n="R. ed. ŚRĪR.',
            ],
         },
 #'pwgc': {'dictcode': 'pwg',
 #   'lscode': 'R. ed. GORR.', 'nparms': [3,4],
 #   'skip': skips,
 #   'skip1': [],
 #        }
 'pwa': {'dictcode': 'pw',
    'lscode': 'R. ed. Bomb.', 'nparms': [3,4],
    'skip': skips,
    'skip1': [],
           },

  'pwb': {'dictcode': 'pw',
    'lscode': 'R.', 'nparms': [2,3,4],
    'skip': skips,
    'skip1': ['<ls>R. GORR.', '<ls n="R. GORR.',
              '<ls>R. SCHL.', '<ls n="R. SCHL.',
              '<ls>R. ed. Bomb.', '<ls n="R. ed. Bomb.',
              '<ls>R. ed. GORR.', '<ls n="R. ed. GORR.',
              '<ls>R. ed. SCHL.', '<ls n="R. ed. SCHL.',
              '<ls>R. ed. Ser.', '<ls n="R. ed. Ser.',
              '<ls>R. (ed. ŚRĪR.)', '<ls>R. ed. ŚRĪR.',
              '<ls n="R. ed. ŚRĪR.',
            ],
          },
    
 'pwkvna': {'dictcode': 'pwkvn',
    'lscode': 'R. ed. Bomb.', 'nparms': [3,4],
    'skip': skips,
    'skip1': [],
           },
  'pwkvnb': {'dictcode': 'pwkvn',
    'lscode': 'R.', 'nparms': [2,3,4],
    'skip': skips,
    'skip1': ['<ls>R. GORR.', '<ls n="R. GORR.',
              '<ls>R. SCHL.', '<ls n="R. SCHL.',
              '<ls>R. ed. Bomb.', '<ls n="R. ed. Bomb.',
              '<ls>R. ed. GORR.', '<ls n="R. ed. GORR.',
              '<ls>R. ed. SCHL.', '<ls n="R. ed. SCHL.',
              '<ls>R. ed. Ser.', '<ls n="R. ed. Ser.',
              '<ls>R. (ed. ŚRĪR.)', '<ls>R. ed. ŚRĪR.',
              '<ls n="R. ed. ŚRĪR.',
            ],
          },
    

 'scha': {'dictcode': 'sch',
    'lscode': 'R. ed. Bomb.', 'nparms': [3,4],
    'skip': [],
    'skip1': [],
         },
 'schb': {'dictcode': 'sch',
    'lscode': 'R.', 'nparms': [2,3,4],
    'skip': skips,
    'skip1': ['<ls>R. Gorr.', '<ls n="R. GORR.',
              '<ls n="R. Gorr.',
              #'<ls>R. SCHL.', '<ls n="R. SCHL.',
              '<ls>R. ed. Bomb.', '<ls n="R. ed. Bomb.',
              #'<ls>R. ed. Gorr.', '<ls n="R. ed. GORR.',
              #'<ls>R. ed. SCHL.', '<ls n="R. ed. SCHL.',
              #'<ls>R. ed. Ser.', '<ls n="R. ed. Ser.',
              #'<ls>R. (ed. ŚRĪR.)', '<ls>R. ed. ŚRĪR.',
              #'<ls n="R. ed. ŚRĪR.',
            ],
          },
    

 'mwa': {'dictcode': 'mw',
    'lscode': 'R. ed. Bomb.', 'nparms': [3,4],
    'skip': [],
    'skip1': [],
           },
 'mwa1': {'dictcode': 'mw',
    'lscode': 'R. \(B.\)', 'nparms': [3],  # R. (B.)  OR R. (B)
    'skip': [],
    'skip1': [],
           },
 'mwa2': {'dictcode': 'mw',
    'lscode': 'R. \(B\)', 'nparms': [3],  # R. (B.)  OR R. (B)
    'skip': [],
    'skip1': [],
           },

 'mwb': {'dictcode': 'mw',
    'lscode': 'R.', 'nparms': [3],
    'skip': skips,
    'skip1': ['<ls>R. Gorr.', '<ls n="R. GORR.',
              '<ls n="R. Gorr.',
              #'<ls>R. SCHL.', '<ls n="R. SCHL.',
              '<ls>R. ed. Bomb.', '<ls n="R. ed. Bomb.',
              '<ls>R. (B.)', 
              '<ls>R. (B)', 
              #'<ls>R. ed. Gorr.', '<ls n="R. ed. GORR.',
              #'<ls>R. ed. SCHL.', '<ls n="R. ed. SCHL.',
              #'<ls>R. ed. Ser.', '<ls n="R. ed. Ser.',
              #'<ls>R. (ed. ŚRĪR.)', '<ls>R. ed. ŚRĪR.',
              #'<ls n="R. ed. ŚRĪR.',
            ],
          },
 'mwb1': {'dictcode': 'mw',
          'outopt': '1',
    'lscode': 'R.', 'nparms': [3],
    'skip': skips,
    'skip1': ['<ls>R. Gorr.', '<ls n="R. GORR.',
              '<ls n="R. Gorr.',
              #'<ls>R. SCHL.', '<ls n="R. SCHL.',
              '<ls>R. ed. Bomb.', '<ls n="R. ed. Bomb.',
              '<ls>R. (B.)', 
              '<ls>R. (B)', 
              #'<ls>R. ed. Gorr.', '<ls n="R. ed. GORR.',
              #'<ls>R. ed. SCHL.', '<ls n="R. ed. SCHL.',
              #'<ls>R. ed. Ser.', '<ls n="R. ed. Ser.',
              #'<ls>R. (ed. ŚRĪR.)', '<ls>R. ed. ŚRĪR.',
              #'<ls n="R. ed. ŚRĪR.',
            ],
          },

 'mwb2': {'dictcode': 'mw',
          'outopt': '1',
    'lscode': 'R.', 'nparms': [3],
          'skip': [],
    'skip1': [],
          },

}

