"""
Phase D: Draft pwgab_input.txt — German abbreviation expansions for PWG.

Format (matches MW's mwab_input.txt convention):
  abbr<TAB><id>abbr</id> <disp>German expansion - English gloss</disp>[ <INFER/>]

The expansions table below is hand-curated based on standard German
lexicographic abbreviation conventions used in the Petersburg Dictionary.
Uncertain expansions are flagged with the <INFER/> marker (following MW
convention). Reviewers should focus on those first.

Output:
  pwgab_input_draft.txt
"""

import sys
import re
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

HERE = Path(__file__).resolve().parent
ABBR_FILE = HERE / "PWG_abbr_global.txt"
OUT = HERE / "pwgab_input_draft.txt"

EXPANSIONS = {
    "ANUKR.": ("Anukramaṇī", "Vedic index/Anukramaṇī reference", True),
    "Abl.": ("Ablativ", "ablative (case)", False),
    "Ableitt.": ("Ableitungen", "derivations", False),
    "Abschn.": ("Abschnitt", "section", False),
    "Acc.": ("Accusativ", "accusative (case)", False),
    "Adhy.": ("Adhyāya", "chapter (Sanskrit text division)", False),
    "Adj. compp.": ("Adjektivische Composita", "adjectival compounds", False),
    "Adnn.": ("Adnomina", "qualifying nouns/adjectives", True),
    "Adnott.": ("Adnotationen", "annotations", False),
    "Allgem.": ("allgemein", "in general", False),
    "Anf.": ("Anfang", "beginning", False),
    "Ang.": ("Angabe", "statement / indication", False),
    "Anm.": ("Anmerkung", "note", False),
    "Anmm.": ("Anmerkungen", "notes (pl.)", False),
    "Annott.": ("Annotationen", "annotations", False),
    "Ant.": ("Antike?", "antiquity (?)", True),
    "Aor.": ("Aorist", "aorist", False),
    "Appell.": ("Appellativum", "appellative / common noun", False),
    "Appos.": ("Apposition", "apposition", False),
    "Arithm.": ("Arithmetik", "arithmetic", False),
    "Art.": ("Artikel", "article (entry)", False),
    "Assimil.": ("Assimilation", "assimilation", False),
    "Astrol.": ("Astrologie", "astrology", False),
    "Astron.": ("Astronomie", "astronomy", False),
    "Aufl.": ("Auflage", "edition / printing", False),
    "Augm.": ("Augment", "augment (verbal prefix a-)", False),
    "Ausdr.": ("Ausdruck", "expression", False),
    "Ausg.": ("Ausgabe", "edition", False),
    "Ausgg.": ("Ausgaben", "editions", False),
    "Ausl.": ("Auslaut", "final sound (phonetics)", False),
    "Ausn.": ("Ausnahme", "exception", False),
    "Aut.": ("Autor", "author", False),
    "Autor.": ("Autoren", "authors", False),
    "Autorr.": ("Autoren", "authors (variant)", False),
    "Autt.": ("Auctores", "authors (Latin)", False),
    "Bde.": ("Bände", "volumes", False),
    "Bed.": ("Bedeutung", "meaning", False),
    "Bedd.": ("Bedeutungen", "meanings", False),
    "Bedeut.": ("Bedeutung", "meaning", False),
    "Bedeutt.": ("Bedeutungen", "meanings", False),
    "Beim.": ("Beiname", "epithet", False),
    "Bein.": ("Beiname", "epithet", False),
    "Beinn.": ("Beinamen", "epithets", False),
    "Beis.": ("Beisatz", "apposition / addition", False),
    "Beisatz.": ("Beisatz", "apposition", False),
    "Beisp.": ("Beispiel", "example", False),
    "Beispp.": ("Beispiele", "examples", False),
    "Beiw.": ("Beiwort", "adjective / attribute", False),
    "Beiww.": ("Beiwörter", "adjectives", False),
    "Bemerk.": ("Bemerkung", "remark", False),
    "Berl. Mpt": ("Berliner Manuskript", "Berlin manuscript", False),
    "Berl.": ("Berliner", "Berlin (manuscript / library)", False),
    "Bes.": ("Besonderheit", "particularity", True),
    "Besond.": ("besonders", "especially", False),
    "Bez.": ("Bezeichnung", "designation", False),
    "Bezz.": ("Bezeichnungen", "designations", False),
    "Bild.": ("Bildung", "formation", False),
    "Bildl.": ("bildlich", "figurative", False),
    "Buddh.": ("buddhistisch", "Buddhist", False),
    "Calc. Ausg.": ("Calcuttaer Ausgabe", "Calcutta edition", False),
    "Capp.": ("Capita", "chapters (Latin pl.)", False),
    "Casusverh.": ("Casusverhältnis", "case-relation", False),
    "Caus.": ("Causativ", "causative", False),
    "Char.": ("Charakter", "character", False),
    "Chr.": ("Christus", "Christ (for AD/BC dating)", False),
    "Cit.": ("Citat", "citation", False),
    "Comm.": ("Commentar", "commentary", False),
    "Comment.": ("Commentar", "commentary", False),
    "Commentat.": ("Commentator", "commentator", False),
    "Commentatt.": ("Commentatoren", "commentators", False),
    "Commentt.": ("Commentatores", "commentators (Latin)", False),
    "Comp.": ("Compositum", "compound", False),
    "Compar.": ("Comparativ", "comparative", False),
    "Compp.": ("Composita", "compounds", False),
    "Condit.": ("Conditionalis", "conditional", False),
    "Conj.": ("Conjunctiv", "subjunctive", False),
    "Conjj.": ("Conjunctive", "subjunctives", False),
    "Conjug.": ("Conjugation", "conjugation", False),
    "Constr.": ("Construction", "construction", False),
    "Corigg.": ("Corrigenda", "corrections (Latin) — likely typo of Corrigg.", True),
    "Corr.": ("Correctur", "correction", False),
    "Correl.": ("Correlativum", "correlative", False),
    "Correlat.": ("Correlativ", "correlative", False),
    "Corrig.": ("Corrigendum", "correction (Latin)", False),
    "Corrigg.": ("Corrigenda", "corrections (Latin pl.)", False),
    "Cultus.": ("Cultus", "cult / ritual practice", False),
    "D.": ("Daselbst", "in the same place (ibid.)", True),
    "Das.": ("daselbst", "in the same place (ibid.)", False),
    "Dat.": ("Dativ", "dative (case)", False),
    "Dec.": ("December", "December", False),
    "Decl.": ("Declination", "declension", False),
    "Declin.": ("Declination", "declension", False),
    "Denom.": ("Denominativ", "denominative", False),
    "Derivv.": ("Derivata", "derivatives", False),
    "Ders.": ("derselbe", "the same (m.)", False),
    "Desid.": ("Desiderativ", "desiderative", False),
    "Dioscor.": ("Dioscorides", "Dioscorides (Greek pharmacologist)", False),
    "Dist.": ("Distich", "distich (two-line verse)", False),
    "Dramat.": ("Dramatik", "drama / dramatic literature", False),
    "Du.": ("Dualis", "dual (number)", False),
    "Eig.": ("eigentlich", "properly / strictly", False),
    "Eigenn.": ("Eigenname", "proper name", False),
    "Einl.": ("Einleitung", "introduction", False),
    "Einsch.": ("Einschiebsel", "insertion", False),
    "Einschieb.": ("Einschiebung", "insertion", False),
    "Emend.": ("Emendation", "emendation", False),
    "End.": ("Endung", "ending", False),
    "Epith.": ("Epitheton", "epithet", False),
    "Erg.": ("Ergänzung", "supplement / completion", False),
    "Ergänz.": ("Ergänzung", "supplement", False),
    "Erkl.": ("Erklärung", "explanation", False),
    "Erkll.": ("Erklärungen", "explanations", False),
    "Erklär.": ("Erklärung", "explanation", False),
    "Erklärr.": ("Erklärungen", "explanations", False),
    "Erll.": ("Erklärungen", "explanations (variant)", False),
    "Erläutt.": ("Erläuterungen", "elucidations", False),
    "Es.": ("?", "uncertain", True),
    "Etym.": ("Etymologie", "etymology", False),
    "Euphem.": ("Euphemismus", "euphemism", False),
    "Fem.": ("Femininum", "feminine", False),
    "Folg.": ("Folgendes", "the following", False),
    "Fut.": ("Futurum", "future tense", False),
    "Gegend.": ("Gegenstände?", "objects (?)", True),
    "Gegens.": ("Gegensatz", "opposite / contrast", False),
    "Gegenss.": ("Gegensätze", "opposites", False),
    "Gegenst.": ("Gegenstand", "object", False),
    "Gen.": ("Genitiv", "genitive (case)", False),
    "Geom.": ("Geometrie", "geometry", False),
    "Gerichtsspr.": ("Gerichtssprache", "legal language", False),
    "Geschl.": ("Geschlecht", "gender / lineage", False),
    "Gr.": ("Grammatik", "grammar (?)", True),
    "Gramm.": ("Grammatik", "grammar", False),
    "Grammat.": ("Grammatiker", "grammarian(s)", False),
    "Hamb. Hdschrr.": ("Hamburger Handschriften", "Hamburg manuscripts", False),
    "Handschr.": ("Handschrift", "manuscript", False),
    "Handschrr.": ("Handschriften", "manuscripts", False),
    "Hdchr.": ("Handschrift", "manuscript (variant spelling)", True),
    "Hdschr.": ("Handschrift", "manuscript", False),
    "Hdschrr.": ("Handschriften", "manuscripts", False),
    "Hdsichr.": ("Handschrift", "manuscript (likely typo)", True),
    "Hem.": ("Hemacandra", "Hemacandra (Sanskrit lexicographer)", True),
    "Hypokor.": ("Hypokoristikum", "hypocoristic (term of endearment)", False),
    "Hypokorr.": ("Hypokoristiken", "hypocoristics", False),
    "Identif.": ("Identifikation", "identification", False),
    "Imacc.": ("?", "uncertain — possibly Imperfectum accentuiert", True),
    "Imperf.": ("Imperfectum", "imperfect (tense)", False),
    "Impl.": ("Implizit?", "implicit (?)", True),
    "Incomp.": ("Incompositum", "non-compound", False),
    "Ind.": ("Indien / indisch", "India / Indian", True),
    "Indecll.": ("Indeclinabilia", "indeclinables", False),
    "Inf.": ("Infinitiv", "infinitive", False),
    "Infin.": ("Infinitiv", "infinitive", False),
    "Inhaltsv.": ("Inhaltsverzeichnis", "table of contents", False),
    "Inhaltsverz.": ("Inhaltsverzeichnis", "table of contents", False),
    "Insbes.": ("insbesondere", "in particular", False),
    "Inschr.": ("Inschrift", "inscription", False),
    "Inschrr.": ("Inschriften", "inscriptions", False),
    "Instr.": ("Instrumental", "instrumental (case)", False),
    "Intens.": ("Intensiv", "intensive", False),
    "Interj.": ("Interjektion", "interjection", False),
    "Interpol.": ("Interpolation", "interpolation", False),
    "Interpr.": ("Interpretation", "interpretation", False),
    "Jahrh.": ("Jahrhundert", "century", False),
    "Jmd.": ("Jemand", "someone", False),
    "Kap.": ("Kapitel", "chapter", False),
    "Kat.": ("Katalog", "catalog", False),
    "Kl.": ("Klasse", "(verb) class", False),
    "Lexicc.": ("Lexici", "lexica (Latin gen.pl.)", False),
    "Lexicogr.": ("Lexicograph", "lexicographer", False),
    "Lexicogrr.": ("Lexicographen", "lexicographers", False),
    "Lexx.": ("Lexica", "lexica (Latin pl.)", False),
    "Lit.": ("Literatur", "literature", False),
    "Litt.": ("literarisch", "literary", False),
    "Loc.": ("Locativ", "locative (case)", False),
    "MBH.": ("Mahābhārata", "Mahābhārata (Sanskrit epic)", False),
    "Mannsn.": ("Mannsname", "man's name", False),
    "Math.": ("Mathematik", "mathematics", False),
    "Mathem.": ("Mathematik", "mathematics", False),
    "Mathemm.": ("Mathematiker", "mathematicians", False),
    "Medic.": ("Medicin", "medicine", False),
    "Mpt.": ("Manuskript", "manuscript", False),
    "Mspt.": ("Manuskript", "manuscript", False),
    "Mss.": ("Manuscripta", "manuscripts (Latin pl.)", False),
    "Myth.": ("Mythologie", "mythology", False),
    "Mythol.": ("Mythologie", "mythology", False),
    "N. Pr.": ("Nomen Proprium", "proper noun (capitalized form)", False),
    "N. abstr.": ("Nomen abstractum", "abstract noun", False),
    "N. appell.": ("Nomen appellativum", "appellative / common noun", False),
    "N. pr.": ("Nomen proprium", "proper noun", False),
    "N.": ("Name / Namen", "name (uncertain in isolation — see local list)", True),
    "Nachk.": ("Nachkomme", "descendant", False),
    "Nachtr.": ("Nachtrag", "addendum", False),
    "Nachtrr.": ("Nachträge", "addenda", False),
    "Nebenf.": ("Nebenform", "secondary / variant form", False),
    "Neg.": ("Negation", "negation", False),
    "Negat.": ("Negation", "negation", False),
    "Nn. prr.": ("Nomina propria", "proper nouns (Latin pl.)", False),
    "Nn.": ("Nomina", "nouns (Latin pl.)", False),
    "Nom. abstr.": ("Nomen abstractum", "abstract noun", False),
    "Nom. act.": ("Nomen actionis", "action noun", False),
    "Nom. ag.": ("Nomen agentis", "agent noun", False),
    "Nom. appell.": ("Nomen appellativum", "common noun", False),
    "Nom. pr.": ("Nomen proprium", "proper noun", False),
    "Nom.": ("Nominativ", "nominative (case)", False),
    "Nomen pr.": ("Nomen proprium", "proper noun", False),
    "Nomina ag.": ("Nomina agentis", "agent nouns", False),
    "Nov.": ("November", "November", False),
    "Obj.": ("Objekt", "object", False),
    "Ort.": ("Ortsname", "place name", False),
    "Ortsadv.": ("Ortsadverb", "locative adverb", False),
    "Ortsadvv.": ("Ortsadverbien", "locative adverbs", False),
    "Padap.": ("Padapāṭha", "Padapāṭha (Vedic word-by-word recitation)", False),
    "Par. Mpt": ("Pariser Manuskript", "Paris manuscript", False),
    "Parenth.": ("Parenthese", "parenthesis", False),
    "Part.": ("Particip", "participle", False),
    "Partic.": ("Participium", "participle", False),
    "Participialfut.": ("Participialfuturum", "participial future", False),
    "Patron.": ("Patronymikum", "patronymic", False),
    "Pers.": ("Person", "person (grammatical)", True),
    "Person.": ("Person", "person", False),
    "Personif.": ("Personifikation", "personification", False),
    "Phil.": ("Philosophie", "philosophy (?)", True),
    "Philos.": ("Philosophie", "philosophy", False),
    "Pl.": ("Plural", "plural", False),
    "Praep.": ("Praeposition", "preposition", False),
    "Pron.": ("Pronomen", "pronoun", False),
    "Pronomm.": ("Pronomina", "pronouns", False),
    "Pros.": ("Prosa", "prose", False),
    "Präp.": ("Präposition", "preposition", False),
    "Präpp.": ("Präpositionen", "prepositions", False),
    "Randgl.": ("Randglosse", "marginal gloss", False),
    "Rec.": ("Recension", "recension (text version)", False),
    "Rechtsspr.": ("Rechtssprache", "legal language", False),
    "Redupl.": ("Reduplikation", "reduplication", False),
    "Reduplicat.": ("Reduplikation", "reduplication", False),
    "Rel.": ("Relativ", "relative", False),
    "Rell.": ("Relativa", "relatives", False),
    "Rhet.": ("Rhetorik", "rhetoric", False),
    "S. u.": ("Siehe unten", "see below", False),
    "Sch.": ("Scholion", "scholion / commentary", False),
    "Schol.": ("Scholion", "scholion", False),
    "Scholl.": ("Scholien", "scholia", False),
    "Schreib.": ("Schreibung", "spelling / writing", False),
    "Sg.": ("Singular", "singular", False),
    "Spr.": ("Spruch", "saying / verse (Indische Sprüche)", False),
    "St.": ("Stelle", "place / passage", True),
    "Subj.": ("Subjekt", "subject", False),
    "Subst.": ("Substantiv", "substantive / noun", False),
    "Suff.": ("Suffix", "suffix", False),
    "Superl.": ("Superlativ", "superlative", False),
    "Suppl.": ("Supplement", "supplement", False),
    "Syn.": ("Synonym", "synonym", False),
    "Synonn.": ("Synonyma", "synonyms", False),
    "Th.": ("Theil", "part", False),
    "Tit.": ("Titel", "title", False),
    "Titelbl.": ("Titelblatt", "title page", False),
    "Trigl.": ("Triglotton / Trikāṇḍaśeṣa", "trilingual list / Trikāṇḍaśeṣa", True),
    "Ueberh.": ("überhaupt", "in general (older spelling)", False),
    "Uebers.": ("Übersetzung", "translation (older spelling)", False),
    "Ueberschr.": ("Überschrift", "heading (older spelling)", False),
    "Uebertr.": ("Übertragung", "transmission / translation (older sp.)", False),
    "Uneig.": ("uneigentlich", "improperly / figuratively", False),
    "Unterrschrr.": ("Unterschriften", "signatures (likely typo)", True),
    "Untersch.": ("Unterscheidung", "distinction", False),
    "Unterschr.": ("Unterschrift", "signature / colophon", False),
    "Unterschrr.": ("Unterschriften", "signatures / colophons", False),
    "Urspr.": ("ursprünglich", "originally", False),
    "V. l.": ("varia lectio", "variant reading (capitalized)", False),
    "Var. l.": ("varia lectio", "variant reading", False),
    "Var.": ("Variante", "variant", False),
    "Varr.": ("Varianten", "variants", False),
    "Verb. fin.": ("Verbum finitum", "finite verb", False),
    "Verb.": ("Verbum", "verb", False),
    "Verbind.": ("Verbindung", "connection / combination", False),
    "Verbindd.": ("Verbindungen", "connections", False),
    "Verf.": ("Verfasser", "author", False),
    "Verff.": ("Verfasser", "authors (plural)", False),
    "Vergl.": ("vergleiche", "compare", False),
    "Vern.": ("Vernachlässigung", "neglect / omission", True),
    "Verz.": ("Verzeichnis", "register / list", False),
    "Viell.": ("vielleicht", "perhaps", False),
    "Voc.": ("Vocativ", "vocative (case)", False),
    "Volksn.": ("Volksname", "people's / tribe name", False),
    "Vollst.": ("vollständig", "complete", False),
    "Vulg.": ("Vulgata / vulgär", "Vulgate / vulgar", True),
    "W.": ("Wort", "word", True),
    "Weg.": ("wegen", "because of", False),
    "Wortm.": ("Wortmasse?", "word material (?)", True),
    "Ww.": ("Wörter", "words", False),
    "Wörterb.": ("Wörterbuch", "dictionary", False),
    "Z. B.": ("Zum Beispiel", "for example", False),
    "Zahladvv.": ("Zahladverbien", "numerical adverbs", False),
    "Zahlw.": ("Zahlwort", "numeral", False),
    "Zeitww.": ("Zeitwörter", "verbs", False),
    "Zus.": ("Zusatz", "addition", False),
    "Zusamm.": ("Zusammensetzung", "composition", False),
    "Zusammeng.": ("zusammengezogen", "contracted", False),
    "Zusammenh.": ("Zusammenhang", "context", False),
    "Zusammens.": ("Zusammensetzung", "composition", False),
    "Zusammenss.": ("Zusammensetzungen", "compositions", False),
    "a. O.": ("am Ort", "at the place cited", False),
    "a. St.": ("an der Stelle", "in the passage", True),
    "a. a. O.": ("am angeführten Ort", "in the place cited (op. cit.)", False),
    "aa.": ("?", "uncertain", True),
    "abgedr.": ("abgedruckt", "printed", False),
    "abgel.": ("abgeleitet", "derived", False),
    "abgiebt.": ("abgibt", "gives (older orthography)", False),
    "abl.": ("ablativ", "ablative", False),
    "ablat.": ("ablativ", "ablative", False),
    "absol.": ("absolut / absolutiv", "absolute / absolutive", False),
    "absolut.": ("absolut", "absolute", False),
    "abstr.": ("abstrakt", "abstract", False),
    "abw.": ("abweichend", "deviating", False),
    "acc. ag.": ("accusativus agentis", "accusative of agent", False),
    "acc.": ("accusativ", "accusative", False),
    "accusat.": ("accusativ", "accusative", False),
    "act.": ("activ", "active", False),
    "adj. Comp.": ("adjektivisches Compositum", "adjectival compound", False),
    "adj. comp.": ("adjektivisches Compositum", "adjectival compound", False),
    "adj.": ("adjektivisch", "adjective / adjectival", False),
    "adject.": ("adjektivisch", "adjective", False),
    "adjj.": ("adjektivisch (Plural)", "adjectives", False),
    "adv. compp.": ("adverbiale Composita", "adverbial compounds", False),
    "adverb. comp.": ("adverbiales Compositum", "adverbial compound", False),
    "adverb.": ("adverbial", "adverbial", False),
    "adverbb.": ("adverbialia", "adverbials", False),
    "advv.": ("Adverbien", "adverbs", False),
    "alleg.": ("allegorisch", "allegorical", False),
    "allg.": ("allgemein", "in general", False),
    "allgem.": ("allgemein", "in general", False),
    "alphab.": ("alphabetisch", "alphabetical", False),
    "an.": ("anders / anom.?", "otherwise / anom.", True),
    "anderndemonstrr.": ("an anderen Demonstrativen", "to other demonstratives", True),
    "aneig.": ("aneignen?", "appropriate (?)", True),
    "angebl.": ("angeblich", "allegedly", False),
    "angef.": ("angeführt", "cited", False),
    "anl.": ("anlautend", "initial (phonetics)", False),
    "anom.": ("anomal", "anomalous", False),
    "anomal.": ("anomal", "anomalous", False),
    "aor.": ("Aorist", "aorist", False),
    "appell.": ("appellativ", "appellative", False),
    "appellat.": ("appellativ", "appellative", False),
    "appos.": ("Apposition", "apposition", False),
    "arch.": ("archaisch", "archaic", False),
    "astr.": ("Astronomie / Astrologie", "astronomy / astrology", True),
    "astrol.": ("astrologisch", "astrological", False),
    "astrolog.": ("astrologisch", "astrological", False),
    "astron.": ("astronomisch", "astronomical", False),
    "astronom.": ("astronomisch", "astronomical", False),
    "attribut.": ("attributiv", "attributive", False),
    "aufgef.": ("aufgefasst", "understood (as)", False),
    "ausg.": ("ausgegeben / ausgesprochen", "issued / pronounced", True),
    "ausgeh.": ("ausgehend", "ending in", False),
    "ausgez.": ("ausgezeichnet", "distinguished / marked", False),
    "auslaut.": ("auslautend", "final (phonetics)", False),
    "ausnahmsw.": ("ausnahmsweise", "exceptionally", False),
    "bed.": ("bedeutet", "means", False),
    "beg.": ("beginnt", "begins", False),
    "beim.": ("Beiname?", "epithet (?) / preposition 'at the'", True),
    "bes.": ("besonders", "especially", False),
    "beschr.": ("beschrieben", "described", False),
    "besond.": ("besonders", "especially", False),
    "bespr.": ("besprochen", "discussed", False),
    "best.": ("bestimmt", "definite / certain", False),
    "betr.": ("betreffend", "concerning", False),
    "bez.": ("bezeichnet / beziehungsweise", "designates / respectively", False),
    "bildl.": ("bildlich", "figurative", False),
    "bisw.": ("bisweilen", "sometimes", False),
    "buddh.": ("buddhistisch", "Buddhist", False),
    "buddhist.": ("buddhistisch", "Buddhist", False),
    "c.": ("cum", "with (Latin)", False),
    "card.": ("cardinal", "cardinal (number)", False),
    "cas.": ("casus", "case (Latin)", False),
    "cass.": ("casus", "cases (Latin pl.)", False),
    "caus.": ("causativ", "causative", False),
    "causat.": ("causativ", "causative", False),
    "causs.": ("causativa", "causatives", False),
    "cfr.": ("confer", "compare (Latin)", False),
    "cit.": ("citiert", "cited", False),
    "class.": ("klassisch", "classical", False),
    "coll.": ("kollektiv", "collective", False),
    "collect.": ("kollektiv", "collective", False),
    "comp.": ("Compositum", "compound", False),
    "compar.": ("Comparativ", "comparative", False),
    "comparat.": ("Comparativ", "comparative", False),
    "compon.": ("Componente", "component", False),
    "compos.": ("Compositum", "compound", False),
    "compp.": ("composita", "compounds", False),
    "concr.": ("konkret", "concrete", False),
    "condit.": ("konditional / Conditionalis", "conditional", False),
    "conj.": ("Conjunctiv / Conjunction", "subjunctive / conjunction", True),
    "conjunct.": ("Conjunctiv", "subjunctive", False),
    "constr.": ("construiert", "construed", False),
    "coord.": ("koordiniert", "coordinated", False),
    "cop.": ("Kopula", "copula", False),
    "copul. comp.": ("kopulatives Compositum", "copulative compound (dvandva)", False),
    "copul.": ("kopulativ", "copulative", False),
    "copulat.": ("kopulativ", "copulative", False),
    "correl.": ("korrelativ", "correlative", False),
    "correlat.": ("korrelativ", "correlative", False),
    "corrigg.": ("corrigenda", "corrigenda", False),
    "d. St.": ("die Stelle", "the passage", False),
    "d. W.": ("das Wort", "the word", False),
    "d. Ww.": ("die Wörter", "the words", False),
    "d. f. W.": ("das folgende Wort", "the following word", False),
    "d. fg. W.": ("das folgende Wort", "the following word", False),
    "d. folg. W.": ("das folgende Wort", "the following word", False),
    "d. h.": ("das heißt", "that is (i.e.)", False),
    "d. i.": ("das ist", "that is", False),
    "d. l. W.": ("das letzte Wort", "the last word", True),
    "d. vorherg. W.": ("das vorhergehende Wort", "the preceding word", False),
    "d.": ("der / die / das", "the (definite article — ambiguous)", True),
    "da.": ("daselbst", "in the same place", False),
    "dag.": ("dagegen", "on the other hand", False),
    "danom. abstr.": ("denominales Abstraktum", "denominal abstract noun", True),
    "das.": ("daselbst", "in the same place (ibid.)", False),
    "dass.": ("dasselbe", "the same", False),
    "dat.": ("Dativ", "dative", False),
    "datt.": ("Dative", "datives", False),
    "dazw.": ("dazwischen", "between", False),
    "dd. Ww.": ("die beiden Wörter", "the two words", False),
    "dd.": ("die beiden", "the two", False),
    "decl.": ("Declination", "declension", False),
    "declin.": ("Declination", "declension", False),
    "defect.": ("defectiv", "defective", False),
    "defin.": ("definit", "definite", False),
    "dem.": ("Demonstrativ", "demonstrative", False),
    "demin.": ("Diminutiv", "diminutive", False),
    "deminn.": ("Diminutive", "diminutives", False),
    "demonstr.": ("Demonstrativ", "demonstrative", False),
    "demonstratt.": ("Demonstrativa", "demonstratives", False),
    "demonstrr.": ("Demonstrativa", "demonstratives", False),
    "dems.": ("demselben", "to the same", False),
    "denom.": ("denominativ", "denominative", False),
    "denomin.": ("denominativ", "denominative", False),
    "denominn.": ("denominativa", "denominatives", False),
    "denomm.": ("denominativa", "denominatives", False),
    "dergen.": ("dergleichen (Genitiv)", "of the like", True),
    "dergl.": ("dergleichen", "the like", False),
    "deriv.": ("Derivat", "derivative", False),
    "derivv.": ("Derivata", "derivatives", False),
    "ders.": ("derselbe", "the same (m.)", False),
    "derselb.": ("derselbe", "the same", False),
    "des.": ("desselben", "of the same", False),
    "desgl.": ("desgleichen", "likewise", False),
    "desid.": ("Desiderativ", "desiderative", False),
    "desider.": ("Desiderativ", "desiderative", False),
    "dess.": ("desselben", "of the same", False),
    "desselb.": ("desselben", "of the same", False),
    "dgl.": ("dergleichen", "the like", False),
    "dies. St.": ("diese Stelle", "this passage", False),
    "dies.": ("dieser", "this", False),
    "diesem.": ("diesem", "to this", False),
    "diess.": ("dieses (older sp.)", "this (n., older sp.)", False),
    "dist.": ("Distich", "distich", False),
    "distr.": ("distributiv", "distributive", False),
    "distrib.": ("distributiv", "distributive", False),
    "dopp.": ("doppelt", "double", False),
    "du.": ("Dual", "dual", False),
    "ebd.": ("ebenda", "in the same place", False),
    "eben.": ("ebenso", "likewise", False),
    "ed.": ("editio", "edition (Latin)", False),
    "edend.": ("edendum", "to be edited", False),
    "eig.": ("eigentlich", "properly", False),
    "eigentl.": ("eigentlich", "properly", False),
    "einf.": ("einfach", "simple", False),
    "einschl.": ("einschließlich", "inclusively", False),
    "einz.": ("einzeln", "individual / single", False),
    "elid.": ("elidiert", "elided", False),
    "ellipt.": ("elliptisch", "elliptic", False),
    "encl.": ("enklitisch", "enclitic", False),
    "enclit.": ("enklitisch", "enclitic", False),
    "engl.": ("englisch", "English", False),
    "enklit.": ("enklitisch", "enclitic", False),
    "entspr.": ("entspricht", "corresponds to", False),
    "erg.": ("ergänze", "supply (imperative)", False),
    "erkl.": ("erklärt", "explained", False),
    "etc.": ("et cetera", "et cetera", False),
    "etym.": ("etymologisch", "etymological", False),
    "etymol.": ("etymologisch", "etymological", False),
    "euph.": ("euphemistisch / Euphemismus", "euphemistic / euphemism", False),
    "euphem.": ("euphemistisch", "euphemistic", False),
    "excl.": ("exklusiv", "exclusive", False),
    "explet.": ("expletiv", "expletive", False),
    "fehlerh.": ("fehlerhaft", "erroneous", False),
    "femm.": ("feminina", "feminines", False),
    "fg.": ("folgend", "following", False),
    "fgg. Ww.": ("folgende Wörter", "following words", False),
    "fgg.": ("folgende", "the following (pl.)", False),
    "fig.": ("figürlich", "figurative", False),
    "fin.": ("finit", "finite", False),
    "folg. W.": ("folgendes Wort", "the following word", False),
    "folg. Ww.": ("folgende Wörter", "the following words", False),
    "folg.": ("folgend", "following", False),
    "folgend.": ("folgend", "following", False),
    "folgg. Ww.": ("folgende Wörter", "the following words", False),
    "folgg.": ("folgende", "the following (pl.)", False),
    "franz.": ("französisch", "French", False),
    "fut.": ("Futurum", "future", False),
    "futt.": ("Futura", "futures", False),
    "geb.": ("geboren", "born", False),
    "gebr.": ("gebraucht", "used", False),
    "geder.": ("gedeutet?", "interpreted (?)", True),
    "gedr.": ("gedruckt", "printed", False),
    "gehör.": ("gehörig", "belonging to", False),
    "gen.": ("Genitiv", "genitive", False),
    "genit.": ("Genitiv", "genitive", False),
    "genitt.": ("Genitive", "genitives", False),
    "genn.": ("genera", "genders / kinds", True),
    "geogr.": ("geographisch", "geographical", False),
    "ger.": ("Gerundium", "gerund", False),
    "gerund.": ("Gerundium", "gerund", False),
    "geschr.": ("geschrieben", "written", False),
    "gespr.": ("gesprochen", "spoken", False),
    "gew.": ("gewöhnlich", "usually", False),
    "gezwung.": ("gezwungen", "forced", False),
    "gramm.": ("grammatisch", "grammatical", False),
    "grammat.": ("grammatisch", "grammatical", False),
    "herausg.": ("herausgegeben", "edited by", False),
    "i. e.": ("id est", "that is (Latin)", False),
    "ibid.": ("ibidem", "in the same place (Latin)", False),
    "id.": ("idem", "the same (Latin)", False),
    "ident.": ("identisch", "identical", False),
    "identif.": ("identifiziert", "identified", False),
    "imp.": ("Imperativ", "imperative", False),
    "imper.": ("Imperativ", "imperative", False),
    "imperat.": ("Imperativ", "imperative", False),
    "imperf.": ("Imperfectum", "imperfect", False),
    "impers.": ("impersonal", "impersonal", False),
    "imperson.": ("impersonal", "impersonal", False),
    "incl.": ("inklusive", "inclusive", False),
    "incomp.": ("incompositum", "non-compound", False),
    "ind.": ("indisch / Indikativ", "Indian / indicative", True),
    "indecl.": ("indeclinabile", "indeclinable", False),
    "indecll.": ("indeclinabilia", "indeclinables", False),
    "indef.": ("indefinit", "indefinite", False),
    "indefin.": ("indefinit", "indefinite", False),
    "indic.": ("Indikativ", "indicative", False),
    "inf.": ("Infinitiv", "infinitive", False),
    "infin.": ("Infinitiv", "infinitive", False),
    "infinit.": ("Infinitiv", "infinitive", False),
    "insb.": ("insbesondere", "in particular", False),
    "insbes.": ("insbesondere", "in particular", False),
    "insens.": ("in sensu", "in the sense (of) (Latin)", False),
    "instr.": ("Instrumental", "instrumental", False),
    "instrans.": ("intransitiv (typo)", "intransitive (likely typo)", True),
    "instrr.": ("Instrumentalia", "instrumentals", False),
    "intens.": ("Intensiv", "intensive", False),
    "interr.": ("interrogativ", "interrogative", False),
    "interrog.": ("interrogativ", "interrogative", False),
    "interrogatt.": ("interrogativa", "interrogatives", False),
    "interrogg.": ("interrogativa", "interrogatives", False),
    "intr.": ("intransitiv", "intransitive", False),
    "intrans.": ("intransitiv", "intransitive", False),
    "intransit.": ("intransitiv", "intransitive", False),
    "jur.": ("juridisch", "juridical / legal", False),
    "körperl.": ("körperlich", "bodily", False),
    "lang.": ("langer Vocal / Sprache", "long vowel / language", True),
    "lith.": ("litauisch", "Lithuanian", False),
    "liturg.": ("liturgisch", "liturgical", False),
    "loc.": ("Locativ", "locative", False),
    "locc.": ("Locativa", "locatives", False),
    "log.": ("logisch", "logical", False),
    "mannigf.": ("mannigfaltig", "manifold / various", False),
    "masc.": ("Maskulinum", "masculine", False),
    "math.": ("mathematisch", "mathematical", False),
    "mathem.": ("mathematisch", "mathematical", False),
    "med.": ("medicinisch / medium", "medicinal / middle voice", True),
    "medic.": ("medicinisch", "medicinal", False),
    "met.": ("metonymisch / metaphorisch", "metonymical / metaphorical", True),
    "meton.": ("metonymisch", "metonymical", False),
    "metonym.": ("metonymisch", "metonymical", False),
    "metr.": ("metrisch", "metrical", False),
    "metron.": ("metronymisch", "metronymical", False),
    "metronn.": ("Metronymika", "metronymics", False),
    "mineral.": ("mineralogisch", "mineralogical", False),
    "mitact.": ("mit dem Activum", "with the active voice", False),
    "mitfolg.": ("mit folgendem", "with following", False),
    "moral.": ("moralisch", "moral", False),
    "musik.": ("musikalisch", "musical", False),
    "myst.": ("mystisch", "mystical", False),
    "myth.": ("mythologisch", "mythological", False),
    "mythol.": ("mythologisch", "mythological", False),
    "n. Chr.": ("nach Christus", "after Christ (AD)", False),
    "n. abstr.": ("nomen abstractum", "abstract noun", False),
    "n. pr.": ("nomen proprium", "proper noun", False),
    "nachf.": ("nachfolgend", "subsequent", False),
    "nachfolg.": ("nachfolgend", "subsequent", False),
    "nam.": ("namentlich", "especially / by name", False),
    "namentl.": ("namentlich", "especially / by name", False),
    "neg.": ("negativ", "negative", False),
    "negat.": ("negativ", "negative", False),
    "neutr.": ("Neutrum", "neuter", False),
    "niedrig.": ("niedrig", "low / base (style)", True),
    "nom. abst.": ("nomen abstractum", "abstract noun", False),
    "nom. abstr.": ("nomen abstractum", "abstract noun", False),
    "nom. abstract.": ("nomen abstractum", "abstract noun", False),
    "nom. act.": ("nomen actionis", "action noun", False),
    "nom. ag.": ("nomen agentis", "agent noun", False),
    "nom. card.": ("nomen cardinale", "cardinal number", False),
    "nom. gent.": ("nomen gentile", "gentilic noun", False),
    "nom. ord.": ("nomen ordinale", "ordinal number", False),
    "nom. ordin.": ("nomen ordinale", "ordinal number", False),
    "nom. pr.": ("nomen proprium", "proper noun", False),
    "nom.": ("Nominativ / nomen", "nominative / noun", False),
    "nomin.": ("Nominativ", "nominative", False),
    "nomm. antret.": ("nominibus antretend", "attaching to nouns", True),
    "nomm.": ("nomina", "nouns", False),
    "num. ordin.": ("numerale ordinale", "ordinal number", False),
    "num.": ("Numerale", "numeral", False),
    "näml.": ("nämlich", "namely", False),
    "obj.": ("Objekt", "object", False),
    "obl.": ("Obliquus", "oblique case", False),
    "od.": ("oder", "or", False),
    "omin.": ("Omen", "omen", True),
    "onomat.": ("onomatopoetisch", "onomatopoeic", False),
    "onomatop.": ("onomatopoetisch", "onomatopoeic", False),
    "opt.": ("Optativ", "optative", False),
    "ord.": ("Ordinalzahl", "ordinal number", False),
    "oxyt.": ("oxyton", "oxytone (final-stress)", False),
    "oxyton.": ("oxytoniert", "oxytone-accented", False),
    "p.": ("pagina", "page (Latin)", False),
    "parall.": ("Parallelstelle", "parallel passage", False),
    "parox.": ("paroxyton", "paroxytone", False),
    "paroxyt.": ("paroxytoniert", "paroxytone-accented", False),
    "part. fut. pass.": ("Participium futuri passivi", "future passive participle", False),
    "part.": ("Particip", "participle", False),
    "partic.": ("Participium", "participle", False),
    "particc.": ("Participia", "participles", False),
    "partit.": ("Partitiv", "partitive", False),
    "pass.": ("Passiv", "passive", False),
    "patr.": ("Patronymikum", "patronymic", False),
    "patron.": ("Patronymikum", "patronymic", False),
    "patronn.": ("Patronymika", "patronymics", False),
    "perf.": ("Perfectum", "perfect", False),
    "periphr.": ("periphrastisch", "periphrastic", False),
    "perisp.": ("perispomeniert", "perispomenon-accented", False),
    "pers.": ("Person / persisch", "person / Persian", True),
    "person.": ("Personal-", "personal", False),
    "personif.": ("personifiziert", "personified", False),
    "personific.": ("Personifizierung", "personification", False),
    "philos.": ("philosophisch", "philosophical", False),
    "pl.": ("Plural", "plural", False),
    "pleon.": ("pleonastisch", "pleonastic", False),
    "plur.": ("Plural", "plural", False),
    "poet.": ("poetisch", "poetic", False),
    "porox.": ("paroxyton (typo)", "paroxytone (typo)", True),
    "pos.": ("Positiv", "positive (degree)", False),
    "posit.": ("Positiv", "positive (degree)", False),
    "poss.": ("Possessiv", "possessive", False),
    "postp.": ("Postposition", "postposition", False),
    "pot.": ("Potential", "potential mood", False),
    "potent.": ("Potentialis", "potential mood", False),
    "praed.": ("Praedikat", "predicate", False),
    "praep.": ("Praeposition", "preposition", False),
    "praepos.": ("Praeposition", "preposition", False),
    "praeposs.": ("Praepositiones", "prepositions", False),
    "praepp.": ("Praepositionen", "prepositions", False),
    "praes.": ("Praesens", "present (tense)", False),
    "praet.": ("Praeteritum", "preterite / past", False),
    "prec.": ("Precativ", "precative / benedictive", False),
    "precat.": ("Precativ", "precative", False),
    "prim.": ("primär", "primary", False),
    "priv.": ("privativ", "privative", False),
    "prohib.": ("Prohibitiv", "prohibitive", False),
    "pron. rel.": ("pronomen relativum", "relative pronoun", False),
    "pron. subst.": ("pronomen substantivum", "substantive pronoun", False),
    "pron.": ("Pronomen", "pronoun", False),
    "pronn.": ("Pronomina", "pronouns", False),
    "pronom.": ("pronominal", "pronominal", False),
    "pronomm.": ("Pronomina", "pronouns", False),
    "propar.": ("proparoxyton (variant)", "proparoxytone", True),
    "proparax.": ("proparoxytone (typo)", "proparoxytone (typo)", True),
    "proparox.": ("proparoxytone", "proparoxytone", False),
    "proparoxyt.": ("proparoxytoniert", "proparoxytone-accented", False),
    "properisp.": ("properispomeniert", "properispomenon-accented", False),
    "propr.": ("proprium", "proper", False),
    "prädic.": ("prädikativ", "predicative", False),
    "präpp.": ("Präpositionen", "prepositions", False),
    "rathsam.": ("rathsam", "advisable (older orthography)", False),
    "recipr.": ("reziprok", "reciprocal", False),
    "redupl.": ("reduplikativ / Reduplikation", "reduplicative / reduplication", False),
    "reduplic.": ("Reduplikation", "reduplication", False),
    "refl.": ("reflexiv", "reflexive", False),
    "reflex.": ("reflexiv", "reflexive", False),
    "reg.": ("regelmäßig", "regular", False),
    "rel.": ("relativ", "relative", False),
    "relat.": ("relativ", "relative", False),
    "relig.": ("religiös", "religious", False),
    "resp.": ("respective", "respectively (Latin)", False),
    "rever.": ("reverentiell", "reverential / honorific", False),
    "rhet.": ("rhetorisch", "rhetorical", False),
    "s. a.": ("siehe auch", "see also", False),
    "s. d.": ("siehe das Wort", "see the word", False),
    "s. u.": ("siehe unten / siehe unter", "see below / see under", False),
    "s. v.": ("sub voce", "under the word (Latin)", False),
    "sc.": ("scilicet", "namely / understand (Latin)", False),
    "sg.": ("Singular", "singular", False),
    "sic.": ("sic", "thus (in the original)", False),
    "simpl.": ("simplex", "simple (verb form)", False),
    "sing.": ("Singular", "singular", False),
    "sog.": ("sogenannt", "so-called", False),
    "spec.": ("speciell", "specifically", False),
    "spiel.": ("spielend (auf)", "playing on (a word)", False),
    "sprüchw.": ("sprichwörtlich", "proverbial", False),
    "st.": ("statt", "instead of", False),
    "subj.": ("Subjekt", "subject", False),
    "subst.": ("Substantiv", "noun", False),
    "substt.": ("Substantiva", "nouns", False),
    "suff.": ("Suffix", "suffix", False),
    "superl.": ("Superlativ", "superlative", False),
    "superlat.": ("Superlativ", "superlative", False),
    "symb.": ("symbolisch", "symbolic", False),
    "syn.": ("Synonym", "synonym", False),
    "synekd.": ("synekdochisch", "synecdochic", False),
    "tautol.": ("tautologisch", "tautological", False),
    "techn.": ("technisch", "technical", False),
    "term. techn.": ("terminus technicus", "technical term", False),
    "term.": ("Terminus", "term", False),
    "trans.": ("transitiv", "transitive", False),
    "transit.": ("transitiv", "transitive", False),
    "trop.": ("tropisch", "figurative (trope)", False),
    "u. d.": ("und der/die/das", "and the (ambiguous — see local list)", True),
    "u. s. w.": ("und so weiter", "et cetera (etc.)", False),
    "uberh.": ("überhaupt (older sp.)", "in general (older spelling)", False),
    "umwendend.": ("umwendend", "turning (towards)", True),
    "unbel.": ("unbelegt", "not attested", False),
    "unbest.": ("unbestimmt", "indefinite", False),
    "uneig.": ("uneigentlich", "figuratively / improperly", False),
    "ungedr.": ("ungedruckt", "unprinted", False),
    "ungramm.": ("ungrammatisch", "ungrammatical", False),
    "ungrammat.": ("ungrammatisch", "ungrammatical", False),
    "unpers.": ("unpersönlich", "impersonal", False),
    "unreg.": ("unregelmäßig", "irregular", False),
    "unregelm.": ("unregelmäßig", "irregular", False),
    "unricht.": ("unrichtig", "incorrect", False),
    "urpsr.": ("ursprünglich (typo)", "originally (typo of urspr.)", True),
    "urspr.": ("ursprünglich", "originally", False),
    "ursprüngl.": ("ursprünglich", "originally", False),
    "v. Chr.": ("vor Christus", "before Christ (BC)", False),
    "v. a.": ("verbum activum", "active verb", False),
    "v. l.": ("varia lectio", "variant reading", False),
    "v. u.": ("von unten", "from below", False),
    "var. l.": ("varia lectio", "variant reading", False),
    "var.": ("Variante", "variant", False),
    "verb. fin.": ("verbum finitum", "finite verb", False),
    "verb.": ("Verbum", "verb", False),
    "verbb.": ("Verba", "verbs", False),
    "verdopp.": ("verdoppelt", "doubled", False),
    "vergl.": ("vergleiche", "compare", False),
    "versch.": ("verschieden", "different", False),
    "verschied.": ("verschieden", "different", False),
    "vgl.": ("vergleiche", "compare", False),
    "viell.": ("vielleicht", "perhaps", False),
    "viz.": ("videlicet", "namely (Latin)", False),
    "voc.": ("Vocativ", "vocative", False),
    "vollst.": ("vollständig", "complete", False),
    "vom.": ("vom", "from the", False),
    "vor. W.": ("voriges Wort", "previous (head)word", False),
    "vor.": ("voriges", "previous (entry)", False),
    "voran.": ("vorangehend", "preceding", False),
    "vorang.": ("vorangehend", "preceding", False),
    "vorangeh.": ("vorangehend", "preceding", False),
    "vorherg. W.": ("vorhergehendes Wort", "preceding word", False),
    "vorherg.": ("vorhergehend", "preceding", False),
    "vorhergeh. Ww.": ("vorhergehende Wörter", "preceding words", False),
    "vorhergeh.": ("vorhergehend", "preceding", False),
    "vulg.": ("vulgär", "vulgar / colloquial", False),
    "vv. ll.": ("variae lectiones", "variant readings (pl.)", False),
    "w.": ("Wort?", "word? (ambiguous — see context)", True),
    "weibl.": ("weiblich", "feminine", False),
    "z. B.": ("zum Beispiel", "for example", False),
    "z.": ("zu", "to", True),
    "zugl.": ("zugleich", "at the same time", False),
    "zus.": ("zusammen", "together", False),
    "zusammen.": ("zusammen", "together", False),
    "zusammeng.": ("zusammengezogen", "contracted", False),
    "zusammengef.": ("zusammengefasst", "summarized", False),
    "zusammenges.": ("zusammengesetzt", "compound (adj.)", False),
    "zusammengez.": ("zusammengezogen", "contracted", False),
    "zusammengezog.": ("zusammengezogen", "contracted", False),
    "ähnl.": ("ähnlich", "similar", False),
    "ält.": ("älter", "older", False),
    "überh.": ("überhaupt", "in general", False),
    "übers.": ("übersetzt", "translated", False),
    "überth.": ("überhaupt (typo)", "in general (typo of überh.)", True),
    "übertr.": ("übertragen", "transferred / metaphorical", False),
}

print(f"Reading abbreviation list from {ABBR_FILE}...", flush=True)
abbrs = []
with ABBR_FILE.open(encoding="utf-8") as f:
    for line in f:
        m = re.search(r"<ab>(.*?)</ab>", line)
        if m:
            abbrs.append(m.group(1))

missing = [a for a in abbrs if a not in EXPANSIONS]
extra = [k for k in EXPANSIONS if k not in abbrs]
print(f"  {len(abbrs)} in list, {len(EXPANSIONS)} expansions defined", flush=True)
print(f"  missing from EXPANSIONS: {len(missing)}", flush=True)
if missing:
    for m in missing[:20]:
        print(f"    {m!r}", flush=True)
print(f"  extra in EXPANSIONS (not in list): {len(extra)}", flush=True)
if extra:
    for e in extra[:20]:
        print(f"    {e!r}", flush=True)

print(f"Writing {OUT}...", flush=True)
with OUT.open("w", encoding="utf-8") as f:
    f.write("; PWG abbreviation expansion table — DRAFT (issue #174)\n")
    f.write("; Format: <abbr>\\t<id>abbr</id> <disp>German - English</disp>[ <INFER/>]\n")
    f.write("; <INFER/> flags uncertain / made-up expansions for human review.\n")
    f.write(";\n")
    inferred = 0
    for abbr in abbrs:
        if abbr not in EXPANSIONS:
            de = "?"
            en = "?"
            infer = True
        else:
            de, en, infer = EXPANSIONS[abbr]
        infer_tag = " <INFER/>" if infer else ""
        if infer:
            inferred += 1
        f.write(f"{abbr}\t<id>{abbr}</id> <disp>{de} - {en}</disp>{infer_tag}\n")
print(f"  wrote {len(abbrs)} lines, {inferred} flagged <INFER/>", flush=True)
print("DONE", flush=True)
