""" change_0f_0g.py
 
"""
import sys,re
import codecs

def read_lines(filein):
 lines = []
 with codecs.open(filein,encoding='utf-8',mode='r') as f:
  for line in f:
   lines.append(line.rstrip('\r\n'))
 print(f'{len(lines)} lines read from {filein}')
 return lines

def write_lines(fileout,outarr):
 with codecs.open(fileout,'w','utf-8') as f:
  for out in outarr:
   f.write("%s\n" % out)
 print(f'{len(outarr)} lines written to {fileout}')


def adjust_lines1(lines):
 replacements = [
  # 06-05-2026. 25%
  ('nach den Lexicogrr.', 'nach den <ab>Lexicogrr.</ab>'),
  ('best. gegen Würmer angewandter Same%} (s.',
   '<ab>best.</ab> gegen Würmer angewandter Same%} (<ab>s.</ab>'),
  ('<ls>VS.</ls> <ab>S.</ab> {#88#} .',
   '<ls>VS. S. {#88#}.</ls>'),
  ('<ls>ebend.</ls> 🞄<ab>S.</ab> 122.',
   '<ls>ebend. S. 122</ls>.'),
  ('vESvadevikam ..#} (<ab>St.</ab>:',
   'vESvadevikam ..#} (<ls>ST.</ls>:'),
  ('<ls>Verz. d. Oxf. H. No. 149.</ls> <ab>S.</ab> <ls n="Verz. d. Oxf. H.">104,a</ls>',
   '<ls>Verz. d. Oxf. H. No. 149. S. 104,a</ls>'),
  ('(transit.)', '(<ab>transit.</ab>)'),
  (' bes. ', ' <ab>bes.</ab> '),
  ('<ls>P.</ls>, <ab>Einl.</ab>', '<ls>P., Einl.</ls>'),
  (' Beiw. ',
   ' <ab>Beiw.</ab> '), #3
  ('1. an. ', '1. <ab>an.</ab>'),
  ('nach dem <ab>Ind.</ab> zu <ls>TRIK.</ls>',
   'nach dem <ls>Ind. zu TRIK.</ls>'),
  ('<ls>SKANDA-P.</ls> <ls>ebend.</ls> 🞄<ls n="Verz. d. Oxf. H.">75,b,18.</ls> <ab>Kap.</ab> 🞄',
   '<ls>SKANDA-P. ebend. 75,b, Kap. 18</ls>. '),
  ('<lex>n.</lex> <ls>Chr.</ls>',
   '<ab>n. Chr.</ab>'), # 16  27%
  ('<ls>ṚV. 5,51</ls> (<ab>ed.</ab> MÜLLER III, <ab>S.</ab> xxx).',
   '<ls>ṚV. 5,51 (ed. MÜLLER III, S. xxx)</ls>.'),
  ('<ab>Th.</ab> II, <ab>S.</ab> 247, <ab>Z.</ab> 2 <ab>v. u.</ab>',
   '<ls>Th. II, S. 247, Z. 2 v. u.</ls>'),
  ('<ls>Verz. d. B. H. No. 1194</ls> (<ab>S.</ab> 337.)',
   '<ls>Verz. d. B. H. No. 1194 (S. 337)</ls>.'),
  (' d: h. ', '<ab>d. h.</ab>'),
  ('(<ls>v. l.). 85,7.</ls>',
   '(<ab>v. l.</ab>). <ls n="ŚĀK.">85,7</ls>.'),
  ('</ls> (<ab>Suppl.</ab>)',
   ' (Suppl.)</ls>'), #11
  ('<ls>HIT.</ls> <ab>ed.</ab> <is>Śrīr</is>. 🞄<ls n="HIT.">79,5</ls>',
   '<ls>HIT. ed. Śrīr. 79,5</ls>'),
  ('<ls>AK.</ls> 🞄<ab>a. a. O.</ab>',
   '<ls>AK. a. a. O.</ls>'),
  ('Terminalia tomentosa <ab>W.</ab> und A.',
   'Terminalia tomentosa W. und A.'),
  ('<ls>NIGH. PR. 5 — 10</ls> wohl <ab>masc.</ab>,11 <ab>u.</ab> 12',
   '<ls>NIGH. PR. 5—10</ls> wohl <ab>masc.</ab>, 11 <ab n=und">u.</ab> 12'),
  ('(and. <ab>Rec.</ab> {#AtfRRAt#})',
   '(<ab n="andere">and.</ab> <ab>Rec.</ab> {#AtfRRAt#})'),
  ('<ab>D.</ab> {%Statt%}, <ab>D.</ab>',
   '<is n="Devadatta">D.</is> {%Statt%}, <is n="Devadatta">D.</is>'),
  ('<ls>NIR. 5,28</ls> <ab>u.</ab> <ab n="dem">d.</ab> <ab>Erll.</ab>',
   '<ls>NIR. 5,28</ls> <ab>u. d.</ab> <ab>Erll.</ab>'),
  ('fat. <ab>pass.</ab>',
   '<ab>fut.</ab> <ab>pass.</ab>'),
  ('{%Piper Chaba <ab>W.</ab> Hunt. (brennend%})',
   '{%Piper Chaba W. Hunt.%} {%(brennend)%}'),
  ('<ls>Verz. d. Oxf. H. No. 150.</ls> <ab>S.</ab> <ls n="Verz. d. Oxf. H.">104,a.</ls>',
   '<ls>Verz. d. Oxf. H. N. 150. S. 104,a</ls>.'),
  ('<ls>MBH. 12,12864</ls> (Bd. III, <ab>S.</ab> 818, <ab>Z.</ab> 6 <ab>v. u.</ab>) 🞄',
   '<ls>MBH. 12,12864 (Bd. III, S. 818, Z. 6 v. u.)</ls>'),  # 28%
  ('{%drei Gerstenkörner enthaltend, das Gewicht von drei G. habend%}',
   '{%drei Gerstenkörner enthaltend, das Gewicht von drei <ab n="Gerstenkörner">G.</ab> habend%}'),
  ('<ls n="MBH. 12,">12864</ls> (<ab>S.</ab> 818, <ab>Z.</ab> 5 <ab>v. u.</ab>)',
   '<ls n="MBH. 12,">12864 (S. 818, Z. 5 v. u.)</ls>'),
  ('{%ein Mittel gegen H.%}',
   '{%ein Mittel gegen <ab n="Hautausschläge">H.</ab>%}'),
  ('{%Haut%} so v. als {%Schlauch%}',
   '{%Haut%} so <ab>v.</ab> als {%Schlauch%}'),
  ('<ls>R. GORR.</ls> <ab>Uebers.</ab> IX,346, <ab>N.</ab> 40.',
   '<ls>R. GORR. Uebers. IX, 346, N. 40</ls>.'),
  ('v. a. die richterliche',
   '<ab>v. a.</ab> die richterliche'),
  ('<ls>MIT. 258,3 v. u.</ls> <ab>fgg.</ab>',
   '<ls>MIT. 258,3 v. u. fgg.</ls>'),  # 28%
  ('<ls>VP. 63.</ls> <ab>D.</ab>',
   '<ls>VP. 63</ls>. <is n="Dadhīci">D.</is>'),
  ('Der Mythus von <ab>D.</ab>',
   'Der Mythus von <is n="Dadhīci">D.</is>'),
  ('den Mythus der <is>Aśvin</is>: <ab>D.</ab>',
   'den Mythus der <is>Aśvin</is>: <is n="Dadhikrā">D.</is>'),
  ('c) <ab>D.</ab> als Opferer und',
   '— c) <is n="Dadhyañc">D.</is>'),
  ('Die von <ab>D.</ab> verkündigte',
   'Die von <is n="Dadhyañc">D.</is> verkündigte'), # 29%
  ('({%der Fürst der%} <ab>D.</ab>)',
   '({%der Fürst der%} <is n="Darada">D.</is>)'),
  ('Schrift der <ab>D.</ab>',
   'Schrift der <is n="Darada">D.</is>'),
  ('{%der Fürst der%} <ab>D.</ab>',
   '{%der Fürst der%} <is n="Darada">D.</is>'),
  ('{%an heil. Bad.%}',
   '{%an <ab n="heilige Badeplätze">heil. Bad.</ab>%}'),
  (' v. a. ', ' <ab>v. a.</ab> '), # 20
  ('das Zusammentreffen mit%} <ab>S.</ab>',
   'das Zusammentreffen mit%} <is n="Saṃpāti">S.</is>'),
  ('<ls>HARIV. 10116</ls> (<ab>S.</ab> 790).',
   '<ls>HARIV. 10116 (S. 790)</ls>.'),
  ('<ls>KÖPPEN</ls>, Die <ab>Rel.</ab> <ab>d.</ab> Buddha 438. <ab>fg.</ab>',
   '<ls>KÖPPEN, Die Rel. d. Buddha 438. fg.</ls>'),
  (' in den <is>Un</is>terschrr. der <is>Adhyāya</is>.',
   ' in den <ab>Unterschrr.</ab> der <is>Adhyāya</is>.'),
  ('<ls>HARIV. 11006</ls> (<ab>p.</ab> 790).',
   '<ls>HARIV. 11006 (p. 790)</ls>.'),
  ('{%das von den%} <ab>D.</ab> {%bewohnte Gebiet%}',
   '{%das von den%} <is n="Dākṣāyaṇa">D.</is> {%bewohnte Gebiet%}'),
  ('{%der Sohn der%} <ab>D.</ab>, <is>Pāṇini</is>',
   '{%der Sohn der%} <is n="Dākṣī">D.</is>, <is>Pāṇini</is>'),
  ('{%ein Fürst der%} <ab>D.</ab> <ls>ebend.</ls>',
   '{%ein Fürst der%} <is n="Daṇḍaka">D.</is> <ls>ebend.</ls>'),
  ('(<ls>SV. v. l.).</ls>', '(<ls>SV. v. l.</ls>).'),
  ('(<ls>SV.</ls> <ab>v. l.</ab>).',
    '(<ls>SV. v. l.</ls>)'),
  (' NO. ', '<ab n="Nord-Ost">NO.</ab>'), #4  30%
  # Begin 06-06-2026
  ('<ab>u.</ab> a.',
   '<ab n="und anderen">u. a.</ab>'), # 11
  ('511,2 <ab>v. u.</ab>',
   '<ls n="">511,2 v. u.</ls>'),
  ('<lex>adj.</lex> 🞄[Page3-0614] 🞄<ab>comp.</ab>',
    '<ab>adj. comp.</ab> 🞄[Page3-0614] 🞄'),
  ('({#Elavila#}). <ab>fgg.</ab>', '({#Elavila#}). fgg.'),
  ('<ab>D.</ab> mit der <ab>Bez.</ab>',
   '<is n="Divodāsa">D.</is> mit der <ab>Bez.</ab>'),
  ('</ls> (<ab>p.</ab> 791).',
   ' (p. 791)</ls>.'), #4
  ('SO. SW. NW. NO.',
   '<ab n="Süd-Ost">SO.</ab> <ab n="Süd-West">SW.</ab> <ab n="Nord-West">NW.</ab> <ab n="Nord-Ost">NO.</ab>'),
  ('<is>Stenzler</is>, De lexicogr. <ab>s.</ab> principiis,22.',
   '<ls>Stenzler, De lexicogr. s. principiis, 22</ls>.'),
  ('<ab>u.</ab> <ab n="dem">d.</ab> <ab>intens.</ab>',
   '<ab>u. d.</ab> <ab>intens.</ab>'),
  ('<ls>MIKLOSICH</ls> (Die Wurzeln des Altsl. <ab>p.</ab> 21)',
   '<ls>MIKLOSICH (Die Wurzeln des Altsl. p. 21)</ls>'),
  ('{%die Nachkommen des%} <ab>D.</ab>',
   '{%die Nachkommen des%} <is n="Dīrghatamas">D.</is>'),
  (' 🞄<ab>Schol.</ab> zu <ls>KĀTY. ŚR. 4,9,21</ls>, Note, <ab>Z.</ab> 5.',
   ' <ab>Schol.</ab> zu <ls>KĀTY. ŚR. 4,9,21, Note, Z. 5</ls>.'),
  ('{#agnO prAstaM praDUyeta taTA#} (<ab n="lies">l.</ab>',
   '{#agnO prAstaM praDUyeta taTA#} (<ab n="lectio">l.</ab>'),
  ('{#duHKaM laBet#} <ab>Einschieb.</ab>',
   '{#duHKaM laBet#} Einschieb.'),
  ('{%die Tochter des M.%}',
   '{%die Tochter des <ab n="Milchmeer">M.</ab>%}'),
  ('fehlerhafte 🞄<ls>Var.</ls>',
   'fehlerhafte <ab>Var.</ab> 🞄'), # 31%
  ('{%Feind des%} <ab>D.</ab>',
   '{%Feind des%} <is n="Dūṣaṇa">D.</is>'),
  ('gerichtet ist (sind) <ab>auf.</ab>',
   'gerichtet ist (sind) auf.'),
  ('<ls>ŚKDR.</ls> <ab>Suppl.</ab>',
   '<ls>ŚKDR. Suppl.</ls>'), # 30
  ("<ls>RAVERTY</ls>, Dict. of Puk'hto, <ab>p.</ab> 343.", 
   "<ls>RAVERTY, Dict. of Pukʼhto, p. 343</ls>."),
  ('führende <ab>Weg.</ab>%}', 'führende Weg%}.'),
  ('{%Ruf zu den Göttern, Anrufung der G.%}',
   '{%Ruf zu den Göttern, Anrufung der <ab n="Göttern">G.</ab>%}'),
  ('{%was die Götter aufbringt, Beleidigung der G.%}',
   '{%was die Götter aufbringt, Beleidigung der <ab n="Götter">G.</ab>%}'),
  ('{%ein Tempel der G.%}', '{%ein Tempel der <ab n="Göttin">G.</ab>%}'),
  ('{%ein Wörterbuch der L.%}',
   '{%ein Wörterbuch der <ab n="Landessprache">L.</ab>%}'),
  ('<ab>D.</ab> {%zu Ehrende%}',
   '<is n="Daitya">D.</is> {%zu Ehrende%}'),
  ('{%das Vertrautsein mit der Astr.%}',
   '{%das Vertrautsein mit der <ab n="Astrolog">Astr.</ab>%}'),
  ('{%bew.%}', '<ab n="bewohnt">bew.</ab>'),
  ('<lang>ved.</lang> Śit.',
   '<lang>ved.</lang> <ab>Cit.</ab>'),
  ('<ab>patron.</ab> v.',
   '<ab>patron.</ab> <ab n="von">v.</ab>'),
  ('(<is>Pāṇḍu</is>) 🞄82 und <ab>N.</ab> 1.',
    '(<is>Pāṇḍu</is>) <ls n="VP.">82 und N. 1</ls>.'),
  ('(sg).', '(<ab>sg.</ab>).'), # 32%
  (' s. u. ', ' <ab>s. u.</ab> '),
  ('Feuchtigkeit beim Eleph.',
   'Feuchtigkeit beim <ab n="Elephant">Eleph.</ab>'),
  ('<ab>vgl.</ab> <ab>S.</ab> 514. <ab>fg.</ab>',
   '<ab>vgl.</ab> <ab n=Seite">S.</ab> 514. <ab>fg.</ab>'),
  ('<ls>Verz. d. Oxf. H. No. 447 — 450.</ls> <ab>p.</ab> <ls n="Verz. d. Oxf. H.">113,a.</ls> <ls n="Verz. d. Oxf. H.">183,b.</ls>',
   '<ls>Verz. d. Oxf. H. No. 447—450. p. 113,a. 183,b</ls>.'),
  ('{%der Inselbewohner%}, Bein.',
   '{%der Inselbewohner%}, <ab>Bein.</ab>'),
  ('Stieresu. <ab>s.</ab> <ab>w.</ab>',
   'Stieres <ab>u. s. w.</ab>'),
  ('{%<ab>D.</ab> fastuosa%}',
   '{%D. fastuosa%}'),
  ('{%Sanseviera zeylanica Roxb. (<ab>S.</ab> Roxburghiana Schult.%})',
   '{%Sanseviera zeylanica Roxb.%} ({%S. Roxburghiana Schult.%})'),
  ('<ls>ebend.</ls> <ab>p.</ab> 150.',
   '<ls>ebend. p. 150</ls>.'),
  ('<ab>Ausg.</ab> v. ',
   '<ab>Ausg.</ab> <ab n="von">v.</ab> '), # 33%
  ('<ls>HARIV. 9929.</ls> <ls n="HARIV.">11005. fg.</ls> <ab>p.</ab> 790.',
   '<ls>HARIV. 9929. 11005. fg. p. 790</ls>.'),
  (' med.', ' <ab>med.</ab>'), # 2
  ('<ls>ŚĀK.</ls> <ab>Einschieb.</ab> nach',
   '<ls>ŚĀK.</ls> Einschieb. nach'),
  ('{%auf den%} <ab>S.</ab> {%gesetzt%}',
   '{%auf den%} <ab n="Süd">S.</ab> {%gesetzt%}'),
  ('<ab>Schol.</ab> zu <ls>KAP. 1,16. Einl.</ls>',
   '<ab>Schol.</ab> zu <ls>KAP. 1,16</ls>. <ab>Einl.</ab>'),
  ('<ls>ebend.</ls> <ab>N.</ab> 11. ',
   '<ls>ebend. N. 11</ls>.'),
  ('(oxyt).', ' (<ab>oxyt.</ab>)'),
  ('und <ls>ebend.</ls> <ab>N.</ab> 1.',
   'und <ls>ebend. N. 1</ls>.'),
  ('(<ab>s.</ab> <ab>w.</ab> <ab>u.</ab>)',
   '(<ab>u. s. w.</ab>)'),
  ('<ls>ebend.</ls> <ab>S.</ab> 96.',
   '<ls>ebend. S. 96</ls>.'),
  ('<ls>HARIV. 11076</ls> (<ab>p.</ab> 792).',
   '<ls>HARIV. 11076 (p. 792)</ls>.'),
  ('(uneig.)', '(<ab>uneig.</ab>)'),
  ('ls>BENFEY</ls> zud. <ab>St.</ab> In der Stelle',
   '<ls>BENFEY</ls> zu <ab>d. St.</ab> In der Stelle'), # 34%
  ('{%Salmalia malabarica Schott <ab>u.</ab> Endl.%}',
   '{%Salmalia malabarica Schott u. Endl.%}'),
  ('</ls> (<ab>S.</ab> 791).',
   '<ls>HARIV. 11042 (S. 791)</ls>.'),
  ('<ab>vgl.</ab> v. 7', '<ab>vgl.</ab> <ab n="vers">v.</ab> 7)'),
  ('<ab>N.</ab> 🞄[Page4-0040] 🞄pr.',
   '<ab>N. pr.</ab> 🞄[Page4-0040] 🞄'),
  ('{%die Leuchte am%} H., {%der Mond%}',
   '{%die Leuchte am%} <ab n="Himmelsgewölbe">H.</ab>, {%der Mond%}'),
  (' <ls>LOIS.</ls> in der Vorrede zu <ls>AK.</ls> 🞄<ab>S.</ab> IX.',
   ' <ls>LOIS.</ls> in der Vorrede zu AK. S. IX.</ls>'),
  ('(<ab>vgl.</ab> <ab>S.</ab> 25)',
   '(<ab>vgl.</ab> <ab n=Seite">S.</ab> 25)'),
  ('<ab>Erll.</ab> zum 🞄<ls>NIR. S. 123.</ls>',
   '<ls>Erll. zum NIR. S. 123</ls>.'),
  ('{%ein Blatt von <ab>N.</ab> sp.%}',
   '{%ein Blatt von N. sp.%}'),
  ('{%ein Blumenblatt von <ab>N.</ab> sp.%}',
   '{%ein Blumenblatt von N.sp.%}'),
  ('{%der neunte%} (<ab>das.</ab>',
   '{%der neunte%} (das'), # 35%
  ('</ls> (<ab>S.</ab> 570).', ' (S. 570)</ls>.'), # 7
  ('(infin.)', '(<ab>infin.</ab>)'),
  ('{%<ab>W.</ab> Hunt.%}', '{%W. Hunt.%}'),
  ('<ls>BALLANTYNE</ls> an Bed 1. an.',
   '<ls>BALLANTYNE</ls> an Bed 1. <ab>an.</ab>'),
  ('<ab>vgl.</ab> <ab>N.</ab> 70. <ab>N. pr.</ab>',
   '<ab>vgl.</ab> <ls n="VP. 479, ">N. 70</ls>. <ab>N. pr.</ab>'),
  ('{%die besten Arten des Costus, den besten C.%}',
   '{%die besten Arten des Costus, den besten <ab n="Costus">C.</ab>%}'),
  ('<ls>MBH. 12,12864</ls> (<ab>S.</ab> 818, <ab>Z.</ab> 8 <ab>v. u.</ab>).',
   '<ls>MBH. 12,12864 (S. 818, Z. 8 v. u.)</ls>.'),
  (' 8 I <ab>st.</ab> 8 T',
   ' 8 <ab n="Iamb">I</ab> <ab>st.</ab> 8 <ab n="Trochee">T</ab>'),
  (' patron. ', ' <ab>patron.</ab> '),
  (' personif. ', ' <ab>personif.</ab> '),
  (' SW. ', ' <ab n="Süd-West">SW.</ab> '),
  ('<ls>MATSYA-P.</ls> in <ls>VP. 384, N.</ls>',
   '<ls>MATSYA-P.</ls>_in_<ls>VP. 384</ls>, <ab>N.</ab>'),
  ('<ls>WEBER</ls>, Zwei vedische Texte über Omina und Portenta, 🞄<ab>S.</ab> 321. <ab>fg.</ab>',
   '<ls>WEBER, Zwei vedische Texte über Omina und Portenta, S. 321. fg.</ls>'),
  ('<ls>ŚRUT. 12, v. l. 17.</ls>',
   '<ls>ŚRUT. 12</ls>, <ab>v. l.</ab> <ls n="">17</ls>.'),
  ('</ls> (<ab>S.</ab> 790)', ' (S. 790)</ls>'), #10
  ('<is>Yūpau</is>. <ab>s.</ab> <ab>w.</ab>)',
   '<is>Yūpa</is> <ab>u. s. w.</ab>)'),  # 36%
  ('<ls>MIT. 47,2 v. u.</ls> <ab>fgg.</ab>',
   '<ls>MIT. 47,2 v. u. fgg.</ls>'),
  ('</ls> (<ab>S.</ab> 792)',
   ' (S. 792)</ls>'), #9
  ('<ls>MÜLLER</ls> in der deutschen <ab>Ausg.</ab> des 🞄<ls>ṚV.</ls> <ab>S.</ab> VI',
   '<ls>MÜLLER in der deutschen Ausg. des ṚV. S. VI</ls>'),
  ('<ab>Ind.</ab> zu <ls>UṆĀDIS.</ls>',
   '<ls>Ind. zu UṆĀDIS.</ls>'),
  ('Göttinger gelehrten Anzeigen 1859, <ab>St.</ab> 172, <ab>S.</ab> 1712.',
   '<ls>Göttinger gelehrten Anzeigen 1859, St. 172, S. 1712</ls>.'),
  ('Schol.zu <ls>ŚĀK. 31,7.</ls>',
   '<ab>Schol.</ab> zu <ls>ŚĀK. 31,7</ls>.'),
  ('{%R. hervorbringend%}',
   '<ab n="Regungslosigkeit">R.</ab> {%hervorbringend%}'),
  ('<ls>M. 5,84</ls> (<ab>S.</ab> 463, <ab>Z.</ab> 9).',
   '<ls>M. 5,84 (S. 463, Z. 9)</ls>.'),
  ('{%keine Fl. essend%}',
   '{%keine <ab n="Fleischspeisen">Fl.</ab> essend%}'),
  ('<ls>M. 1,1</ls> (<ab>S.</ab> 5, <ab>Z.</ab> 4).',
   '<ls>M. 1,1 (S. 5, Z. 4)</ls>.'),
  ('herausgegeben in der Bibl. <ab>Ind.</ab>',
   'herausgegeben in der <ls>Bibl. Ind.</ls>'),
  ('für die M. passend, aus M. bestehend, von M. begleitet',
   'für die <ab n="Männern">M.</ab> passend, aus <ab n="Männern">M.</ab> bestehend, von <ab n="Männern">M.</ab> begleitet'),
  ('<ls>HALĀY. 2,217.</ls> <ab>Einschieb.</ab> nach',
   '<ls>HALĀY. 2,217</ls>. Einschieb. nach'),
  ('Calc. <lang>lith.</lang> <ab>Ausg.</ab> von 🞄1830 (GILD. 205).',
   '<ls>Calc. lith. Ausg. von 1830 (GILD. 205)</ls>.'),
  (' NW. ', ' <ab n="Nord-West">NW.</ab> '),
  ('<ls>Einl. zum ṚV.</ls> <ab>S.</ab> 7.',
   '<ls>Einl. zum ṚV. S. 7</ls>.'),
  ('{%den Tod bringend den%} <ab>D.</ab>',
   '{%den Tod bringend den%} <is n="Daitya">D.</is>'),
  ('<ab>Schol.</ab> <ab>S.</ab> <ls>31,11. 41,22.</ls>',
   '<ab>Schol.</ab> <ls>S. 31,11. 41,22</ls>.'),
  ('{%im <ab>N.</ab>-Walde sich aufhaltend%}',
   '{%im <is n="Naimiṣāyana">N.</is>-Walde sich aufhaltend%}'),
  ('(<ab>s. u.</ab> <ab>d.</ab>) <ab>W.</ab>',
   '(<ab>s. u.</ab> <ab>d. W.</ab>)'),
  ('<ls>WILS.</ls> (2te <ab>Aufl.</ab>)',
   '<ls>WILS. (2te Aufl.)</ls>'),
  ('<ls>WILS.</ls> (1ste <ab>Aufl.</ab>)',
   '<ls>WILS. (1ste Aufl.)</ls>'),
  ('wie die 1ste <ab>Aufl.</ab> hat.',
   'wie die 1ste Aufl. hat.'),
  ('Scholien der Calc. und Bonner Ausg.',
   'den Scholien der <ls>Calc.</ls> und Bonner <ab>Ausg.</ab>'),
  ('(<ab>s.</ab> <ls>AUFRECHT</ls> in der Vorrede <ab>S.</ab> XVI)',
   '(<ab>s.</ab> <ls>AUFRECHT in der Vorrede S. XVI</ls>)'),
  (' Gegens. ', ' <ab>Gegens.</ab> '),#3
  ('(trans.)', '(<ab>trans.</ab>)'),
  ('in fünf <ab>Sch.</ab> zubereitet',
   'in fünf <ab n="Schalen">Sch.</ab> zubereitet'),
  ('<ls>Verz. d. Oxf. H. 71,a</ls>, <ls>Kap. 59</ls>; <ab>vgl.</ab> <ab>N.</ab> 1.',
   '<ls>Verz. d. Oxf. H. 71,a, Kap. 59</ls>; <ab>vgl.</ab> <ls n="Verz. d. Oxf. H. 71,a">N. 1</ls>.'),
  ('<ab>S.</ab> 40. Fälschlich',
   '<ab n=Seite">S.</ab> 40. Fälschlich'),  # 38%
  ('<ls>MBH. 12,12864</ls> (<ab>S.</ab> 818, <ab>Z.</ab> 9 <ab>v. u.</ab>).',
   '<ls>MBH. 12,12864 (S. 818, Z. 9 v. u.)</ls>'),
  ('<ab>Aut.</ab> in der 1ten <ab>Aufl.</ab>',
   '<ab>Aut.</ab> in der 1ten Aufl.'),
  ('<ls>M. 3,45</ls> (<ab>S.</ab> 193,1. <ab>fg.</ab>).',
   '<ls>M. 3,45 (S. 193,1. fg.)</ls>.'),
  ('<ls>GOLD.</ls> <ab>Wörterb.</ab>',
   '<ls>GOLD. Wörterb.</ls>'),
  (' von <ab>W.</ab> begleitet%}',
   ' von <ab n="Weibe">W.</ab> begleitet%}'),
  ('Am Auf. eines',
   'Am <ab>Auf.</ab> eines'), #2
  ('in 🞄<ab>S.</ab> 292 abgebildet',
   'in <ab n=Seite">S.</ab> 292 abgebildet'),
  (' Vgs. ',
   ' <ab>Vgl.</ab> '),
  ('<ls>MBH. 12,12864</ls> (<ab>S.</ab> 518, <ab>Z.</ab> 7 <ab>v. u.</ab>).',
   '<ls>MBH. 12,12864 (S. 518, Z. 7 v. u.)</ls>.'),
  ('im Index <ab>S.</ab> 11.',
   'im <ls n="SĀH. D.">Index S. 11</ls>.'),
  ('P. {%<ab>u.</ab>%} <ab>N.</ab>',
   '<is n="Paphaka">P.</is> <ab n="und">u.</ab> <is n="Naraka">N.</is>'),
  ('</ls> (<ab>S.</ab> 792.)',
   ' (S. 792)</ls>.'),  # 39%
  ('{%Einer den Andern <ab>u.</ab>%} 🞄[Page4-0496] 🞄{%s. w.%}',
   '{%Einer den Andern <ab>u. s. w.</ab>%} 🞄[Page4-0496] 🞄'),
  ('jenes <ab>S.</ab> {%spontaneum%}',
   'jenes {%S. {%spontaneum%}'),
  ('<ls>PRAB. 87 15</ls> (<ab>s. v.</ab> l.)',
   '<ls>PRAB. 87. 15</ls> (<ab>s.</ab> <ab>v. l.</ab>)'),
  ('<ls>ŚUK. ebend. 39,3. Inschr.</ls>',
   '<ls>ŚUK.</ls> <ls>ebend. 39,3</ls>. <ab>Inschr.</ab>'),
  ('die <ab>gedr.</ab> Ausgabe (<ab>p.</ab> 27)',
   'die <ls>gedr. Ausgabe (p. 27)</ls>'),
  ('<ls>MBH. 10,724</ls> (<ab>Etym.</ab> des Namens). <ab>fgg.</ab>',
   '<ls>MBH. 10,724 (<ab>Etym.</ab> des Namens). fgg.</ls>'),
  ('des <is>Adhy</is>. {#puruza˚#}',
   'des <is n="Adhyāya">Adhy.</is> {#puruza˚#}'),
  ('<ls>AUFR.</ls> im <ls>Ind.</ls> zu ',
   '<ls>AUFR.</ls> im <ab>Ind.</ab> zu '),
  ('</ls> (<ab>S.</ab> 605).',
   ' (S. 605)</ls>.'),
  ('{%im Gefolge des <ab>S.</ab> seiend%}',
   '{%im Gefolge des <is n="Sugrīva">S.</is> seiend%}'),
  ('<ls>KULL.</ls> (<ab>S.</ab> 358, <ab>Z.</ab> 6).',
   '<ls>KULL. (S. 358, Z. 6)</ls>.'),
  ('</ls> (<ab>S.</ab> 134).',
   ' (S. 134)</ls>.'),
  ('die <ab>gedr.</ab> <ab>Ausg.</ab> j. 121',
   'die <ls>gedr. Ausg. y. 121</ls>'),
  ('<ls>KULL.</ls> <ls>ebend.</ls> <ab>S.</ab> 193, <ab>Z.</ab> 12',
   '<ls>KULL. ebend. S. 193, Z. 12</ls>'),
  ('<ab>ed.</ab> 🞄<ls>ST.</ls>',
   '<ls>ed. ST.</ls>'),
  ('<ls n="VS.">36,10.</ls> <ab>S.</ab> <ls>59,15.</ls>',
   ''),  # 40%
  ('<ab>d.</ab> <ab>vorang.</ab>',
   '<ab>d. vorang.</ab>'),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  
  ]
 newlines = []
 nchg = 0
 for iline,line in enumerate(lines):
  newline = line
  for old,new in replacements:
   newline = newline.replace(old,new)
  if newline != line:
   nchg = nchg + 1
  newlines.append(newline)
 print(f'{nchg} line(s) changed')
 return newlines

if __name__=="__main__":
 filein = sys.argv[1]  # base
 fileout = sys.argv[2] # adjusted base
 
 lines = read_lines(filein)

 lines1 = adjust_lines1(lines)
 #lines2 = adjust_lines2(lines1)
 write_lines(fileout,lines1)
