""" change_0h_0i.py
 
"""
import sys,re
import codecs

def read_lines(filein):
 lines = []
 with codecs.open(filein,encoding='utf-8',mode='r') as f:
  for line in f:
   lines.append(line.rstrip('\r\n'))
 print(f'{len(lines)} lines read from {filein}')
 return lines

def write_lines(fileout,outarr):
 with codecs.open(fileout,'w','utf-8') as f:
  for out in outarr:
   f.write("%s\n" % out)
 print(f'{len(outarr)} lines written to {fileout}')


def adjust_lines1(lines):
 replacements = [
  # 06-08-2026.
  # 59%
  ('🞄<ls>AUFRECHT</ls>\'S <ab>Ausg.</ab> des <ls>HALĀY. 2,303</ls>',
   '<ls>AUFRECHTʼs Ausg. des HALĀY. 2,303</ls> liest {#uccUla#}.'),
  ('🞄<ls>R. 7,32,46.</ls> <ab>Z.</ab> 6.',
   '<ls>R. 7,32,46. Z. 6</ls>.'),
  ('<ab>ed.</ab> 🞄<ls>TROYER.</ls>',
   '<ls>ed. TROYER.</ls>'),
  ('Gött. gel. Anz. 1860, <ab>S.</ab> 737.',
   '<ls>Gött. gel. Anz. 1860, S. 737</ls>.'),
  ('</ls> 🞄[Page5-1165] 🞄<ab>fg.</ab>',
   ' fg.</ls> 🞄[Page5-1165] 🞄'),
  ('{%zum Wasser, bis <ab>z.</ab> <ab>W.</ab>%}',
   '{%zum Wasser, bis <ab n="zum Wasser">z. W.</ab>%}'),
  ('<ab>ed.</ab> 🞄<ls>BALLANT. 189,5.</ls>',
   '<ls>ed. BALLANT. 189,5</ls>.'),
  ('Thl. 3, <ab>S.</ab> 400',
   '<ls>Thl. 3, S. 400</ls>'),
  ('<span>N. 1. 357,a,6</span> <ab>v. u.</ab>',
   '<ls>N. 1. 357,a,6 v. u.</ls>'),
  ('<ab>ed.</ab> 🞄<ls>BURN.</ls>',
   '<ls>ed. BURN.</ls>'), #4
  ('<ab>ed.</ab> Allah.',
   '<ls n="KAP.">ed. Allah.</ls>'),
  ('🞄<ls n="Verz. d. Oxf. H.">321,a, No. 701, Z. 2</ls>',
   '<ls n="Verz. d. Oxf. H.">321,a, No. 701</ls>. <ab>Z.</ab> 2'),
  ('<ls>Sp. 967, Z. 7 lies ad 78 st. 78.</ls>',
   '<ab>Sp.</ab> 967, <ab>Z.</ab> 7 lies ad 78 <ab>st.</ab> 78.'),
  ('<ls>STENZLER</ls> in Breslauer Programm 1860, <ab>S.</ab> 13.',
   '<ls>STENZLER</ls> in <ls>Breslauer Programm 1860, S. 13</ls>.'),
  ('<ab>ed.</ab> 🞄<ls>JOHNS.</ls>',
   '<ls>ed. JOHNS.</ls>'),
  ('<ab>ed.</ab> 🞄<ls>WILS.</ls>',
   '<ls>ed. WILS.</ls>'),
  ('<ls>KAP. 1,65</ls> (<ab>S.</ab> 53, <ab>Z.</ab> 3).',
   '<ls>KAP. 1,65 (S. 53, Z. 3)</ls>.'),
  ('<ls>STENZLER</ls> im Breslauer Programm 1860, <ab>S.</ab> 13.',
   '<ls>STENZLER</ls> in <ls>Breslauer Programm 1860, S. 13</ls>.'),
  ('<ls>Verz. d. Oxf. H. 91,a,29</ls> und <ab>N.</ab> 3.',
   '<ls>Verz. d. Oxf. H. 91,a,29 und N. 3.</ls>'),
  ('ls>Sp. 1047, Z. 1 lies 6,114,1. 2.</ls>',
   '<ab>Sp.</ab> 1047, <ab>Z.</ab> 1 lies 6,114,1. 2.'),
  ('🞄(<ls>PAÑCAV. BR. 15,3,16) N.</ls>',
   '(<ls>PAÑCAV. BR. 15,3,16</ls>) <ab>N.</ab>'),
  ('(<ls>PAÑCAV. BR. 13,5,17) desgl. 239,b.</ls>',
   '(<ls>PAÑCAV. BR. 13,5,17</ls>) <ab>desgl.</ab> <ls n="PAÑCAV. BR.">239,b</ls>.'),
  ('der neueren Ausg, in', 'der neueren <ab>Ausg.</ab> in'),
  ('<ls>Sp. 1070, Z. 2 lies 10,4,2,15 st. 10,4,3,18</ls>; <ab>Z.</ab> 4.',
   '<ab>Sp.</ab> 1070, <ab>Z.</ab> 2 lies 10,4,2,15 <ab>st.</ab> 10,4,3,18; <ab>Z.</ab> 4.'),
  ('🞄<ls>Sp. 1116, Z. 1 lies 4,2,54 st. 4,2,154.</ls>',
   '<ab>Sp.</ab> 1116, <ab>Z.</ab> 1 lies 4,2,54 <ab>st.</ab> 4,2,154.'),
  ('<ls>Spr. 1406.</ls> Sp. 1, <ab>Z.</ab> 2',
   '<ls>Spr. 1406.</ls> <ab>Sp.</ab> 1, <ab>Z.</ab> 2'),
  ('🞄(Sp. 42, <ab>Z.</ab> 8 <ab>v. u.</ab>) streiche 104, 2.',
   '(<ab>Sp.</ab> 42, <ab>Z.</ab> 8 <ab>v. u.</ab>) streiche 104, 2.'),
  # 60%
  ('<ls>ĀŚV. GṚHY. 4,5,10 (steht u. 2.).</ls>',
   '<ls>ĀŚV. GṚHY. 4,5,10</ls> (steht <ab>u.</ab> 2.).'),
  ('(<ab>vgl.</ab> <ab>S.</ab> 312)',
   '(<ab>vgl.</ab> <ab n="Seite">S.</ab> 312)'),
  ('<ls>Sp. 207, Z. 3 fgg.</ls>',
   '<ab>Sp.</ab> 207, <ab>Z.</ab> 3 <ab>fgg.</ab>'),
  (' 🞄<ls>Sp. 294, Z. 10 lies 3,28,11.</ls>',
   '<ab>Sp.</ab> 294, <ab>Z.</ab> 10 lies 3,28,11.'),
  ('Die Bomb. <ab>Ausgg.</ab>',
   'Die <ls>Bomb. Ausgg.</ls>'),
  ('🞄<ls>NIR.</ls> <ab>Erläutt.</ab> <ab>S.</ab> 12, <ab>Anm.</ab> 4.',
   '<ls>NIR. Erläutt. S. 12, Anm. 4</ls>.'),
  ('{%a%}, <ab>N.</ab> 2.',
   '<ls n="Verz. d. Oxf. H. 217,">a, N. 2</ls>.'),
  ('<ls>Sp. 425, Z. 9 lies 387</ls>',
   '<ab>Sp.</ab> 425, <ab>Z.</ab> 9 lies 387'),
  ('<ls>ebend.</ls> 🞄<ls n="Verz. d. Oxf. H.">66,b,37</ls> und <ab>N.</ab> 5.',
   '<ls>ebend. 66,b,37 und N. 5</ls>.'),
  ('mit der H. geschmückt',
   'mit der <ab n="Hochzeitsschnur">H.</ab>'),
  ('<ls>VARĀH. BṚH. S. 89,1</ls> (<ab>S.</ab> 445,1 <ab>v. u.</ab>).',
   '<ls>VARĀH. BṚH. S. 89,1 (S. 445,1 v. u.)</ls>'),
  ('<ls>Sp. 492, Z. 9. fgg.</ls>',
   '<ab>Sp.</ab> 492, <ab>Z.</ab> 9. <ab>fgg.</ab>'),
  # 61%
  ('🞄<ls>AV. PRĀT.</ls> <ab>S.</ab> 261. <ab>fg.</ab> (II,3. 18).',
   '<ls>AV. PRĀT. S. 261. fg. (II, 3. 18)</ls>.'),
  ('Bomb. <ab>Ausgg.</ab>',
   'ls>Bomb. Ausgg.</ls>'),  #57
  ('<ls>Sp. 523, Z. 19 lies 104,19 st. 104,9.</ls>',
   '<ab>Sp.</ab> 523, <ab>Z.</ab> 19 lies 104,19 <ab>st.</ab> 104,9.'),
  ('<ls>VARĀH. BṚH. S. 104,61</ls> (<ab>S.</ab> 499, <ab>Z.</ab> 3 <ab>v. u.</ab>).',
   '<ls>VARĀH. BṚH. S. 104,61 (S. 499, Z. 3 v. u.)</ls>.'),
  ('🞄<ls>Verz. d. Oxf. H. 308,b,3</ls> und 1 <ab>v. u.</ab>',
   '<ls>Verz. d. Oxf. H. 308,b,3 und 1 v. u.</ls>'),
  ('<ls>Sp. 577,13</ls>',
   '<ab>Sp.</ab> 577,13'),
  ('🞄<ls>Sp. 584, Z. 1.</ls>',
   '<ab>Sp.</ab> 584, <ab>Z.</ab> 1.'),
  ('<ab>urpsr.</ab>', '<ab>urspr.</ab>'),
  ('🞄Sp. 600, <ab>Z.</ab> 1',
   '<ab>Sp.</ab> 600, <ab>Z.</ab> 1 '),
  ('<ls>ṚV. 8,91</ls> (<ab>S.</ab> 828, <ab>Z.</ab> 8)',
   '<ls>ṚV. 8,91 (S. 828, Z. 8)</ls>'),
  ('🞄<ls>Sp. 607</ls>, <ab>Z.</ab>',
   '<ab>Sp.</ab> 607, <ab>Z.</ab>'),
  ('🞄<ls>Sp. 622</ls>',
   '<ab>Sp.</ab> 622'),
  ('🞄<ls>Sp. 622</ls>', '<ab>Sp.</ab> 622'),
  ('🞄<ls>Sp. 3673</ls>', '<ab>Sp.</ab> 3673'),
  ('🞄<ls>Sp. 1107</ls>', '<ab>Sp.</ab> 1107'),
  ('🞄<ls>Sp. 976</ls>', '<ab>Sp.</ab> 976'),
  ('<ls>HALL</ls> <ls>ebend.</ls> <ab>S.</ab> 19.',
   '<ls>HALL ebend. S. 19</ls>.'),
  ('<ls>AV. PRĀT.</ls> 🞄<ab>S.</ab> 261. <ab>fg.</ab> (II,3. 10. 13. 15. 16. 18).',
   '<ls>AV. PRĀT. S. 261. fg. (II, 3. 10. 13. 15. 16. 18)</ls>.'),
  #('<ls n="MBH.">14,474</ls> (<ab>S.</ab> 291).',
  # ''),
  # BEGIN changes from make_change_04.txt
  ('</ls> (<ab>S.</ab> 291)',
   ' (S. 291)</ls>'),
  ('</ls> (<ab>S.</ab> 223)',
   ' (S. 223)</ls>'),
  ('</ls> (<ab>S.</ab> 403)',
   ' (S. 403)</ls>'),
  ('</ls> (<ab>S.</ab> 791)',
   ' (S. 791)</ls>'),
  ('</ls> (<ab>S.</ab> 9)',
   ' (S. 9)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 9)',
   ' (S. 9)</ls>'),
  ('</ls> (<ab>S.</ab> 791)',
   ' (S. 791)</ls>'),
  ('</ls> (<ab>S.</ab> 249)',
   ' (S. 249)</ls>'),
  ('</ls> (<ab>S.</ab> 249)',
   ' (S. 249)</ls>'),
  ('</ls> (<ab>S.</ab> 250)',
   ' (S. 250)</ls>'),
  ('</ls> (<ab>S.</ab> 152)',
   ' (S. 152)</ls>'),
  ('</ls> (<ab>S.</ab> 793)',
   ' (S. 793)</ls>'),
  ('</ls> (<ab>S.</ab> 22)',
   ' (S. 22)</ls>'),
  ('</ls> (<ab>S.</ab> 249)',
   ' (S. 249)</ls>'),
  ('</ls> (<ab>S.</ab> 249)',
   ' (S. 249)</ls>'),
  ('</ls> (<ab>S.</ab> 603)',
   ' (S. 603)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 248)',
   ' (S. 248)</ls>'),
  ('</ls> (<ab>S.</ab> 791)',
   ' (S. 791)</ls>'),
  ('</ls> (<ab>S.</ab> 894)',
   ' (S. 894)</ls>'),

  # END changes from make_change_04.txt
  ('(<ab>vgl.</ab> <ab>S.</ab> 11)',
   '(<ab>vgl.</ab> <ab n="Seite">S.</ab> 11)'),
  # BEGIN changes from make_change_05.txt
  ('<ls>Sp. 756, Z. 5. fgg.</ls>',
   '<ab>Sp.</ab> 756, <ab>Z.</ab> 5. <ab>fgg.</ab>'),
  ('<ls>Sp. 347, Z. 3. fgg.</ls>',
   '<ab>Sp.</ab> 347, <ab>Z.</ab> 3. <ab>fgg.</ab>'),
  ('<ls>Sp. 974, Z. 11. fgg.</ls>',
   '<ab>Sp.</ab> 974, <ab>Z.</ab> 11. <ab>fgg.</ab>'),
  ('<ls>Sp. 883, Z. 14. fgg.</ls>',
   '<ab>Sp.</ab> 883, <ab>Z.</ab> 14. <ab>fgg.</ab>'),
  ('<ls>Sp. 967, Z. 8. fgg.</ls>',
   '<ab>Sp.</ab> 967, <ab>Z.</ab> 8. <ab>fgg.</ab>'),
  ('<ls>Sp. 3, Z. 16. fgg.</ls>',
   '<ab>Sp.</ab> 3, <ab>Z.</ab> 16. <ab>fgg.</ab>'),
  ('<ls>Sp. 85, Z. 5. fgg.</ls>',
   '<ab>Sp.</ab> 85, <ab>Z.</ab> 5. <ab>fgg.</ab>'),
  ('<ls>Sp. 473, Z. 12. fgg.</ls>',
   '<ab>Sp.</ab> 473, <ab>Z.</ab> 12. <ab>fgg.</ab>'),
  ('<ls>Sp. 783, Z. 4. fgg.</ls>',
   '<ab>Sp.</ab> 783, <ab>Z.</ab> 4. <ab>fgg.</ab>'),
  ('<ls>Sp. 844, Z. 5. fgg.</ls>',
   '<ab>Sp.</ab> 844, <ab>Z.</ab> 5. <ab>fgg.</ab>'),
  ('<ls>Sp. 1092, Z. 16. fgg.</ls>',
   '<ab>Sp.</ab> 1092, <ab>Z.</ab> 16. <ab>fgg.</ab>'),
  ('<ls>Sp. 8, Z. 28. fgg.</ls>',
   '<ab>Sp.</ab> 8, <ab>Z.</ab> 28. <ab>fgg.</ab>'),
  ('<ls>Sp. 302, Z. 9. fgg.</ls>',
   '<ab>Sp.</ab> 302, <ab>Z.</ab> 9. <ab>fgg.</ab>'),
  ('<ls>Sp. 302, Z. 9. fgg.</ls>',
   '<ab>Sp.</ab> 302, <ab>Z.</ab> 9. <ab>fgg.</ab>'),
  ('<ls>Sp. 806, Z. 1. fgg.</ls>',
   '<ab>Sp.</ab> 806, <ab>Z.</ab> 1. <ab>fgg.</ab>'),
  ('<ls>Sp. 327, Z. 6. fgg.</ls>',
   '<ab>Sp.</ab> 327, <ab>Z.</ab> 6. <ab>fgg.</ab>'),
  ('<ls>Sp. 69, Z. 1. fgg.</ls>',
   '<ab>Sp.</ab> 69, <ab>Z.</ab> 1. <ab>fgg.</ab>'),
  # END changes from make_change_05.txt
  ('<ab>Schol.</ab> <ab>D.</ab> hat', '<ab>Schol.</ab> D. hat'),
  ('<ab>ed.</ab> <ls>GORR.</ls>', '<ls>ed. GORR.</ls>'),
  ('<ls>Sp. 856.</ls>', '<ab>Sp.</ab> 856.'),
  ('🞄<ls>Sp. 874,1 v. u.</ls> und <ls n="Sp.">875,1</ls>',
   '<ab>Sp.</ab> 874,1 <ab>v. u.</ab> und 875,1'),
  ('🞄<ls>Sp. 892, Z. 6 lies 3,226 st. 226.</ls>',
   '<ab>Sp.</ab> 892, <ab>Z.</ab> 6 lies 3,226 <ab>st.</ab> 226.'),
  ('<ls>AV. PRĀT.</ls> <ab>S.</ab> 261 (I,3. 4).',
   '<ls>AV. PRĀT. S. 261 (I, 3. 4)</ls>.'),
  ('<ls>P. 8,3,5</ls> (<ab>Th.</ab> II, <ab>S.</ab> 377).',
   '<ls>P. 8,3,5 (Th. II, S. 377)</ls>.'),
  ('(<ab>S.</ab> 385)',
   '(<ls n="">S. 385</ls>)'),
  ('(<ab>Th.</ab> II, <ab>S.</ab> 328)',
   '(<ls n="">Th. II, S. 328</ls>)'),
  ('(<ab>vgl.</ab> <ab>S.</ab> 370)',
   '(<ab>vgl.</ab> <ab n="Seite">S.</ab> 370)'),
  ('🞄<ls>Sp. 998, Z. 9 lies 6,1,2,17.</ls>',
   '<ab>Sp.</ab> 998, <ab>Z.</ab> 9 lies 6,1,2,17.'),
  ('<ls>Sp. 1053, Z. 20. fg.</ls>',
   '<ab>Sp.</ab> 1053, <ab>Z.</ab> 20. <ab>fg.</ab>'),
  # BEGIN changes from make_change_06.txt
  ('<ls>Sp. 1053, Z. 20. fg.</ls>',
   '<ab>Sp.</ab> 1053, <ab>Z.</ab> 20. <ab>fg.</ab>'),
  ('<ls>Sp. 137, Z. 11. fg.</ls>',
   '<ab>Sp.</ab> 137, <ab>Z.</ab> 11. <ab>fg.</ab>'),
  ('<ls>Sp. 190, Z. 5. fg.</ls>',
   '<ab>Sp.</ab> 190, <ab>Z.</ab> 5. <ab>fg.</ab>'),
  ('<ls>Sp. 423, Z. 2. fg.</ls>',
   '<ab>Sp.</ab> 423, <ab>Z.</ab> 2. <ab>fg.</ab>'),
  ('<ls>Sp. 476, Z. 7. fg.</ls>',
   '<ab>Sp.</ab> 476, <ab>Z.</ab> 7. <ab>fg.</ab>'),
  ('<ls>Sp. 605, Z. 6. fg.</ls>',
   '<ab>Sp.</ab> 605, <ab>Z.</ab> 6. <ab>fg.</ab>'),
  ('<ls>Sp. 638, Z. 3. fg.</ls>',
   '<ab>Sp.</ab> 638, <ab>Z.</ab> 3. <ab>fg.</ab>'),
  ('<ls>Sp. 825, Z. 16. fg.</ls>',
   '<ab>Sp.</ab> 825, <ab>Z.</ab> 16. <ab>fg.</ab>'),
  ('<ls>Sp. 112, Z. 2. fg.</ls>',
   '<ab>Sp.</ab> 112, <ab>Z.</ab> 2. <ab>fg.</ab>'),
  ('<ls>Sp. 166, Z. 1. fg.</ls>',
   '<ab>Sp.</ab> 166, <ab>Z.</ab> 1. <ab>fg.</ab>'),
  ('<ls>Sp. 353, Z. 4. fg.</ls>',
   '<ab>Sp.</ab> 353, <ab>Z.</ab> 4. <ab>fg.</ab>'),
  ('<ls>Sp. 423, Z. 6. fg.</ls>',
   '<ab>Sp.</ab> 423, <ab>Z.</ab> 6. <ab>fg.</ab>'),
  ('<ls>Sp. 431, Z. 1. fg.</ls>',
   '<ab>Sp.</ab> 431, <ab>Z.</ab> 1. <ab>fg.</ab>'),
  ('<ls>Sp. 674, Z. 2. fg.</ls>',
   '<ab>Sp.</ab> 674, <ab>Z.</ab> 2. <ab>fg.</ab>'),
  ('<ls>Sp. 844, Z. 5. fg.</ls>',
   '<ab>Sp.</ab> 844, <ab>Z.</ab> 5. <ab>fg.</ab>'),
  ('<ls>Sp. 780, Z. 5. fg.</ls>',
   '<ab>Sp.</ab> 780, <ab>Z.</ab> 5. <ab>fg.</ab>'),
  ('<ls>Sp. 841, Z. 1. fg.</ls>',
   '<ab>Sp.</ab> 841, <ab>Z.</ab> 1. <ab>fg.</ab>'),
  ('<ls>Sp. 883, Z. 1. fg.</ls>',
   '<ab>Sp.</ab> 883, <ab>Z.</ab> 1. <ab>fg.</ab>'),
  ('<ls>Sp. 900, Z. 19. fg.</ls>',
   '<ab>Sp.</ab> 900, <ab>Z.</ab> 19. <ab>fg.</ab>'),
  ('<ls>Sp. 935, Z. 9. fg.</ls>',
   '<ab>Sp.</ab> 935, <ab>Z.</ab> 9. <ab>fg.</ab>'),
  ('<ls>Sp. 1051, Z. 3. fg.</ls>',
   '<ab>Sp.</ab> 1051, <ab>Z.</ab> 3. <ab>fg.</ab>'),
  ('<ls>Sp. 1068, Z. 11. fg.</ls>',
   '<ab>Sp.</ab> 1068, <ab>Z.</ab> 11. <ab>fg.</ab>'),
  ('<ls>Sp. 12, Z. 8. fg.</ls>',
   '<ab>Sp.</ab> 12, <ab>Z.</ab> 8. <ab>fg.</ab>'),
  ('<ls>Sp. 176, Z. 2. fg.</ls>',
   '<ab>Sp.</ab> 176, <ab>Z.</ab> 2. <ab>fg.</ab>'),
  ('<ls>Sp. 375, Z. 4. fg.</ls>',
   '<ab>Sp.</ab> 375, <ab>Z.</ab> 4. <ab>fg.</ab>'),
  ('<ls>Sp. 590, Z. 12. fg.</ls>',
   '<ab>Sp.</ab> 590, <ab>Z.</ab> 12. <ab>fg.</ab>'),
  ('<ls>Sp. 931, Z. 2. fg.</ls>',
   '<ab>Sp.</ab> 931, <ab>Z.</ab> 2. <ab>fg.</ab>'),
  ('<ls>Sp. 152, Z. 32. fg.</ls>',
   '<ab>Sp.</ab> 152, <ab>Z.</ab> 32. <ab>fg.</ab>'),
  # END changes from make_change_06.txt
  # 62%
  ('<ls>Spr. 814</ls>, <ab>v. l.</ab> (<ab>Th.</ab> 2, <ab>S.</ab> 330).',
   '<ls>Spr. 814, v. l. (Th. 2, S. 330)</ls>.'),
  
  ('v. <ab>s.</ab> e. <ab>Th.</ab> ab',
   '<ab n="vor">v.</ab> <ab n="seinen eigenen Thaten">s. e. Th.</ab> ab'),
  
  # 74227
  ('fehlerhaft für {#jaWara#} 🞄<ls>SĀH. D. 103,22.</ls> 🞄<ls>Spr. 814, v. l. (Th. 2, S. 330)</ls>.',
   'fehlerhaft für {#jaWara#} <ls>SĀH. D. 103,22</ls>. <ls>Spr. 814</ls>, <ab>v. l.</ab> (<ls n="">Th. 2, S. 330</ls>).'),
  
  ('<ls>PRAB.</ls> <ab>S.</ab> 98, <ab>Z.</ab> 6.',
   '<ls>PRAB. S. 98, Z. 6</ls>.'),
  ('<ab>ed.</ab> 🞄<ls>LASS. 3,16.</ls>',
   ' <ls>ed. LASS. 3,16</ls>.'),
  ('(<ls n="HARIV.">11070</ls>, <ab>S.</ab> 792)',
   '(<ls n="HARIV.">11070, S. 792</ls>)'),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  
  ]
 newlines = []
 nchg = 0
 for iline,line in enumerate(lines):
  newline = line
  for old,new in replacements:
   newline = newline.replace(old,new)
  if newline != line:
   nchg = nchg + 1
  newlines.append(newline)
 print(f'{nchg} line(s) changed')
 return newlines

if __name__=="__main__":
 filein = sys.argv[1]  # base
 fileout = sys.argv[2] # adjusted base
 
 lines = read_lines(filein)

 lines1 = adjust_lines1(lines)
 #lines2 = adjust_lines2(lines1)
 write_lines(fileout,lines1)
