""" change_0k_0m.py
 
"""
import sys,re
import codecs

def read_lines(filein):
 lines = []
 with codecs.open(filein,encoding='utf-8',mode='r') as f:
  for line in f:
   lines.append(line.rstrip('\r\n'))
 print(f'{len(lines)} lines read from {filein}')
 return lines

def write_lines(fileout,outarr):
 with codecs.open(fileout,'w','utf-8') as f:
  for out in outarr:
   f.write("%s\n" % out)
 print(f'{len(outarr)} lines written to {fileout}')


def adjust_lines1(lines):
 replacements = [
  # 06-10-2026.
  # 87%
  
  ('{%ein heterodoxes System <ab>d.</ab> Ph.%}',
   '{%ein heterodoxes System <ab n="der Philosophie">d. Ph.</ab>%}'),
  ('<ls>AV. PRĀT.</ls> <ab>S.</ab> 261.',
   '<ls>AV. PRĀT. S. 261</ls>.'),
  ('adyy. <ls>SUŚR. 2,226,12. fg.</ls>',
   '<ab>advv.</ab> <ls>SUŚR. 2,226,12. fg.</ls>'),
  ('<ab>u.</ab> 🞄[Page7-0593] 🞄<ab>s.</ab> <ab>w.</ab>',
   '<ab>u. s. w.</ab> 🞄[Page7-0593] 🞄'),
  ('gl. <ab>Z.</ab> zeigend',
   '<ab n="glänzenden Zähnen">gl. Z.</ab> zeigend'),
  ('<ls>GILD.</ls> Bibl. 421. <ab>fg.</ab>',
   '<ls>GILD. Bibl. 421. fg.</ls>'),
  ('imComm. zu <ls>TBR. 1,164,6.</ls>',
   'im <ab>Comm.</ab> zu <ls>TBR. 1,164,6</ls>.'),
  ('{%leicht%} <ab>z.</ab>', '{%leicht%} <ab n="zu">z.</ab>'),

  # 88%
  
  ('die neuere Ausg)',
   'die neuere <ab>Ausg.</ab>)'),
  ('{%eine nicht vorhandene A.%}',
   '{%eine nicht vorhandene <ab n="Absicht">A.</ab>%}'),
  ('{%eine falsche A.%}',
   '{%eine falsche <ab n="Ansicht">A.</ab>%}'),
  ('{%sieben Meere habend, von <ab>s.</ab> M. umgeben%}',
   '{%sieben Meere habend, von <ab n="sieben Meere">s. M.</ab> umgeben%}'),
  ('<ab>ed.</ab> <ls>TULLB. 74,9</ls>',
   '<ls>ed. TULLB. 74,9</ls>'),
  ('(as cubit, fathom, finger, etc).',
   '(as cubit, fathom, finger, <ab>etc.</ab>)'),
  ('Ort des <ab>Z.</ab>',
   'Ort des <ab n="Zusammenfluss">Z.</ab>'),
  ('🞄<ab>S.</ab> 265, 12.',
   '<ls n="Verz. d. B. H.">S. 265,12</ls>.'),
  ('<ls>AV. PRĀT.</ls> <ab>S.</ab> 261, II,3.',
   '<ls>AV. PRĀT. S. 261, II, 3</ls>.'),
  ('<ab>Aufl.</ab> 🞄<ls n="VP.">2,179</ls>).',
   '<ls n="VP.">2te Aufl. 2,179</ls>).'),
  ('<ab>ed.</ab> 🞄<ls>TULLB.</ls>',
   '<ls>ed. TULLB.</ls>'),
  ('<ls>ṚV. PRĀT.</ls> (<ab>ed.</ab> M.) <ls n="ṚV. PRĀT.">1,2.</ls>',
   '<ls>ṚV. PRĀT. (ed. M.) 1,2</ls>.'),
  ('<ls>UṆĀDIS. 1,108</ls> (<ab>S.</ab> 26, <ab>Z.</ab> 1. 13).',
   '<ls>UṆĀDIS. 1,108 (S. 26, Z. 1. 13)</ls>.'),
  ('(<ab>ed.</ab> <ls>BÖHTL.</ls>)',
   '(<ls>ed. BÖHTL.</ls>)'),
  ('Nähe von <ab>S.</ab>',
   'Nähe von <is n="Sugrīva">S.</is>'),
  ('<ab>N.</ab> 🞄[Page7-0728] 🞄pr.',
   '<ab>N. pr.</ab> 🞄[Page7-0728] 🞄'),
  ('<ls>VS.</ls> <ab>S.</ab> {#160#} .',
   '<ls>VS. S. {#160#}.</ls>'),

  # 89%
  ('<ab>Schol.</ab> <ls>VOP.</ls> <ab>Einl.</ab>',
   '<ab>Schol.</ab> <ls>VOP. Einl.</ls>'),
  ('<ab>d. h.</ab> g.',
   '<ab>d. h.</ab> <ab n="gemeinschaftlichen">g.</ab>'),
  ('(<ab>S.</ab> 131). fehlerhaft ist die Lesart 🞄<ab>S.</ab> 87.',
   '(<ls n="">S. 131</ls>). fehlerhaft ist die Lesart <ls n="">S. 87</ls>.'),
  ('<ls>BṚH. ĀR. UP. S. 96. pass. 88.</ls>',
   '<ls>BṚH. ĀR. UP. S. 96</ls>. <ab>pass.</ab> <ls n="BṚH. ĀR. UP. S.">88</ls>.'),
  #('{%<ab>v. a.</ab> <ab>S.</ab> beschienen%}',
  # '<ab n="von allen Seiten">v. a. S.</ab> {%beschienen%}'),
  ('so <ab>v. a.</ab> {%<ab>v. a.</ab> <ab>S.</ab> beschienen%}',
   'so <ab n="von allen Seiten">v. a. S.</ab> {%beschienen%}'),
  ('{%Vatica robusta <ab>W.</ab> et. A.%}',
   '{%Vatica robusta W. et. A.%}'),
  ('{%nach allen Richtungen hin, von a. R. her%}',
   '{%nach allen Richtungen hin, von <ab n="allen Richtungen">a. R.</ab> her%}'),
  ('<ab>ad.</ab> {%ganz aufgeblüht%}',
   '<lex>adj.</lex> {%ganz aufgeblüht%}'),
  ('{%du mit dem ganzen <ab>W.</ab>%}',
   '{%du mit dem ganzen <ab n="Wagengefolge">W.</ab>%}'),
  ('{%in a. J. vorhanden%}',
   '{%in <ab n="allen Jahreszeiten">a. J.</ab> vorhanden%}'),

  # 90%
  
  ('{#sa/rvavedas#}¦ <ab>ad.</ab>',
   '{#sa/rvavedas#}¦ <lex>adj.</lex>'),
  ('<is>Adhyāya</is> 86. <ab>fgg.</ab>',
   '<is>Adhyāya</is> <ls n="VARĀH. BṚH. S.">86. fgg.</ls>'),
  ('<ab>d.</ab> g. K.',
   '<ab n="den ganzen Körper">d. g. K.</ab>'),
  ('G. oder L. machend, von G.%} oder {%L. widerhallend%}',
   '<ab n="Geräusch">G.</ab> oder <ab n="Lärm">L.</ab> machend, von <ab n="Geräusch">G.</ab>%} oder <ab n="Lärm">L.</ab> {%widerhallend%}'),
  ('und <ab>S.</ab> 261.',
   'und <ab n="Seite">S.</ab> 261.'),
  ('<ab>ed.</ab> TR.).',
   '<ls>ed. TR.</ls>).'),
  ('{%einen guten Gef. habend%}',
   '{%einen guten <ab n="Gefährten">Gef.</ab> habend%}'),
  ('{%eine l. Schwester%}',
   '{%eine <ab n="leiblicher">l.</ab> Schwester%}'),
  ('{#˚sUtra#} <ls n="VARĀH. BṚH. S.">2, Anf.</ls>',
   '{#˚sUtra#} 2, <ab>Anf.</ab>'),
  ('<ab>nom.</ab> abstr',
   '<ab>nom. abstr.</ab>'),
  ('<ls>VOP. 6,58.</ls>  <ab>Anf.</ab>',
   '<ls>VOP. 6,58. Anf.</ls>'),
  ('{%eine unübersehbare Anzahl von%} <ab>D.</ab>',
   '{%eine unübersehbare Anzahl von%} <is n="Daitya">D.</is>'),
  ('<ls>ebend.</ls> 292, {%b%}, 31. <ab>fg.</ab>',
   '<ls>ebend. 292,b,31. fg.</ls>'),
  ('Bewohner von%} 🞄<ab>S.</ab>',
   'Bewohner von%} <is n="Sāṃkāśyaka">S.</is>'),
  ('<ls n="Verz. d. Oxf. H.">213,a,1.</ls> 🞄[Page7-0902] 🞄<ab>v. u.</ab>',
   '<ls n="Verz. d. Oxf. H.">213,a,1. v. u.</ls> 🞄[Page7-0902] 🞄'),

  # 91%
  
  ('<ab>u.</ab> 🞄[Page7-0935] 🞄<ab>s.</ab> <ab>w.</ab>',
   '<ab>u. s. w.</ab> 🞄[Page7-0935] 🞄'),
  ('ls>AV. PRĀT.</ls> <ab>S.</ab> 261 (4, I,9).',
   '<ls>AV. PRĀT. S. 261 (4, I, 9)</ls>.'),
  ('{%mit <ab>W.</ab> bestreut%}',
   '{%mit <ab n="Weizenmehl">W.</ab> bestreut%}'),
  ('wie viele <ab>S.</ab>',
   'wie viele <is n="Sāmidheni">S.</is>'),
  ('ab>ed.</ab> <ls>TULLB. 44,1</ls>',
   '<ls>ed. TULLB. 44,1</ls>'),
  ('<ab>ed.</ab> SCHL. <ls n="HIT.">104,7.</ls>',
   '<ls n="HIT.">ed. SCHL. 104,7</ls>.'),
  ('{%über die g. E. verbreitet%}',
   '{%über die <ab n="ganzen Erde">g. E.</ab> verbreitet%}'),
  ('eine Ger. enthaltend',
   'eine <ab n="Geringschätzung">Ger.</ab> enthaltend'),
  ('HIT. <ab>ed.</ab> SCHL. <ls n="HIT.">54,19.</ls> <ls n="HIT.">58,19</ls>, <ab>v. l.</ab> <ls n="HIT.">100,3.</ls>',
   '<ls>HIT. ed. SCHL. 54,19. 58,19</ls>, <ab>v. l.</ab> <ls n="">100,3</ls>.'),
  ('🞄<ls>PISCHEL</ls>, De <ab>gramm.</ab> pr. 40.',
   '<ls>PISCHEL, De gramm. pr. 40</ls>.'),
  ('🞄<ls>PISCHEL</ls>, De <ab>gramm.</ab> pr. 39. <ab>fgg.</ab>',
   '<ls>PISCHEL, De gramm. pr. 39. fgg.</ls>'),
  ('🞄<span>N. 9</span>',
   '<ab n="Note">N.</ab> 9'),
  ('{%mit Zaubermacht versehen, <ab>Z.</ab> besitzend%}',
   '{%mit Zaubermacht versehen, <ab n="Zaubermacht">Z.</ab> besitzend%}'),
  ('<ab>ed.</ab> 🞄<ls>KOSEG. 242,5.</ls>',
   '<ls>ed. KOSEG. 242,5</ls>.'),

  # 92%  End 2026-06-10  Begom 2026-06-11
  
  ('Notices of Skt <ab>Mss.</ab> 🞄<ls n="WEBER, RĀMAT. UP.">1,17. 42.</ls>',
   '<ls>Notices of Skt Mss. 1,17. 42</ls>.'),
  ('(nach <ab>S.</ab>, <ab>W.</ab> und <ab>N.</ab>%}):',
   '(nach <ab n="Süd">S.</ab>, <ab n="West">W.</ab> und <ab n="Nord">N.</ab>)%}:'),
  ('{%mit Wohlbehagen verbunden, <ab>W.</ab> bewirkend%}',
   '{%mit Wohlbehagen verbunden, <ab n="Wohlbehagen">W.</ab> bewirkend%}'),
  ('(<ab>fg.</ab> {#A#})',
   '(<lex>f.</lex> {#A#})'),
  ('{%ein Bock für den%} <ab>S.</ab>',
   '{%ein Bock für den%} <is n="Subrahmaṇya">S.</is>'),
  ('🞄{#sumeDya#} <ab>ed.</ab> <ls>SCHL.</ls>',
   '{#sumeDya#} <ls>ed. SCHL.</ls>'),
  ('{%die Herrschaft über <ab>d.</ab> G.%}',
   '{%die Herrschaft über <ab n="die Götterwelt">d. G.</ab>%}'),
  ('{%das Harz der Gossampinus Rumphii <ab>Sch.</ab> et Endl.%}',
   '{%das Harz der%} {%Gossampinus Rumphii Sch. et Endl.%}'),

  # 93%
  
  ('{%ein Brahmane aus%} <ab>S.</ab>',
   '{%ein Brahmane aus%} <is n="Surāṣṭra">S.</is>'),
  ('{%ein Elephant der Götter%}, <is>Indra\'s</is> E.',
   '{%ein Elephant der Götter%}, <is>Indra</is>ʼs <ab n="Elephant">E.</ab>'),
  ('aus sch. H. a. K.',
   'aus <ab n="schöne Haare am Körper">sch. H. a. K.</ab>'),
  ('eines nach NW.verlegten {%Landes%}',
   'eines nach <ab n="Nord-West">NW.</ab> verlegten {%Landes%}'),
  ('(proparox).',
   '(<ab>proparox.</ab>)'),
  ('<ab>N.</ab> 🞄[Page7-1142] 🞄pr.',
   '<ab>N. pr.</ab> 🞄[Page7-1142] 🞄'),
  ('<ab>ed.</ab> 🞄[Page7-1144] 🞄Bomb.',
   '<ls>ed. Bomb.</ls> 🞄[Page7-1144] 🞄'),
  ('(<ab>vgl.</ab> 🞄<ls>HIT.</ls> <ab>Comm.</ab> <ab>S.</ab> 134)',
   '(<ab>vgl.</ab> <ls>HIT.</ls> <ab>Comm.</ab> <ab n="Seite">S.</ab> 134)'),
  ('{%die Zeit des <ab>S.</ab>%}',
   '{%die Zeit des <is n="Sūrya">S.</is>%}'),

  # 94%
  
  ('🞄<ls>TRIK. Ind.</ls> zu <ls n="TRIK.">2,8,2.</ls>',
   '<ls>TRIK.</ls> <ab>Ind.</ab> zu <ls n="TRIK.">2,8,2</ls>.'),
  ('{%die Küste von C.%}',
   '{%die Küste von <ab n="Ceylon">C.</ab>%}'),
  ('{%ein Kind der%} <ab>S.</ab>',
   '{%ein Kind der%} <is n="Siṃhikā">S.</is>'),
  ('{%Steinsalz an Weisse, weiss wie <ab>St.</ab>%}',
   '{%Steinsalz an Weisse, weiss wie <ab n="Steinsalz">St.</ab>%}'),
  ('{%ein Fürst der Anwohner des I.%}',
   '{%ein Fürst der Anwohner des <ab n="Indus">I.</ab>%}'),
  ('{%mit Wasser versehen, <ab>W.</ab> enthaltend%}',
   '{%mit Wasser versehen, <ab n="Wasser">W.</ab> enthaltend%}'),
  ('{#goDa#} <ab>ed.</ab> Bomb',
   '{#goDa#} <ls>ed. Bomb.</ls>'),
  ('<ab>Comm.</ab> zu <ls>KAṆ. 1,2,1</ls> 🞄(<ab>S.</ab> 48, <ab>Z.</ab> 2).',
   '<ab>Comm.</ab> zu <ls>KAṆ. 1,2,1 (S. 48, Z. 2)</ls>.'),
  ('(vielleicht <lex>adj.</lex> {%aus%} <ab>S.</ab> {%stammend%})',
   '(vielleicht <lex>adj.</lex> {%aus%} <is n="Somaka">S.</is> {%stammend%})'),
  ('{%Mutter des%} <ab>S.</ab>',
   '{%Mutter des%} <is n="Soma">S.</is>'),
  ('{%ein Nachkomme des M.%}',
   '{%ein Nachkomme des <ab n="Mondgottes">M.</ab>%}'),
  ('{%eine Hymne an <ab>S.</ab> und%}',
   '{%eine Hymne an <is n="Soma">S.</is> und%}'),
  ('{%bestehend%}, <ab>S.</ab> {%enthaltend%}',
   '{%bestehend%}, <is n="Soma">S.</is> {%enthaltend%}'),
  ('{%liebend, durch%} <ab>S.</ab> {%begeistert%}',
   '{%liebend, durch%} <is n="Soma">S.</is> {%begeistert%}'),
  ('{%ein Ueberfall während des Schlafes, ein nächtlicher U.%}',
   '{%ein Ueberfall während des Schlafes, ein nächtlicher <ab n="Ueberfall">U.</ab>%}'),
  ('<ls>WEBER, RĀMAT. UP. 337. Inschr.</ls>',
   '<ls>WEBER, RĀMAT. UP. 337</ls>. <ab>Inschr.</ab>'),
  ('seiner Frau stehender%} <ab>S.</ab>',
   'seiner Frau stehender%} <is n="Suśruta">S.</is>'),
  ('🞄<ls>SĀMAGĀNA</ls> Tüb. <ab>Hdschr.</ab>',
   '<ls>SĀMAGĀNA Tüb. Hdschr.</ls>'),

  # 95%
  
  ('{%sich freuend an L.%}',
   '{%sich freuend an <ab n="Loblieder">L.</ab>%}'),
  ('{%Frauenhuldigung, geschlechtlicher Verkehr mit Fr.%}',
   '{%Frauenhuldigung, geschlechtlicher Verkehr mit <ab n="Frauenhuldigung">Fr.</ab>%}'),
  ('(<ab>S.</ab> 790. <ab>med.</ab>)',
   '(<ls>S. 790</ls>. <ab>med.</ab>)'),
  ('hatte er <ab>d.</ab> g. E.',
   'hatte er <ab n="der ganzen Erde">d. g. E.</ab>'),
  ('{%geleitet <ab>auf.</ab>%} (<ab>loc.</ab>)',
  '{%geleitet auf%}, (<ab>loc.</ab>)'),
  ('{%zusammen seiend mit%} <ab>S.</ab>',
   '{%zusammen seiend mit%} <is n="Sugrīva">S.</is>'),
  ('<ls>MṚCCH. 83,8, v. l. 114,6.</ls>',
   '<ls>MṚCCH. 83,8</ls>, <ab>v. l.</ab> <ls n="">114,6</ls>.'),
  ('<ls>VET. in LA. (III) 2,2. Inschr.</ls>',
   '<ls>VET. in LA. (III) 2,2</ls>. <ab>Inschr.</ab>'),
  ('<lex>adj.</lex> 🞄<ab>comp.</ab>',
   '<ab>adj. comp.</ab>'),
  ('Unterabtheilung eines <ab>astr.</ab> H.',
   'Unterabtheilung eines <ab n="astrologisches Haus">astr. H.</ab>'),
  ('<ls n="KĀTY. ŚR.">Comm. 323,14.</ls>',
   '<ab>Comm.</ab> <ls n="KĀTY. ŚR.">323,14</ls>.'),
  ('<ls>MIT. III</ls>,30, {%a%},1 <ab>v. u.</ab> und {#sTAlaka#} .',
   '<ls>MIT. III, 30,a,1 v. u.</ls> und {#sTAlaka#}.'),
  ('<ls>BṚH. ĀR. UP. S. 10. fg. Inschr.</ls>',
   '<ls>BṚH. ĀR. UP. S. 10. fg.</ls> <ab>Inschr.</ab>'),
  ('🞄<ab>S.</ab> 658, <ab>Z.</ab> 15.',
   '<ab n="Seite">S.</ab> 658, <ab>Z.</ab> 15.'),
  ('es sich mit a <ab>W.</ab>%}',
   'es sich mit a <ab n="Wesen">W.</ab>%}'),
  ('{%malabarica <ab>Sch.</ab> und E.%}',
   '{%malabarica Sch. und E.%}'),
  ('{%malabarica <ab>Sch.</ab> et E.%}',
   '{%malabarica Sch. et E.%}'),
  ('{%Salmalia malabarica <ab>Sch.</ab> et E.%}',
   '{%Salmalia malabarica Sch. et E.%}'),
  ('Schol zu <ls>KAP. 1,33.</ls>',
   '<ab>Schol.</ab>_zu_<ls>KAP. 1,33</ls>.'),
  ('<ls>BHĀVAPR.; s. u.</ls>',
   '<ls>BHĀVAPR.</ls>; <ab>s. u.</ab>'),
  ('im- <ab>pers.</ab>',
   '<ab>impers.</ab>'),

  # 96%
  
  ('<ls>ṚT. 1,25, v. l. 26.</ls>',
   '<ls>ṚT. 1,25</ls>, <ab>v. l.</ab> <ls n="">26</ls>.'),
  ('auch fút. stehen.',
   'auch <ab>fut.</ab> stehen.'),
  ('<ls>SMARADĪPIKĀ</ls> Tüb. <ab>Hdschr.</ab>',
   '<ls>SMARADĪPIKĀ Tüb. Hdschr.</ls>'),
  ('<ls>TS. 1,2,13,3</ls> und <ab>Comm.</ab>',
   '<ls>TS. 1,2,13,3 und Comm.</ls>'),
  ('{%ein Weib der <ab>eig.</ab> K.%}',
   '{%ein Weib der <ab n="eigenen Kaste">eig. K.</ab>%}'),
  ('<ab>u.</ab> <ab>aa.</ab>',
   '<ab n="und">u.</ab> <ab n="auch allgemein">aa.</ab>'),
  ('(parox).',
   '<ab>parox.</ab>'),
  ('nach <ab>D.</ab>',
   'nach <ls n="Durgasiṃha">D.</ls>'),
  ('<ls>WILSON</ls> und <ab>N.</ab> 24',
   '<ls>WILSON</ls> und N. 24'),
  ('(so <ls>WILSON</ls>\'s <ab>Ausg.</ab>)',
   '(so <ls>WILSONʼs Ausg.</ls>)'),
  ('{%zur H. gemacht%}',
   '{%zur <ab n="Himmelsstadt">H.</ab> gemacht%}'),

  # 97%
  
  ('sich mit dem e. <ab>S.</ab>',
   'sich mit dem <ab n="eigenen Selbst">e. S.</ab>'),
  ('(pl).',
   '<ab>pl.</ab>'),
  ('<ls>ĀRAṆYAGĀNA</ls> Tüb. <ab>Hdschr.</ab>',
   '<ls>ĀRAṆYAGĀNA Tüb. Hdschr.</ls>'),
  ('<ls>P. 8,1,60</ls> an. ',
   '<ls>P. 8,1,60</ls> <ab>an.</ab>'),
  ('(in der Astr.)',
   '(in der <ab n="Astrolog">Astr.</ab>)'),
  ('Jahrhundert nach <ls>Chr.</ls>',
   'Jahrhundert nach <ab>Chr.</ab>'),
  ('{%wieder e. <ab>w.</ab>%}',
   '{%wieder <ab n="erlangen wollen">e. w.</ab>%}'),
  ('<ls>AV. PRĀT. 4,76. fg.</ls> <ab>S.</ab> 261,4, II,7. 14.',
   '<ls>AV. PRĀT. 4,76. fg. S. 261,4, II, 7. 14</ls>.'),
  ('{%als Beleg, — als Beispiel anführen%} Comm.',
   '{%als Beleg, — als Beispiel anführen%} <ab>Comm.</ab>'),
  ('<ls>M. 3,11</ls> (<ab>S.</ab> 178, <ab>Z.</ab> 7).',
   '<ls>M. 3,11 (S. 178, Z. 7)</ls>.'),

  # 98%
  
  ('<ls n="Verz. d. Oxf. H.">280,a,6</ls> nebst <ab>N.</ab> 2.',
   '<ls n="Verz. d. Oxf. H.">280,a,6 nebst N. 2.</ls>'),
  ('🞄<ab>S.</ab> 160.',
   '<ab n="Seite">S.</ab> 160.'),
  ('(aus v. 🞄<ls n="ṚV. 8,">18</ls> entnommen)',
   '(aus <ab n="vers">v.</ab> 18 entnommen)'),
  ('(in c. ist wohl {#haryatvatasutaH#} zu lesen)',
   '(in <ab n="comp.">c.</ab> ist wohl {#haryatvatasutaH#} zu lesen)'),
  ('{%so deutlich wie eine M. auf der Hand%}',
   '{%so deutlich wie eine <ab n="Myrobalane">M.</ab> auf der Hand%}'),
  ('{%mit einem Elephanten versehen, auf einem E. sitzend%}',
   '{%mit einem Elephanten versehen, auf einem <ab n="Elephanten">E.</ab> sitzend%}'),
  ('<is>Śākyamuni</is> als {%El.%}',
   '<is>Śākyamuni</is> als <ab n="Elephant">El.</ab>'),
  ('mit <ab>d.</ab> H. bearbeitet',
   'mit <ab n="der Hand">d. H.</ab> bearbeitet'),
  ('🞄<ab>S.</ab> 6, 4, 8. 16, 12, 1.',
   '<is n="Sāman">S.</is> <ls n="PAÑCAV. BR.">6,4,8. 16,12,1</ls>.'),
  ('(dat.)',
   '(<ab>dat.</ab>)'),
  ('<ab>ed.</ab> 🞄<ls>TR.</ls>).',
   '<ls>ed. TR.</ls>).'),

  # 99%
  
  ('{%zum Herzen dringend, dem H. zusagend%}',
   '{%zum Herzen dringend, dem <ab n="Herzen">H.</ab> zusagend%}'),
  ('{%zum Innern gehörig, dem I. entsprechend%}',
   '{%zum Innern gehörig, dem <ab n="Innern">I.</ab> entsprechend%}'),
  ('{%im Herzen befindlich, am H. liegend, dem H. zusagend%}',
   '{%im Herzen befindlich, am <ab n="Herzen">H.</ab> liegend, dem <ab n="Herzen">H.</ab> zusagend%}'),
  ('{%Terminalia Arjuna <ab>W.</ab> et A. (Feind der%} {#hfdroga#} {%genannten Krankheit%})',
   '{%Terminalia Arjuna W. et A.%} ({%Feind der%} {#hfdroga#} {%genannten Krankheit%})'),
  ('{%zur Ursache machen, als U. annehmen%}',
   '{%zur Ursache machen, als <ab n="Ursache">U.</ab> annehmen%}'),
  ('{%reich mit G. g.%}',
   '{%reich mit <ab n="Gold geschmückt">G. g.</ab>%}'),
  ('<ls>AUFRECHT</ls>, <ls>UṆĀDIS.</ls> <ab>Ind.</ab>',
   '<ls>AUFRECHT, UṆĀDIS. Ind.</ls>'),
  ('{%um%} <ab>St.</ab>',
   '{%um%} <is n="Stoma">St.</is>'),
  ('🞄{%ohne Steuermann%} Comm.',
   '{%ohne Steuermann%} <ab>Comm.</ab>'),
  ('🞄<ls>ROTH</ls>, der Atharvaveda in Kashmir, 🞄<ab>S.</ab> 24.',
   '<ls>ROTH, der Atharvaveda in Kashmir, S. 24</ls>.'),
  ('{%Anwendung, wiederholte A.%}',
   '{%Anwendung, wiederholte <ab n="Anwendung">A.</ab>%}'),
  ('(<ls>v. l.).</ls>',
   '(<ab>v. l.</ab>)'),
  ('🞄Sp. 803, <ab>Z.</ab> 3 füge 10,73,1 nach 8,66,1. 2 hinzu.',
   '<ab>Sp.</ab> 803, <ab>Z.</ab> 3 füge 10,73,1 nach 8,66,1. 2 hinzu.'),
  ('die Absicht eine h. H. abzubrechen',
   'die Absicht eine <ab n="heiligen Handlung">h. H.</ab> abzubrechen'),
  ('{%sine of the point of the ecliptic on the E. horizon%}',
   '{%sine of the point of the ecliptic on the <ab n="Eastern">E.</ab> horizon%}'),
  ('<ls>SŪRYAS. 5,17</ls> 🞄(<ab>S.</ab> 191, <ab>Z.</ab> 1).',
   '<ls>SŪRYAS. 5,17 (S. 191, Z. 1)</ls>.'),
  ('v. l; <ab>vgl.</ab> <ls>Spr. (II) 5823.</ls>',
   '<ab>v. l.</ab>; <ab>vgl.</ab> <ls>Spr. (II) 5823</ls>.'),
  ('gedachten <ab>Z.</ab>',
   'gedachten <ab n="Zauberspruchs">Z.</ab>'),
  ('{%Eigenschaft%}; vgl.',
   '{%Eigenschaft%}; <ab>vgl.</ab>'),
  ('<ab>N.</ab> <ab>p.</ab>',
   '<ab>N. pr.</ab>'),
  ('🞄<ab>S.</ab> 1067, <ab>Z.</ab> 1. 2',
   '<ab>Sp.</ab> 1067, <ab>Z.</ab> 1. 2'),
  ('der Astr.; vgl.',
   'in der <ab n="Astrolog">Astr.</ab>; <ab>vgl.</ab>'),
  ('<ab>S.</ab> <ab>d.</ab> <ab>superl.</ab>',
   '<ab n="Suffix des">S. d.</ab> <ab>superl.</ab>'),
  ('{%sobald als, seit.%} 🞄<ls>Z.</ls> <ls>B.</ls>',
   '{%sobald als, seit%}. <ab>Z. B.</ab>'),
  ('<ls>TATTVAS. st. TARKASAṂGR.</ls>',
   '<ls>TATTVAS.</ls> <ab>st.</ab> <ls>TARKASAṂGR.</ls>'),
  ('<ls>ROTH\'S</ls> Programm über den 🞄<ls>AV.</ls> in Kashmir 🞄<ab>S.</ab> 26.',
   '<ls>ROTHʼs Programm über den AV. in Kashmir S. 26</ls>.'),
  ('<ls>BĀDAR. 1,3,30</ls> (<ab>S.</ab> 300,7. 9).',
   '<ls>BĀDAR. 1,3,30 (S. 300,7. 9)</ls>.'),
  ('<ab>st.</ab> wie <ab>eben.</ab>',
   '<ab>st.</ab> wie eben.'),
  ('🞄(Calcutta 1857. 2te <ab>Aufl.</ab>)',
   '(<ls>Calcutta 1857. 2te Aufl.</ls>)'),
  ('<ab>Z.</ab> 2 lies 5, 83, 6 <ab>st.</ab> 5, 83, 7. — Sp. 303, <ab>Z.</ab> 4 <ab>v. u.</ab> lies 10, 49, 3.',
   '<ab>Z.</ab> 2 lies 5,83,6 <ab>st.</ab> 5,83,7. — <ab>Sp.</ab> 303, <ab>Z.</ab> 4 <ab>v. u.</ab> lies 10,49,3.'),
  ('Sp. 696, <ab>Z.</ab> 1 <ab>v. u.</ab> lies 7, 32, 16.',
   '<ab>Sp.</ab> 696, <ab>Z.</ab> 1 <ab>v. u.</ab> lies 7,32,16.'),
  ('<ls>Spr. (II) 1622.</ls> Sp. 698,',
   '<ls>Spr. (II) 1622</ls>. <ab>Sp.</ab> 698,'),
  ('Calc. <ab>Ausgg.</ab>',
   '<ls>Calc. Ausgg.</ls>'),
  ('<ab>vgl.</ab> 2te <ab>Aufl.</ab>',
   '<ab>vgl.</ab> 2te Aufl.'),
  ('<ab>vgl.</ab> 🞄2te <ab>Aufl.</ab>',
   '<ab>vgl.</ab> 2te <Aufl.'),
  ('fungirenden <ab>Nom.</ab>%} ag.',
   'fungirenden%} <ab>Nom. ag.</ab>'),
  ('{%auf Opfern b.%}',
   '{%auf Opfern <ab n="beruhend">b.</ab>%}'),
 ]
 newlines = []
 nchg = 0
 for iline,line in enumerate(lines):
  newline = line
  for old,new in replacements:
   newline = newline.replace(old,new)
  if newline != line:
   nchg = nchg + 1
  newlines.append(newline)
 print(f'{nchg} line(s) changed')
 return newlines

if __name__=="__main__":
 filein = sys.argv[1]  # base
 fileout = sys.argv[2] # adjusted base
 
 lines = read_lines(filein)

 lines1 = adjust_lines1(lines)
 #lines2 = adjust_lines2(lines1)
 write_lines(fileout,lines1)
