""" change_0g_0h.py
 
"""
import sys,re
import codecs

def read_lines(filein):
 lines = []
 with codecs.open(filein,encoding='utf-8',mode='r') as f:
  for line in f:
   lines.append(line.rstrip('\r\n'))
 print(f'{len(lines)} lines read from {filein}')
 return lines

def write_lines(fileout,outarr):
 with codecs.open(fileout,'w','utf-8') as f:
  for out in outarr:
   f.write("%s\n" % out)
 print(f'{len(outarr)} lines written to {fileout}')


def adjust_lines1(lines):
 replacements = [
  # 06-06-2026. 40%
  ('{%Gold%} u. s. w. ', '{%Gold%} <ab>u. s. w.</ab>'),
  (' z. B. ', ' <ab>z. B.</ab> '), #4
  ('</ls> <ab>p.</ab> 1',
   ' p. 1</ls>'),
  ('(vulg. ', '(<ab>vulg.</ab> '),
  (' v. 🞄<ls>Chr.</ls>', ' <ab>v. Chr.</ab>'),
  ('<ab>Th.</ab> II, <ls>Sp. 835</ls>',
   '<ls>Th. II, Sp. 835</ls>'),
  ('Clypea hernandifolia <ab>W.</ab>', 'Clypea hernandifolia W.'), #9
  ('<lex>n.</lex> <ab>abstr.</ab>', '<ab>n. abstr.</ab>'), # 41%  #19
  ('angehörig <ab>u.</ab> <ab>s.</ab> w%}',
   'angehörig%} <ab>u. s. w.</ab>'),
  (' des <lex>ind.</lex> Kuckucks%})',
   ' des <ab n="indische">ind.</ab> Kuckucks)%}'),
  ('<ls>Verz. d. Oxf. H. No. 457. fgg.</ls> <ab>S.</ab> <ls n="Verz. d. Oxf. H.">113,a.</ls>',
   '<ls>Verz. d. Oxf. H. No. 457. fgg. S. 113,a.</ls>'),
  ('<ls>KUHN</ls>, Herabkunft <ab>d.</ab> Feuers,208.',
   '<ls>KUHN, Herabkunft d. Feuers, 208</ls>.'),
  ('den Columnentiteln auf <ab>S.</ab> 1-15.',
   'den Columnentiteln auf <ab n="Seiten">S.</ab> 1—15.'),
  ('verdorben) 24. <ab>fgg.</ab>',
   'verdorben) <ls n="PAÑCAT. ed. orn. 38,">24. fgg.</ls>'),
  ('{%Terminalia tomentosa <ab>W.</ab> et A.%}',
   '{%Terminalia tomentosa W. et A.%}'), #5
  ('<lex>m.</lex> K. umgeben',
   '<ab n="männliche Kälber">m. K.</ab> umgeben'),  # 42%
  ('{%setzte sie zu%} <ab>p.</ab> {%ein%}',
   '{%setzte sie zu%} <is n="putrikā">p.</is> {%ein%}'),
  ('<ls>MBH. 12,13206</ls> (<ab>S.</ab> 831, <ab>Z.</ab> 8).',
   '<ls>MBH. 12,13206 (S. 831, Z. 8)</ls>.'),
  ('(v. 1. {#samupasTitam#})',
   '(<ab n="vgl.">v.</ab> 1. {#samupasTitam#})'),
  ('<ls>ṚV. PRĀT. 16,46</ls> und <ab>Anm.</ab>',
   '<ls>ṚV. PRĀT. 16,46 und Anm.</ls>'),
  ('(<ab>s.</ab> <ls>JOHAENTGEN</ls>, Ueber <ab>d.</ab> Ges. des <is>Manu</is>, <ab>S.</ab> 5)',
   '(<ab>s.</ab> <ls>JOHAENTGEN, Ueber d. Ges. des Manu, S. 5</ls>)'),
  ('<ls>JOHAENTGEN</ls> <ls>a. a. O. S. 5. 18</ls>',
   '<ls>JOHAENTGEN a. a. O. S. 5. 18</ls>'),
  ('<ls>Verz. d. Oxf. H. No. 94. 143.</ls> <ab>S.</ab> <ls n="Verz. d. Oxf. H.">162,b,15.</ls> <ls n="Verz. d. Oxf. H.">182,b,40.</ls>',
   '<ls>Verz. d. Oxf. H. No. 94. 143. S. 162,b,15. 182,b,40</ls>.'),
  ('Carl Graf v. GÖRTZ, Reise um die Welt III,552.',
   '<ls>Carl Graf</ls> <ab>v.</ab> <ls>GÖRTZ, Reise um die Welt III, 552</ls>.'),
  ('<lex>adj.</lex> 🞄[Page4-0807] 🞄<ab>comp.</ab>',
   '<ab>adj. comp.</ab> 🞄[Page4-0807] 🞄'),
  ('<ls>REINAUD</ls> (Mémoire sur l\'Inde <ab>S.</ab> 65)',
   '<ls>REINAUD (Mémoire sur lʼInde S. 65)</ls>'),
  ('mit der Bomb. <ab>Ausg.</ab> zu lesen',
   'mit der <ls>Bomb. Ausg.</ls> zu lesen'),
  ('der Richtung <ab>auf.</ab> zum Zweck',
   'der Richtung auf, zum Zweck'),
  ('{%die im Osten gangbare E. von%} J.',
   '{%die im Osten gangbare <ab n="Erzählung">E.</ab> von%} <is n="Yayāti">Y.</is>'),
  # 43%
  # 06-07-2026 begin
  ('{%die im Osten gangbare E. v.%}',
   '{%die im Osten gangbare <ab n="Erzählung von">E. v.</ab>%}'),
  ('(bei <ls>AUFRECHT</ls> im <ab>Ind.</ab> zu <ls>HALĀY.</ls>)',
   '(bei <ls>AUFRECHT</ls>_im_<ls>Ind. zu HALĀY.</ls>)'),  # 43%
  ('<ls n="HARIV.">7922</ls> (lies {#pOrARaM#}). <ab>fg.</ab>',
   '<ls n="HARIV.">7922 (lies {#pOrARaM#}). fg.</ls>'),
  ('<ls>Verz. d. Oxf. H. 7,b,9</ls> und 5 <ab>v. u.</ab>',
   '<ls>Verz. d. Oxf. H. 7,b,9 und 5 v. u.</ls>'),
  ('{#˚svara#} 🞄<ab>S.</ab> 261.',
   '{#˚svara#} <ab n="Seite">S.</ab> 261.'),
  ('<ls>TBR.</ls> <ab>Comm.</ab> I, <ab>S.</ab> 26,3.',
  '<ls>TBR. Comm. I, S. 26,3</ls>'),
  ('{#udaka˚#} 2 <ab>v. u.</ab>',
   '{#udaka˚#} <ls n="">2 v. u.</ls>'),
  ('<ls>DAŚAR. 1,41</ls> (<ab>S.</ab> 37,6 <ab>v. u.</ab>).',
   '<ls>DAŚAR. 1,41 (S. 37, 6 v. u.)</ls>.'),
  ('<ls>VS. 5,11</ls> (<ab>Comm.</ab>).',
   '<ls>VS. 5,11 (Comm.)</ls>.'),
  ('Zauberkunst%}, personif',
   'Zauberkunst%}, <ab>personif.</ab>'),
  ('liest die Bomb. <ab>Ausg.</ab>',
   'liest die <ls>Bomb. Ausg.</ls>'),
  ('{#nI#} mit {#pra#}, 🞄<ls n="ŚĀṄKH. ŚR.">2 (Sp. 278, Z. 8 ist 11,26,1</ls> zu streichen).',
   '{#nI#} mit {#pra#}, 2 (<ab>Sp.</ab> 278, <ab>Z.</ab> 8 ist 11,26,1 zu streichen).'),
  # 44%
  ('<ls n="R.">6,112,20.</ls> Bd. III, <ab>S.</ab> 465.',
   '<ls n="R.">6,112,20. Bd. III, S. 465</ls>.'),
  ('{%im <ab>W.</ab> stehen%}',
   '{%im <ab n="Widerspruch">W.</ab> stehen%}'),
  ('in seiner Chrest. 🞄<ab>S.</ab> 50, <ab>Z.</ab> 1',
   'in seiner <ls>Chrest. S. 50, Z. 1</ls>'),
  ('gen und <ab>intr.</ab> ',
   '<ab>gen.</ab> und <ab>intr.</ab> '),
  ('<ls>M. 1,5</ls> (<ab>S.</ab> 9, <ab>Z.</ab> 7).',
   '<ls>M. 1,5 (S. 9, Z. 7)</ls>.'),
  ('der Bomb. <ab>Ausg.</ab>',
   'der <ls>Bomb. Ausg.</ls>'),
  ('<ls>M. 2,1</ls> (<ab>S.</ab> 65, <ab>Z.</ab> 9).',
   '<ls>M. 2,1 (S. 65, Z. 9)</ls>.'),
  ('<ab>Corrigg.</ab> <ab>S.</ab> 312).',
   '<ab>Corrigg.</ab> <ab n="Seite">S.</ab> 312).'),
  ('{#vigalitapratyASatva#} 2, <ab>v. u.</ab>',
   '{#vigalitapratyASatva#} <ls n="">2, v. u.</ls>'),
  ('<ls>AUFR.</ls> <ls>HALĀY.</ls> <ab>Ind.</ab>',
   '<ls>AUFR. HALĀY. Ind.</ls>'),
  ('<ls>BṚH. ĀR. UP. 1,4,8</ls> (<ab>S.</ab> 195).',
   '<ls>BṚH. ĀR. UP. 1,4,8 (S. 195)</ls>.'),
  # 45%
  ('<ls>KAP. 1,87</ls> (<ab>S.</ab> 64, <ab>Z.</ab> 23).',
   '<ls>KAP. 1,87 (S. 64, Z. 23)</ls>.'),
  ('<ls>ebend.</ls> (<ab>S.</ab> 67, <ab>Z.</ab> 4).',
   '<ls>ebend. (S. 67, Z. 4)</ls>.'),
  (' nach einem Comm.', ' nach einem <ab>Comm.</ab>'),
  ('die Bomb. <ab>Ausg.</ab>',
   'die <ls>Bomb. Ausg.</ls>'), #19
  ('(von {#vac#} mit {#pra#}) <ab>u.</ab>',
   '(von {#vac#} mit {#pra#}) <lex>n.</lex>'),
  ('<ls>VARĀH. BṚH.</ls> <ab>S.</ab>',
   '<ls>VARĀH. BṚH. S.</ls>'),
  ('(von {#sar#} mit {#pra#}) <ab>w.</ab>',
   '(von {#sar#} mit {#pra#}) <lex>m.</lex>'),
  # 46%
  ('<ls>DHŪRTAS. 74,2. Inschr.</ls>',
   '<ls>DHŪRTAS. 74,2</ls>. <ab>Inschr.</ab>'),
  ('{%Terminalia tomentosa <ab>W.</ab> et. A.%}',
   '{%Terminalia tomentosa W. et. A.%}'), #3
  ('<ls>Ind. St. 8,136, N.</ls>',
   '<ls>Ind. St. 8,136</ls>, <ab>N.</ab>'),
  ('<ls>MBH. 9,9156</ls> (<ab>S.</ab> 248, <ab>Z.</ab> 1).',
   '<ls>MBH. 9,9156 (S. 248, Z. 1)</ls>.'),
  ('{%die Frucht der F. <ab>inf.</ab>%}',
   '{%die Frucht der F. inf.%}'),
  ('{%result (from base-sine or perp. sine%})',
   '{%result (from base-sine or <ab n="perpendicular">perp.</ab> sine)%}'),
  ('De rebus indicis <ab>etc.</ab> 🞄<lang n="arabic">٣٣</lang>, 🞄<ab>Z.</ab> 1 <ab>v. u.</ab>',
   '<ls>De rebus indicis etc.</ls> <arab>٣٣</arab>, <ls>Z. 1 v. u.</ls>'),
  ('und AVIC. <ls>ebend.</ls> 177, <ab>N.</ab> 7)',
   'und <ls>AVIC. ebend. 177, N. 7</ls>)'),
  ('{%im%} P., {%der sowohl das%} <ab>S.</ab>',
   '{%im%} <is n="Parva">P.</is>, {%der sowohl das%} <is n="Sauptika">S.</is>'),
  # 47%
  ('(viell. ', '(<ab>viell.</ab> '),
  ('<is>Halāyudhau</is>. <ab>s.</ab> <ab>w.</ab>',
   '<is>Halāyudha</is> <ab>u. s. w.</ab>'),
  ('<ab>N.</ab> 🞄[Page5-0033] 🞄pr.',
   '<ab>N. pr.</ab> 🞄[Page5-0033] 🞄'),
  ('göttlichen Wesens <ab>Einschieb.</ab>',
   'göttlichen Wesens Einschieb.'),
  ('<ls>VP. 444</ls> (<ab>vgl.</ab> <ab>N.</ab> 12).',
   '<ls>VP. 444 (vgl. N. 12)</ls>.'),
  ('Bomb. <ab>Ausg.</ab>',
   '<ls>Bomb. Ausg.</ls>'), #6
  ('<ls>ebend.</ls> 🞄<ab>S.</ab> <ls n="Verz. d. Oxf. H.">365,b, No. 87.</ls>',
   '<ls>ebend. S. 365,b, No. 87</ls>.'),
  ('<ls>Verz. d. Oxf. H. No. 37.</ls> <ab>S.</ab> <ls n="Verz. d. Oxf. H.">125,a,35.</ls>',
   '<ls>Verz. d. Oxf. H. No. 37, S. 125,a,35</ls>.'),
  ('</ls> (<ab>S.</ab> 573).',
   ' (S. 573)</ls>.'),
  ('(= {#nfkeSaja#} Scol.)',
   '(= {#nfkeSaja#} <ab>Schol.</ab>)'),
  ('<ls>AUFRECHT</ls> im <ab>Ind.</ab> zum <ls>HALĀY.</ls>',
   '<ls>AUFRECHT</ls> im <ls>Ind. zum HALĀY.</ls>'),
  ('</ls> (<ab>S.</ab> 8).',
   ' (S. 8)</ls>.'),
  ('<ab>u.</ab> A. gebraucht',
   '<ab n="und">u.</ab> <ab n="Anderen">A.</ab> gebraucht'),
  ('<ls>SAṂSK. K. 183,b,10. N.</ls> 🞄pr.',
   '<ls>SAṂSK. K. 183,b,10.</ls>  <ab>N. pr.</ab>'),
  ('(namentlich <ab>N.</ab> edulis)',
   '(namentlich <bot>N. edulis</bot>)'),
  ('<ls n="BHĀG. P. 5,">26,23</ls> <ab>ed.</ab> <ls>BURN.</ls>',
   '<ls n="BHĀG. P. 5,">26,23</ls> <ls>ed. BURN.</ls>'),
  # 48%
  (' 🞄<ls>Randgl.</ls>',
   ' <ab>Randgl.</ab>'),
  ('die Ergänzung ein infln.', 'die Ergänzung ein <ab>infin.</ab>'),
  ('<ab>S.</ab> <ls n="Verz. d. Oxf. H.">394,b.</ls>',
   '<ls n="Verz. d. Oxf. H.">S. 394,b</ls>.'),
  ('<ab>Adhy.</ab>',
   '<is n="Adhyāya">Adhy.</is>'),
  ('{%Polanisia icosandra <ab>W.</ab> et A.%}',
   '{%Polanisia icosandra W. et A.%}'),
  ('347, {%a%}, <ab>N.</ab>',
   '<ls n="Verz. d. Oxf. H.">347,a, N.</ls>'),
  ('<ls>LIA. I,64. 555, N.</ls>',
   '<ls>LIA. I,64. 555</ls>, <ab>N.</ab>'),
  ('<ls n="MBH.">12,12864</ls> (<ab>S.</ab> 518, <ab>Z.</ab> 7 <ab>v. u.</ab>).',
   '<ls n="MBH.">12,12864 (S. 518, Z. 7 v. u.)</ls>.'),
  ('(gen.)', '(<ab>gen.</ab>)'),
  ('Familien u. s. w. geliebt',
   'Familien <ab>u. s. w.</ab> geliebt'),
  ('{#Bakzantu#} <ab>Einschieb.</ab>',
   '{#Bakzantu#} Einschieb.'),
  ('<ls>VP.</ls> (<ab>S.</ab> 643 bei <ls>WILSON</ls>)',
   '<ls>VP. (S. 643 bei WILSON)</ls>'),
  (' 🞄<ls>STENZLER</ls>\'<ab>S.</ab>',
   '<ls>STENZLER</ls>ʼs.'),
  ('{#yadyadicCanti tatsarvaM laBante (Bajante#} <ab>ed.</ab> Bomb).',
   '{#yadyadicCanti tatsarvaM laBante#} ({#Bajante#} <ls>ed. Bomb.</ls>)'),
  ('{%ohne die l. A.%}',
   '{%ohne die <ab n="luftigen Atomen">l. A.</ab>%}'),
  ('<ls>M. 1,21</ls> (<ab>S.</ab> 23, <ab>Z.</ab> 1).',
   '<ls>M. 1,21 (S. 23, Z. 1)</ls>.'),
  ('<ls>MĀRK. P. S. 660.</ls> <ab>Z.</ab> 4.',
   '<ls>MĀRK. P. S. 660. Z. 4</ls>.'),
  ('dem 10ten Jahrh', 'dem 10ten <ab>Jahrh.</ab>'),
  # 49%
  ('<ls>MAITRYUP. 6,35. Bein. <is>Brahman\'s</is></ls>', 
   '<ls>MAITRYUP. 6,35</ls>. <ab>Bein.</ab> <is>Brahman</is>ʼs'),
  ('(acc).', '(<ab>acc.</ab>)'),
  (' <ab>Einschieb.</ab> nach ', ' Einschieb. nach '),
  ('<ls>M. 3,11</ls> (<ab>S.</ab> 178, <ab>Z.</ab> 1).',
   '<ls>M. 3,11 (S. 178, Z. 1)</ls>.'),
  ('<ls>MĀRK. P. S. 659.</ls> <ab>Z.</ab> 3.',
   '<ls>MĀRK. P. S. 659. Z. 3</ls>.'),
  (' Bed. ', ' <ab>Bed.</ab> '),
  ('<ls>P. 1,2,32</ls> (<ab>Th.</ab> II).',
   '<ls>P. 1,2,32 (Th. II)</ls>.'),
  ('{%Abelmoschus esculentus <ab>W.</ab> und A.%}',
   '{%Abelmoschus esculentus W. und A.%}'),
  # 50%
  ('<ab>S.</ab> 516 bei <ls>BOLLENSEN.</ls>',
   '<ab n="Seite">S.</ab> 516 bei <ls>BOLLENSEN.</ls>'),
  (' inbes. ', ' <ab>insbes.</ab> '),
  ('<ls>ĀŚV. GṚHY.</ls> <ab>Einschieb.</ab>',
   '<ls>ĀŚV. GṚHY.</ls> Einschieb.'),
  ('<ls>AUFRECHT, HALĀY.</ls> <ab>Ind.</ab>',
   '<ls>AUFRECHT, HALĀY. Ind.</ls>'),
  ('<ls>ŚUK.</ls> Pet. <ab>Hdschr.</ab> 31, {%b%},1.',
   '<ls>ŚUK. Pet. Hdschr. 31,b,1</ls>.'),
  ('{#amitrAnBUyaSo (BUyaso#} <ab>ed.</ab> B.)',
   '{#amitrAnBUyaSo#} ({#BUyaso#} <ls>ed. B.</ls>)'),
  ('Progr. der Univ. Breslau 1860, <ab>S.</ab> 12 <ab>fgg.</ab>',
   '<ls>Progr. der Univ. Breslau 1860, S. 12. fgg.</ls>'),
  ('<ls>KUHN</ls>, Herabkunft der Feuers, <ab>S.</ab> 6. <ab>fgg.</ab>',
   '<ls>KUHN, Herabkunft der Feuers, S. 6. fgg.</ls>'),
  # 51%
  ('nebst der <ab>Anm.</ab> <ab>S.</ab> <ls n="Spr.">398.</ls>',
   'nebst der <ls>Anm. S. 398</ls>.'),
  ('</ls> (<ab>S.</ab> 569).',
   ' (S. 569)</ls>.'),
  ('<ls>WEBER</ls> vermuthet <ab>a. a. O.</ab>',
   '<ls>WEBER</ls> vermuthet <ls n="Weber">a. a. O.</ls>'),
  ('<ab>ed.</ab> <ls>LANGL. I,518. 526.</ls>',
   '<ls>ed. LANGL. I, 518. 526</ls>.'),
  ('(<ab>ed.</ab> SCHL. <ls n="HIT.">59,22</ls>)',
   '(<ls n="HIT.">ed. SCHL. 59,22</ls>)'),
  ('{#(ma˚ + dA#}, <lex>f.</lex> v. 1. {#da)#}',
   '({#ma˚#} + {#dA#}, <lex>f.</lex> <ab n="von">v.</ab> <hom>1.</hom> {#da#})'),
  ('<ab>ed.</ab> B.',
   '<ls>ed. B.</ls>'),
  # 52%
  ('SḌTS.', '<ab n="Spondee-Dactyl-Trochee-Trochee-Spondee">SD2TS</ab>.'),
  ('(<ls>ST. und der Schol.</ls> in der <ab>Calc. Ausg.</ab> {%Wein).%}',
   '(<ls>ST.</ls> und der <ab>Schol.</ab> in der <ab>Calc. Ausg.</ab> {%Wein%})'),
  ('<ab>u.</ab> <ab n="dem">d.</ab> <ab>vorherg.</ab>',
   '<ab>u. d.</ab> <ab>vorherg.</ab>'),
  ('<ls>BENF.</ls> <ab>Uebers.</ab> <ls n="BENFEY, SV.">S. 221, N. 3.</ls>',
   '<ls>BENF. Uebers. S. 221, N. 3</ls>.'),
  ('{%Bienenstock%}, s. {#cazAla#}',
   '{%Bienenstock%}, <ab>s.</ab> {#cazAla#}'),
  ('{#maDuzyanda#} <ab>ed.</ab> 🞄<ls>SCHL. 1,57,3.</ls>',
   '{#maDuzyanda#} <ls>ed. SCHL. 1,57,3</ls>.'),
  ('im <ab>N.</ab>, dem <is>Vindhya</is> im <ab>S.</ab>, <is>Vinaśana</is> im <ab>W.</ab> und <is>Prayāga</is> im O.',
   'im <ab n="Nord">N.</ab>, dem <is>Vindhya</is> im <ab n="Süd">S.</ab>, <is>Vinaśana</is> im <ab n="West">W.</ab> und <is>Prayāga</is> im <ab n="Osten">O.</ab>'),
  ('<ls>TAITT. UP. 2,7.</ls> Cit. in ',
   '<ls>TAITT. UP. 2,7</ls>. <ab>Cit.</ab> in '),
  ('<ls>SCHLEGEL</ls>\'s <ab>Uebers.</ab>',
   '<ls>SCHLEGELʼs Uebers.</ls>).'),
  #('(<ab>vgl.</ab> 🞄<ls>Sp. 519, Z. 35. fgg.</ls>)',
  # '(<ab>vgl.</ab> <ls>Sp. 519, Z. 35. fgg.</ls>)'),
  ('(<ab>vgl.</ab> 🞄<ls>Sp. 519, Z. 35. fgg.</ls>)',
   '(<ab>vgl.</ab> <ab>Sp.</ab> 519, <ab>Z.</ab> 35. <ab>fgg.</ab>)'),
  ('<ls>AV. PRĀT. 4,35.</ls> <ab>S.</ab> 261 (I,1)',
   '<ls>AV. PRĀT. 4,35. S. 261 (I, 1)</ls>'),
  ('<ls>ṚV.</ls> <ab>Comm.</ab> I, <ab>S.</ab> 22.',
   '<ls>ṚV. Comm. I, S. 22</ls>.'),
  ('{#astram — tvadvaDAyAnumantritam (aBimantritam#} <ab>ed.</ab> 🞄<ls>SCHL.</ls>)',
   '{#astram — tvadvaDAyAnumantritam#} ({#aBimantritam#} <ls>ed. SCHL.</ls>)'),
  ('{#astram — tvadvaDAyABimantritam (anumantritam#} <ab>ed.</ab> 🞄<ls>GORR.</ls>)',
   '{#astram — tvadvaDAyABimantritam#} ({#anumantritam#} <ls>ed. GORR.</ls>)'),
  ('{#Baratam — AtiTyenAByamantrayat (nyamantrayat#} <ab>ed.</ab> 🞄<ls>SCHL.</ls>)',
   '{#Baratam — AtiTyenAByamantrayat#} ({#nyamantrayat#} <ls>ed. SCHL.</ls>)'),
  ('<ab>ed.</ab> 🞄<ls>JOHNS. 990.</ls>',
   '<ls>ed. JOHNS. 990</ls>.'),
  ('(<ab>vgl.</ab> 🞄<ls>SCHÜTZ\'S</ls> <ab>Uebers.</ab>)',
   '(<ab>vgl.</ab> <ls>SCHÜTZʼs Uebers.</ls>)'),
  ('{%Nacken, Nackenmuskel, Musculus cucullaris <ab>s.</ab> trapezius%}',
   '{%Nacken, Nackenmuskel%}, {%Musculus cucullaris s. trapezius%}'),
  # 53%
  ('({#mAru˚#} v. l)',
   '({#mAru˚#} <ab>v. l.</ab>)'),
  ('<ls n="ŚATR.">500. 8,699</ls> (<ab>S.</ab> 23 bei <ls>WEBER</ls> ).',
   '<ls n="ŚATR.">500. 8,699 (S. 23 bei WEBER)</ls>.'),
  ('angenommen werden; vgl. übrigens auch ',
   'angenommen werden; <ab>vgl.</ab> übrigens auch '),
  ('{#pARinA saMmamArja (sa mamArja#} <ab>ed.</ab> 🞄<ls>SCHL.</ls>)',
   '{#pARinA saMmamArja#} ({#sa mamArja#} <ls>ed. SCHL.</ls>)'),
  ('paScAtsumarditaH (paScAcca pIqitaH#} <ab>ed.</ab> 🞄[Page5-0584] 🞄Bomb.)',
   'paScAtsumarditaH#} ({#paScAcca pIqitaH#} <ls>ed. Bomb.</ls>) 🞄[Page5-0584] 🞄'),
  ('(so die <ab>ed.</ab> Bomb).',
   '(so die <ls>ed. Bomb.</ls>)'),
  ('Einschluss des <ab>Gr.</ab>',
   'Einschluss des <ab n="Grenzpunktes">Gr.</ab>'),
  ('({#nAwyaviSeza#} 🞄<ab>Schol.</ab> <ab>S.</ab> 519)',
   '({#nAwyaviSeza#} <ab>Schol.</ab> <ab n="Seite">S.</ab> 519)'),
  ('nach dem <ab>Ind.</ab> zum 🞄<ls>TRIK.</ls>',
   'nach dem <ls>Ind. zum TRIK.</ls>'),
  (' oben 🞄<ls>Sp. 613, Z. 8. fg.</ls>',
   ' oben <ab>Sp.</ab> 613, <ab>Z.</ab> 8. <ab>fg.</ab>'),
  ('(<ls>SUŚR. 1,238,15. 2,43,8. 123,6) s. u.</ls>',
   '(<ls>SUŚR. 1,238,15. 2,43,8. 123,6</ls>) <ab>s. u.</ab>'),
  ('<ls>FOUCAUX</ls> (<ab>S.</ab> 113)',
   ' (S. 113)<ls>FOUCAUX</ls>'),
  # 54%
  ('{%überaus kurz, — <ab>niedrig.</ab>%}',
   '{%überaus kurz, — niedrig%}'),
  ('{%Amoora Rohitaka <ab>W.</ab> <ab>u.</ab> A.%}',
   '{%Amoora Rohitaka W. u. A.%}'),
  ('<ls>BHARTṚ.</ls> (<lang>lith.</lang> <ab>Ausg.</ab>) <ls n="BHARTṚ.">3,14</ls>',
   '<ls>BHARTṚ. (lith. Ausg.) 3,14</ls>'),
  ('{%stehend, ihm gehörig%} u. s. w.:',
   '{%stehend, ihm gehörig%} <ab>u. s. w.</ab>:'),
  ('{%ein%} 🞄[Page5-0707] 🞄{%best. Vogel%}',
   '{%ein <ab>best.</ab> Vogel%} 🞄[Page5-0707] 🞄'),
  ('<ab>S.</ab> {%und%} L.',
   '<is n="Sītā">S.</is> {%und%} <is n="Lakṣmaṇa">L.</is>'),
  ('<ls>VIKR. 23</ls> (<ls>v. l.).</ls>',
   '<ls>VIKR. 23</ls> (<ab>v. l.</ab>).'),
  ('(X,4; am Ende lies S 8)',
   '(X,4; am Ende lies <ab n="Seite">S.</ab> 8)'),
  # 55%
  ('<ls>VṚDDHA-CĀṆ.</ls> <ab>Einl.</ab>',
   '<ls>VṚDDHA-CĀṆ. Einl.</ls>'),
  ('<ab>u.</ab> <ab n="dem">d.</ab> <ab>einf.</ab>',
   '<ab>u. d.</ab> <ab>einf.</ab>'),
  ('{#(minmina#} Berl <ab>Hdschr.</ab>)',
   '({#minmina#} <ab>Berl.</ab> <ab>Hdschr.</ab>)'),
  ('<ab>ed.</ab> 🞄<ls>TR. 382</ls>',
   '<ls>ed. TR. 382</ls>'),
  ('letzten Worte (<ab>Suppl.</ab>)',
   'letzten Worte (<ls n="ŚKDR.">Suppl.</ls>)'),
  ('<ls>ŚĀRṄG.</ls> <ls>PADDH.</ls> <ls>Pet. Hdschr. 50,b (73,b).</ls>',
   '<ls>ŚĀRṄG. PADDH. Pet. Hdschr. 50,b (73,b)</ls>.'),
  ('(<ab>vgl.</ab> daselbst 🞄v. 5)',
   '(<ab>vgl.</ab> daselbst <ab n="vers">v.</ab> 5)'),
  ('<ab>ed.</ab> 🞄<ls>JOHNS. 2622).</ls>',
   '<ls>ed. JOHNS. 2622</ls>).'),
  # 56%
  ('in der <ab>Einl.</ab> <ab>S.</ab> 50.',
   'in der <ab>Einl.</ab> <ab n="Seite">S.</ab> 50.'),
  ('<ls>VP. 50</ls>, 🞄<ab>N.</ab>',
   '<ls>VP. 50, N.</ls>'),
  ('<ls>ĀŚV. GṚHY. 1,13</ls> (<ab>S.</ab> 48 bei <ls>STENZLER</ls>).',
   '<ls>ĀŚV. GṚHY. 1,13 (S. 48 bei STENZLER)</ls>.'),
  ('<ls>MAITRYUP. 6,30</ls> (<ab>S.</ab> 163).',
   '<ls>MAITRYUP. 6,30 (S. 163)</ls>.'),
  ('Gegend im 🞄<ab>N.</ab> O.',
   'Gegend im <ab n="Nord-Ost">NO.</ab>'),
  ('auch zu {%<ab>d.</ab>%} gehören',
   'auch zu {%d.%} gehören'),
  ('der <ab>Einl.</ab> zu <ls>NIR. XXIII.</ls>',
   'der <ls>Einl. zu NIR. XXIII.</ls>'),
  # <L>62164<pc>5-0916<k1>mokzay<k2>mokzay
  # <ls>Spr. 660</ls> thru end is not in print. Where did it come from?
  ('<div n="p">— {#A#} <ab>s.</ab> {#AmokzaRa#} <ls>Spr. 660.</ls> <ls n="Spr.">1678</ls>, <ab>v. l.</ab> (<ab>Th.</ab> III, <ab>S.</ab> 372). <ls n="Spr.">2042</ls>, <ab>v. l.</ab> <ls n="Spr.">2935</ls>, <ab>v. l.</ab>.',
   '<div n="p">— {#A#} <ab>s.</ab> {#AmokzaRa#}.'),
  ('(<ab>Th.</ab> I, <ab>S.</ab> 320)',
   '(<ls n="">Th. I, S. 320</ls>)'),
  ('{#(moktavya#} <ab>v. l.</ab>).',
   '({#moktavya#} <ab>v. l.</ab>).'),
  ('{%das Harz der Gossampinus Rumphii <ab>Sch.</ab> & Endl.%}',
   '{%das Harz der%} {%Gossampinus Rumphii Sch. & Endl.%}'),
  ('<ls>HALL</ls>, <ab>Einl.</ab> zu <ls>DAŚAR. S. 20</ls>',
   '<ls>HALL, Einl. zu DAŚAR. S. 20</ls>'),
  ('(<ab>Th.</ab> 2, <ab>S.</ab> 323)',
   '(<ls n="">Th. 2, S. 323</ls>)'),
  ('<ls>TRIK. 2,6,6.</ls> <ab>Ind.</ab>',
   '<ls>TRIK. 2,6,6, Ind.</ls>'),
  (' 🞄<ls>Sp. 20, Z. 6 lies 11,3,34 st. 11,4,3</ls>; *<ab>Z.</ab> 7 lies 4,5,5 <ab>st.</ab> 6,5,5.',
   '<ab>Sp.</ab> 20, <ab>Z.</ab> 6 lies 11,3,34 <ab>st.</ab> 11,4,3; *<ab>Z.</ab> 7 lies 4,5,5 <ab>st.</ab> 6,5,5.'),
  ('🞄<ls>Sp. 24, Z. 2 lies 11,10,16 st. 11,12,16.</ls>',
   '<ab>Sp.</ab> 24, <ab>Z.</ab> 2 lies 11,10,16 <ab>st.</ab> 11,12,16.'),
  ('🞄<ls>Z. 21</ls> lies {#vAsatIvare#} .',
   '<ab>Z.</ab> 21 lies {#vAsatIvare#}.'),
  ('🞄<ls>Z. 16</ls>',
   '<ab>Z.</ab> 16'),
  # 57%
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  #('', ''),
  
  ]
 newlines = []
 nchg = 0
 for iline,line in enumerate(lines):
  newline = line
  for old,new in replacements:
   newline = newline.replace(old,new)
  if newline != line:
   nchg = nchg + 1
  newlines.append(newline)
 print(f'{nchg} line(s) changed')
 return newlines

if __name__=="__main__":
 filein = sys.argv[1]  # base
 fileout = sys.argv[2] # adjusted base
 
 lines = read_lines(filein)

 lines1 = adjust_lines1(lines)
 #lines2 = adjust_lines2(lines1)
 write_lines(fileout,lines1)
