""" change_4_5.py
 
"""
import sys,re
import codecs

def read_lines(filein):
 lines = []
 with codecs.open(filein,encoding='utf-8',mode='r') as f:
  for line in f:
   lines.append(line.rstrip('\r\n'))
 print(f'{len(lines)} lines read from {filein}')
 return lines

def write_lines(fileout,outarr):
 with codecs.open(fileout,'w','utf-8') as f:
  for out in outarr:
   f.write("%s\n" % out)
 print(f'{len(outarr)} lines written to {fileout}')


def adjust_lines1(lines):
 replacements = [
  # 43% Begin 06-19-2026 
  ('<is>Kṣ</is>., {%der Ur%}- <is>Kṣ</is>.',
   '<is n="Kṣatra">Kṣ.</is>, {%der Ur%}-<is n="Kṣatra">Kṣ.</is>'),
  ('{%unter denen%} <is>Ikṣv</is>. ',
   '{%unter denen%} <is n="Ikṣvāku">Ikṣv.</is>'),
  ('Schüler des%} P. <ls>ebend.</ls>',
   'Schüler des%} <is n="Pāṇini">P.</is> <ls>ebend.</ls>'),
  ('die Legende, dass P. seine Zähne',
   'die Legende, dass <is n="Pūṣan">P.</is> seine Zähne'),
  ('{%in deren Mitte%} P.',
   '{%in deren Mitte%} <is n="Pūṣan">P.</is>'),
  ('einer <is>Piśācī</is> und einer',
   'einer <is>Piśākī</is> und einer'),  # v1e spelling error
  ('{%von%} P. {%herrührend%}',
   '{%von%} <is n="Pippalāda">P.</is> {%herrührend%}'),
  ('P. <ls>Ind. St. 5,80, N. 3.</ls>',
   '<is n="Paippalāda">P.</is> <ls>Ind. St. 5,80, N. 3</ls>.'),
  ('{%bezüglich, dem%} P.',
   '{%bezüglich, dem%} <is n="Potar">P.</is>'),
  #('<is>Bihār</is>',
  # 'Bihār'),  # v1e <iw>
  ('{#vehAra#} <is>Bihār</is>',
   '{#vehAra#} <iw>Bihār</iw>'),
  ('{%ein den%} P. {%begleitender%}',
   '{%ein den%} <is n="Puroḍāśa">P.</is> {%begleitender%}'),
  ('{%vom%} P. {%kommend%}',
   '{%vom%} <is n="Purohita">P.</is> {%kommend%}'),
  ('{%geweiht, gehörig, auf%} P. {%bezüglich%}',
   '{%geweiht, gehörig, auf%} <is n="Pūṣan">P.</is> {%bezüglich%}'),
  ('Seiten mit%} <is>Pr</is>. {%versehen%}',
   'Seiten mit%} <is n="Pra-uga">Pr.</is> {%versehen%}'),
  ('P. {%liegt das%} Ś.',
   '<is n="Paiśācī">P.</is> {%liegt das%} <is n="Śaurasenī">Ś.</is>'),
  ('P. {%wird vom%} Ś. {%abgeleitet%}',
   '<is n="Paiśācī">P.</is> {%wird vom%} <is n="Śaurasenī">Ś.</is> {%abgeleitet%}'),
  # 44%
  ('{#jagatpraRatiM ca vizRoH#} {%vor%} V.',
   '{#jagatpraRatiM ca vizRoH#} {%vor%} <is n="Viṣṇu">V.</is>'),
  ('{%dem Spiegel des%} <is>Kāvy</is>.',
   '{%dem Spiegel des%} <is n="Kāvyaprakāśa">Kāvy.</is>'),
  ('<is>Veda</is>, {%für jeden%} V.',
   '<is>Veda</is>, {%für jeden%} <is n="Veda">V.</is>'),
  ('{%in%} <is>Mag</is>. {%residirend%}',
   '{%in%} <is n="Magadha">Mag.</is> {%residirend%}'),
  ('{#magaDapratizWa#} {%in%} <is>Mag</is>.',
   '{#magaDapratizWa#} {%in%} <is n="Magadha">Mag.</is>'),
  ('{%ein Bewohner von%} <is>Madhyad</is>.',
   '{%ein Bewohner von%} <is n="Madhyadeśa">Madhyad.</is>'),
  ('erst zusammengesetzte%} Bṛ.',
   'erst zusammengesetzte%} <is n="Bṛhatī">Bṛ.</is>'),
  ('eines der Söhne des <is>Manu</is> <is>Svārokiṣa</is>',
   'eines der Söhne des <is>Manu</is> <is>Svārociṣa</is>'),
  # 45%
  ('<is>Pūnā</is>',
   '<iw>Pūnā</iw>'),  # note <iw>
  ('{%auf dem%} <is>Him</is>.',
   '{%auf dem%} <is n="Himavant">Him.</is>'),
  ('{%auf dem%} M.',
   '{%auf dem%} <is n="Meru">M.</is>'),
  ('{%die Heirath der%} P.',
   '{%die Heirath der%} <is n="Pradyumna">P.</is>'),
  ('P. <ls>MED.</ls>',
   '<is n="Pravacana">P.</is> <ls>MED.</ls>'),
  ('<is>Madh</is>. {%sprechen%}',
   '<is n="Madhusūdana">Madh.</is> {%sprechen%}'),
  # 46%
  ('herausgegeben von <is>Cowell</is>.',
   'herausgegeben von <ls>Cowell</ls>.'),
  ('{%König von%} <is>Pr</is>.',
   '{%König von%} <is n="Prāgjyotiṣa">Pr.</is>'),
  ('{%bestehend, wo die%} Ā.',
   '{%bestehend, wo die%} <is n="Ārya">Ā.</is>'),
  ('Theil von%} Bh. {%erschlagen%}',
   'Theil von%} <is n="Bhīma">Bh.</is> {%erschlagen%}'),
  ('{%der Ort des Wiedersichtbarwerdens der%} <is>Sar</is>.',
   '{%der Ort des Wiedersichtbarwerdens der%} <is n="Sarasvati">Sar.</is>'),
  ('{%um%} K {%einen Gefallen zu erweisen%}',
   '{%um%} <is n="Kaikeyī">K.</is> {%einen Gefallen zu erweisen%}'),
  ('{#virAwa˚#} {%bei%} <is>Vir</is>.',
   '{#virAwa˚#} {%bei%} <is n="Virāṭa">Vir.</is>'),
  ('{%der Monat%} <is>Ph</is>.',
   '{%der Monat%} <is n="Phālguna">Ph.</is>'),
  # 47%
  ('P. {%zum Vollmondstage im Monat%}',
   '<is n="Phalgunī">P.</is> {%zum Vollmondstage im Monat%}'),
  ('B. {%will man Nichts zu thun haben%}',
   '<is n="Bāhīka">B.</is> {%will man Nichts zu thun haben%}'),
  ('%als das%} Ai. {%enthält%}',
   '{%als das%} <is n="Aiṣīka">Ai.</is> {%enthält%}'),
  ('{%in der Gefangenschaft bei%} Bh.',
   '{%in der Gefangenschaft bei%} <is n="Bhojendra">Bh.</is>'),
  ("<is>Atris</is>ʼ",
   '<is>Atri</is>ʼs'),
  ('eines <is>Pra-</is>',
   'eines <is>Prajāpati</is>'),
  ('-<is>jāpati</is>', ''),
  ('{%eine Prinzessin der%} <is>Bālh</is>.',
   '{%eine Prinzessin der%} <is n="Bālhika">Bālh.</is>'),
  ('<is>Bāh</is>.: {#gOrbAhIkaH#}',
   '<is n="Bāhīka">Bāh.</is>: {#gOrbAhIkaH#}'),
  # 48%
  ('Name eines <is>Devag</is>. wäre',
   'Name eines <is n="Devagandharva">Devag.</is> wäre'),
  ('{%wissend, was durch%} <is>Br</is>.',
   '{%wissend, was durch%} <is n="Brahman">Br.</is>'),
  ('{%der Sohn einer nach%} Br.',
   '{%der Sohn einer nach%} <is n="Brahmadeya">Br.</is>'),
  ('Br. {%viele machend%}',
   '<is n="Brahman">Br.</is> {%viele machend%}'),
  ('{%das Eingehen in\'s%} Br.',
   '{%das Eingehen inʼs%} <is n="Brahman">Br.</is>'),
  ('<ls><is>Śak</is>.</ls> <ls>ŚĀK. 25,5.</ls>',
   '<is n="Śakuntalā">Śak.</is> <ls>ŚĀK. 25,5</ls>.'),
  ('<is>St</is>. {%übrig sind%}',
   '<is n="Stotriya">St.</is> {%übrig sind%}'),
  ('{%sprach zu%} R. {%die Worte%}',
   '{%sprach zu%} <is n="Rāvaṇa">R.</is> {%die Worte%}'),
  ('eines der <is>Aditya</is>',
   'eines der <is>Āditya</is>'),
  # 49%
  ('<is>Udayanākārya</is>',
   '<is>Udayanācārya</is>'),
  ('König <is>Bhadr</is>.',
   'König <is n="Bhadrāśva">Bhadr.</is>'),
  ('(Śṛṅgāra-Ś., Nīti-Ś. und <is>Vairāgya</is>-Ś.)',
   '(<is n="Śṛṅgāra-Śataka">Śṛṅgāra-Ś.</is>, <is n="Nīti-Śataka">Nīti-Ś.</is> und <is n="Vairāgya-Śataka">Vairāgya-Ś.</is>)'),
  ('{%die Nachkommen des%} <is>Bh</is>.',
   '{%die Nachkommen des%} <is n="Bhalandana">Bh.</is>'),
  ('{%der Vater der%} <is>Bh</is>.',
   '{%der Vater der%} <is n="Bhavānī">Bh.</is>'),
  ('{%ein Anhänger des%} <is>Bhag</is>.',
   '{%ein Anhänger des%} <is n="Bhagavant">Bhag.</is>'),
  ('Yellinghy <is>Navadvīpa</is>',
   '<is>Yellinghy</is> <is>Navadvīpa</is>'),
  ('(so ist zu lesen mit {%K.%})',
   '(so ist zu lesen mit <is n="Karma">K.</is>)'),
  ('<is>Viśv</is>. {%ist die dir bevorstehende Arbeit%}',
   '<is n="Viśvāmitra">Viśv.</is> {%ist die dir bevorstehende Arbeit%}'),
  ('Sinne des%} <is>Bhā-</is>',
   'Sinne des%} <is>Bhārata</is>'),
  ('<is>rata</is>, Titel',
   'Titel'),
  ('{#BAvavfttI#} <is>Naig</is>.',
   '{#BAvavfttI#} <is n="Naigeyagāna">Naig.</is>'),
  ('<is>Vaiśeṣika</is>-Systems',
   'Vaiśeṣika-Systems'),
  # 50%
  ('P., {%weniger als ein%}',
   '<is n="Paṇa">P.</is>, {%weniger als ein%}'),
  ('P. <ls>YĀJÑ. 2,248.</ls>',
   '<is n="Paṇa">P.</is> <ls>YĀJÑ. 2,248</ls>.'),
  ('47ten <is>Adhy</is>, im',
   '47ten <is n="Adhyāya">Adhy.</is>, im'),
  ('Verlangen der%} A. {%entgegen%}',
   'Verlangen der%} <is n="Aśvin">A.</is> {%entgegen%}'),
  # 51%
  ('{%weil er irrthümlich%} V.',
   '{%weil er irrthümlich%} <is n="Vatseśa">V.</is>'),
  ('({#masj#}) . erhält keinen Bindevocal {#i#} <is>Kār.</is>',
   '({#masj#}). erhält keinen Bindevocal {#i#} <ls n="Kārikā">Kār. 2</ls>'),
  # 52%
  ('<is>Lakṣmī(</is>?)',
   '<is>Lakṣmī</is>(?)'),
  ('(Gesetzgeber), {%der%} A.',
   '(Gesetzgeber), {%der%} <is n="Aṅgiras">A.</is>'),
  ('{%der%} Ā. {%von mittlerem Umfange%}',
   '{%der%} <is n="Ātreya">Ā.</is> {%von mittlerem Umfange%}'),
  ('<is>Siddh</is>.',
   '<is n="Siddhānta">Siddh.</is>'),
  ('{%das wusste%} G. {%nicht%}',
   '{%das wusste%} <is n="Gārgya">G.</is> {%nicht%}'),
  ('{%hielt%} V. {%für geringer an Wissen als sich%}',
   '{%hielt%} <is n="Varuṇa">V.</is> {%für geringer an Wissen als sich%}'),
  ('Chronologie eröffnet <is>M</is>.',
   'Chronologie eröffnet <is n="Manu">M.</is>'),
  ('{%in einem Thale des%} M.',
   '{%in einem Thale des%} <is n="Mandara">M.</is>'),
  ('{%der Sohn der%} M.',
   '{%der Sohn der%} <is n="Mandodarī">M.</is>'),
  ('{%des 8ten in der dunklen Hälfte des%} <is>Aṣ</is>.',
   '{%des 8ten in der dunklen Hälfte des%} <is n="Āṣāḍha">Aṣ.</is>'),
  ('{%Fürst der%} <is>Kiṃp</is>.',
   '{%Fürst der%} <is n="Kiṃpuruṣa">Kiṃp.</is>'),
  # 53%
  ('<is>mahrka</is>',
   '<iw>mahrka</iw>'),
  ('<ls>WEBER, JYOT. 100. 102. <is>Nakṣ</is>. 2,350.</ls>',
   '<ls>WEBER, JYOT. 100. 102</ls>. <ls>Nax. 2,350</ls>.'), # v1e spelling?
  ('{%der grosse%} <is>Nār</is>.',
   '{%der grosse%} <is n="Nārāyaṇa">Nār.</is>'),
  ('{%das grosse epische Gedicht%} <is>Mah</is>.',
   '{%das grosse epische Gedicht%} <is n="Mahābhārata">Mah.</is>'),
  ('Titel von <is>Kaiyaṭa</is>ʼs {%Erklärung%} des <is>Mah</is>.',
   'Titel von <is>Kaiyaṭa</is>ʼs {%Erklärung%} des <is n="Mahābhāṣya">Mah.</is>'),
  ('Titel von <is>Bhartṛhari</is>ʼs {%Erklärung%} des <is>Mah</is>.',
   'Titel von <is>Bhartṛihari</is>ʼs {%Erklärung%} des <is n="Mahābhāṣya">Mah.</is>'),
  # 54%
  ('{%einen%} K. {%messend%}',
   '{%einen%} <is n="Karṣa">K.</is> {%messend%}'),
  ('{%aus zwölf%} <is>Sk</is>.',
   '{%aus zwölf%} <is n="Skandha">Sk.</is>'),
  ('{%die Nachkommen des%} <is>Mārk</is>.',
   '{%die Nachkommen des%} <is n="Mārkaṇḍeya">Mārk.</is>'),
  ('{%einen Monat lang%} <is>Brahmac</is>.',
   '{%einen Monat lang%} <is n="Brahmacārin">Brahmac.</is>'),
  # 55%
  ('<ls>WEBER, <is>Nakṣ</is> 2,282. 345</ls>',
   '<ls>WEBER, Nax. 2,282. 345</ls>'),
  ('<is>mithradruj</is>',
   '<iw>mithradruj</iw>'),  #v1e <iw>
  ('<is>myazda</is>',
   '<iw>myazda</iw>'), # v1e <iw>
  ('{%ein mit%} <is>Śall</is>.',
   '{%ein mit%} <is n="Śallakī">Śall.</is>'),
  ('<is>Bad</is>. {%vermischter Wald%}',
   '<is n="Badarī">Bad.</is> {%vermischter Wald%}'),
  ('{%ein Wald, der ausser%} <is>Śall</is>. und <is>Bad</is>.',
   '{%ein Wald, der ausser%} <is n="Śallakī">Śall.</is> und <is n="Badarī">Bad.</is>'),
  ('{%und die Uebrigen%}, <is>Mar</is>.',
   '{%und die Uebrigen%}, <is n="Marīci">Mar.</is>'),
  ('{%und Andere%}, <is>Jayadr</is>.',
   '{%und Andere%}, <is n="Jayadratha">Jayadr.</is>'),
  # 56%
  ('{%der ältere Theil der Stadt%} Dv.',
   '{%der ältere Theil der Stadt%} <is n="Dvāravatī">Dv.</is>'),
  ('{%aus dem weichsten Theile des%} <is>Pur</is>.',
   '{%aus dem weichsten Theile des%} <is n="Puroḍha">Pur.</is>'),
  ('<ls>WEBER, JYOT. 36. <is>Nakṣ</is>. 2,384. fg.</ls>',
   '<ls>WEBER, JYOT. 36</ls>. <ls>Nax. 2,384. fg.</ls>'),  # v1e spelling?
  ('{%die am Fusse des%} V.',
   '{%die am Fusse des%} <is n="Vindhya">V.</is>'),
  # 57%
  ('<ls>WEBER, JYOT. 95. 96. 98. <is>Nakṣ</is>. 2,336.</ls>',
   '<ls>WEBER, JYOT. 95. 96. 98</ls>. <ls>Nax. 2,336</ls>.'),
  ('<ab>N.</ab> der <is>Dā-</is>',
   '<ab>N.</ab> der <is>Dākṣāyaṇī</is>'),
  ('<is>kṣāyaṇī</is> in <is>Bharatāśrama</is>',
   'in <is>Bharatāśrama</is>'),
  ('<ls>WEBER, JYOT. 101. <is>Nakṣ</is>. 2,382.</ls>',
   '<ls>WEBER, JYOT. 101</ls>. <ls>Nax. 2,382</ls>.'),  # v1e spelling
  ('<is>Mātṛg</is>.',
   '<is n="Mātṛgupta">Mātṛg.</is>'),
  # 58%
  ('{%der Gefährte der%} Ar.',
   '{%der Gefährte der%} <is n="Arundhatī">Ar.</is>'),
  ('{%das Hinabsteigen auf den Pfad der%} <is>Pāṣ</is>.',
   '{%das Hinabsteigen auf den Pfad der%} <is n="Pāṣaṇḍha">Pāṣ.</is>'),
  ('<is>aiwyāoṅha</is>, <is>aiwyāoṅhana</is>',
   '<iw>aiwyâoṅha</iw>, <iw>aiwyâoṅhana</iw>.'),
  ('<ls>WEBER, JYOT.</ls> und <is>Nakṣ</is>.',
   '<ls>WEBER, JYOT.</ls> und <ls>Nax.</ls>'),  # v1e spelling?
  ('<is>Dvād</is>.',
   '<is n="Dvādaśāha">Dvād.</is>'),
  ('<is>Khandéṣ</is>',
   '<iw>Khandéṣ</iw>'),  # v1e <iw>
  ('<is>Śaṃkarācārya\'s(</is>?)',
   '<is>Śaṃkarācārya</is>ʼs (?)'),
  ('<is>Adhyātmar</is>.',
   '<ls>Adhyātmar.</ls>'),
  ('<is>Nakṣ</is>. <ls n="WEBER, Nakṣ.">1,310. 2,300. 303. 315</ls> (<ab>pl.</ab>). <ls n="WEBER, Nakṣ.">323. 370.</ls>',
   ' <ls>Nax. 1,310. 2,300. 303. 315</ls> (<ab>pl.</ab>). <ls n="WEBER, Nax.">323. 370</ls>.'),
  ('<is>Avabhṛti</is>',
   '<is>Avabhṛiti</is>'), # v1e spelling?
  ('<is>Prātiśākhya</is> des <is>Āśv</is>.',
   '<is>Prātiśākhya</is> des <is n="Āśvalāyana">Āśv.</is>'),
  ('{%dadurch gelangt man zu%} <is>Bhag</is>.',
   '{%dadurch gelangt man zu%} <is n="Bhagavān">Bhag.</is>'),
  # 59%
  ('<ls>WEBER, JYOT. 95. <is>Nakṣ</is>. 2,385.</ls>',
   '<ls>WEBER, JYOT. 95</ls>. <ls>Nax. 2,385</ls>.'),
  ('<ls>WEBER, JYOT. 40. 89. 91. 109. <is>Nakṣ</is>. 2,287.</ls>',
   '<ls>WEBER, JYOT. 40. 89. 91. 109</ls>. <ls>Nax. 2,287</ls>.'),
  ('<ls>WEBER, JYOT. 112. <is>Nakṣ</is>. 2,341. 351.</ls>',
   '<ls>WEBER, JYOT. 112</ls>. <ls>Nax. 2,341. 351</ls>.'),
  ('<ls>WEBER, JYOT. 54. fg.</ls> {#ahorAtra#} <is>Nakṣ</is>. 2,287.',
   '<ls>WEBER, JYOT. 54. fg.</ls> {#ahorAtra#} <ls>Nax. 2,287</ls>.'),
  # 60%
  ('<is>karaṇa</is>',
   '<iw>karaṇa</iw>'),
  ('<is>Caitanya-</is> <is>Candrodaya</is>.',
   '<is>Caitanya-Candrodaya</is>.'),
  ('<is>Karṇ</is>.',
   '<is n="Karṇāṭa">Karṇ.</is>'),
  ('<ls>WEBER, JYOT. 112. <is>Nakṣ.</is> 2,354. fg.</ls>',
   '<ls>WEBER, JYOT. 112</ls>. <ls>Nax. 2,354. fg.</ls>'),
  ('{%das Land der%} <is>Kal</is>.',
   '{%das Land der%} <is n="Kaliṅga">Kal.</is>'),
  ('{%ein Fürst der%} <is>Kal</is>.',
   '{%ein Fürst der%} <is n="Kaliṅga">Kal.</is>'),
  ('{%ein Mann aus dem Volke der%} <is>Kul</is>.',
   '{%ein Mann aus dem Volke der%} <is n="Kulūta">Kul.</is>'),
  ('{#˚rAmAyite dve#} <is>Kṛ</is>.',
   '{#˚rAmAyite dve#} <is n="Kṛṣṇa">Kṛ.</is>'),
  ('<ls>R.</ls> {%darstellend%}',
   '<is n="Rāma">R.</is> {%darstellend%}'),
  # 61%
  #('<ls>LIA. II,906. Ki-li-to</is></ls>, <lang>chines.</lang> <is>Maï-te</is>',
  # '<ls>LIA. II,906.</ls> <ns>Ki-li-to</ns>, <lang>chines.</lang> <ns>Maï-te</ns>'),
  ('<ls>LIA. II,906. <is>Ki-li-to</is></ls>, <lang>chines.</lang> <is>Maï-te</is>',
   '<ls>LIA. II,906</ls>. <ns>Ki-li-to</ns>, <lang>chines.</lang> <ns>Maï-te</ns>'),
  
  ('<is>Lak\'ṣmī</is>',
   '<is>Lakṣmī</is>'),
  ('{%ein Quasi%}- <is>Kāp</is>.',
   '{%ein Quasi%}-<is n="Kāpālika">Kāp.</is>'),
  ('{#˚rAmAyaRakAvya#} {%ein%} <is>Rām</is>.',
   '{#˚rAmAyaRakAvya#} {%ein%} <is n="Rāmāyaṇa">Rām.</is>'),
  ('G. <ls>WEBER, RĀMAT. UP. 355.</ls>',
   '<is n="Gaṇeśa">G.</is> <ls>WEBER, RĀMAT. UP. 355</ls>.'),
  ('{%ein Verehrer des%} G.',
   '{%ein Verehrer des%} <is n="Gaṇeśa">G.</is>'),
  # 62%
  ('<is>Śr</is>. {%die Befriedigung an%}',
   '<is n="Śrotriya">Śr.</is> {%die Befriedigung an%}'),
  ('<is>Jy</is>.',
   '<is n="Jyotiṣṭoma">Jy.</is>'),
  ('<is>ḍhabūā</is>',
   '<iw>ḍhabūā</iw>'),
  ('<is>Tārkṣyaputra</is>',
   '<is>Tārkṣyaputra Suparṇa</is>'),
  ('<is>Suparṇa</is> als Liedverfasser',
   'als Liedverfasser'),
  ('{%ein Mann vom Volke der%} T.',
   '{%ein Mann vom Volke der%} <is n="Turuṣka">T.</is>'),
  ('1. {#dA#}¦ <is>A.</is>',
   '<hom>1.</hom> {#dA#}¦ A.'),   # v1e <enum>A.</enum>
  ('entsprechenden Bewohner von <is>Kr</is>.',
   'entsprechenden Bewohner von <is n="Krauñcadvīpa">Kr.</is>'),
  # 63%
  ('<span>N.</span> <ls>KATHĀS. 102,76.</ls>',
   '<is n="Narmada">N.</is> <ls>KATHĀS. 102,76</ls>.'),
  ('{%in der Nähe der%} <is>God</is>.',
   '{%in der Nähe der%} <is n="Godāvarī">God.</is>'),
  ('<is>Mahābhāsya</is>',
   '<is>Mahābhāṣya</is>'),
  ('<is>Yoga</is>-{%Systems des%} <is>Pat</is>.',
   '<is>Yoga</is>-{%Systems des%} <is n="Patañjali">Pat.</is>'),
  ('{%ein Fürst der%} <is>Gandh</is>.',
   '{%ein Fürst der%} <is n="Gandharva">Gandh.</is>'),
  # 64%
  ('die <is>Prāt</is>. sind {%Orthoepien%}',
   'die <is n="Prātiśākhya">Prāt.</is>'),
  ('{%die Abkömmlinge des%} <is>Bak</is>. ',
   '{%die Abkömmlinge des%} <is n="Bakanakha">Bak.</is>'),
  ('<is>Gud</is>. <is>gaṇa</is> {#tikakitavAdi#}',
   '<is n="Gudaparinaddha">Gud.</is> <is>gaṇa</is> {#tikakitavAdi#}'),
  ('{%im Kampfe zwischen%} <is>Bāl</is>.',
   '{%im Kampfe zwischen%} <is n="Bālāhaka">Bāl.</is>'),
  ('<ls>SV.</ls> <ls>PŪRVĀRCIKA, <is>Prap</is>. 7, <is>Daś</is>. 6</ls>(<ls>NAIGEYAŚĀKHĀ</ls>) <ls>Tüb. Hdschr. 67</ls>',
   '<ls>SV. PŪRVĀRCIKA, Prap. 7, Daś. 6 (NAIGEYAŚĀKHĀ) Tüb. Hdschr. 67</ls>'),
  ('<is>yazata</is>',
   '<iw>yazata</iw>'),
  ('{%in Beziehung auf das%} J., {%im Gebiete des%} Yajus',
   '{%in Beziehung auf das%} <is n="Yajus">Y.</is>, {%im Gebiete des%} <is n="Yajus">Y.</is>'),
  ('<is>yaśna</is>',
   '<iw>yaçna</iw>'),
  # 65%
  ('<ls><is>KATHĀS</is>. 28,165. 62,11.</ls>',
   '<ls>KATHĀS. 28,165. 62,11</ls>.'),
  ('{%wie angewiesen von%} <is>Sugr</is>.',
   '{%wie angewiesen von%} <is n="Sugrīva">Sugr.</is>'),
  ('<is>eine</is>',
   'eine'),
  ('<ls>P. 3,1,34</ls>, <is>Vārtt</is>',
   '<ls>P. 3,1,34, <is n="Vārttika">Vārtt.</is></ls>'),
  # 66%
  ('<ls>Journ. of the Am. Or. S. 7,4, <is>Śl</is>. 2.</ls>',
   '<ls>Journ. of the Am. Or. S. 7,4, Śl. 2</ls>.'),
  # next done in adjust_lines0
  #('<div n="1"> 1) <ab>Bein.</ab> <is>Kṛṣṇa</is>ʼs',
  # '<div n="1"> 1〉 <ab>Bein.</ab> <is>Kṛiṣṇa</is>ʼs'),  # v1e spelling
  ('<is>Prākīna</is>',
   '<is>Prācīna</is>'),
  ('(<ab>vgl.</ab> <ls>P. 3,1,85</ls>, <is>Kārt.</is>, <ab>Sch.</ab>)',
   '(<ab>vgl.</ab> <ls>P. 3,1,85, <is n="Vārttika">Vārt.</is></ls>, <ab>Sch.</ab>)'),
  ('{%Zeitalter der%} <is>Br</is>., {%der%} <is>Kṣ</is>.',
   '{%Zeitalter der%} <is n="Brahma">Br.</is>, {%der%} <is n="Kṣatriya">Kṣ.</is>'),
  ('<ls>WEBER, JYOT. 23. 26. 88. 93. <is>Nakṣ</is>. 2,354.</ls>',
   '<ls>WEBER, JYOT. 23. 26. 88. 93</ls>. <ls>Nax. 2,354</ls>.'),
  ('{%die Nachkommen des%} <is>Yudh</is>.',
   '{%die Nachkommen des%} <is n="Yudhiṣṭhira">Yudh.</is>'),
  ('<is>PRAVARĀDHY</is>',
   '<ls>PRAVARĀDHY.</ls>'),
  ('{%Sohn des%} <is>Yuv</is>.',
   '{%Sohn des%} <is n="Yuvanāśva">Yuv.</is>'),
  ('{%Clypea hernandifolia W. et%} <is>A.</is>',
   '{%Clypea hernandifolia W. et A.%}'),
  ('{%eine Strecke von sechzig%} <is>Yoj</is>.',
   '{%eine Strecke von sechzig%} <is n="Yojana">Yoj.</is>'),
  ('ls>MED. <is>dh</is>',
   'ls>MED. dh'),
  # 67%
  ('<is>aredra</is>',
   '<iw>aredra</iw>'),
  ('<ls>R.</ls> <ls>Verz. d. Oxf. H. 86,a,36.</ls>',
   '<is n="Rāga">R.</is> <ls>Verz. d. Oxf. H. 86,a,36</ls>.'),
  # 68%
  ('Br. {%nehmen sie es in Besitz%}',
   '<is n="Brahma">Br.</is> {%nehmen sie es in Besitz%}'),
  # 69%
  ('<is>Nip</is>. zu 14.',
   '<is n="Nipāta">Nip.</is> zu 14.'),
  ('<ls><is>Śak</is>.</ls>',
   '<is n="Śakuntalā">Śak.</is>'),
  ('dem Sohne <is>Hariścandra</is>ʼs, gegründeten',
   'dem Sohne <is>Hariśkandra</is>ʼs, gegründeten'),  # v1e sp. error
  ('<ls>WEBER, JYOT. 34. <is>Nakṣ</is>. 1,309.</ls>',
   '<ls>WEBER, JYOT. 34</ls>. <ls>Nax. 1,309</ls>.'),
  ('{#devatAlakzaRA yAjyAnuvAkyAH#} {%die%} J. {%und A. haben die Götternamen%}',
   '{#devatAlakzaRA yAjyAnuvAkyAH#} {%die%} <is n="Yājya">Y.</is> {%und%} <is n="Anuvāka">A.</is> {%haben die Götternamen%}'),
  ('{%der jüngere Theil der Stadt%} Dv.',
   '{%der jüngere Theil der Stadt%} <is n="Dvāravatī">Dv.</is>'),
  ('Titel einer {%Abkürzung des%} <is>Vas</is>.',
   'Titel einer {%Abkürzung des%} <is n="Vasiṣṭasiddhānta">Vas.</is>'),
  ('Titel einer {%Abkürzung der%} <is>Vaiyāk</is>.',
   'Titel einer {%Abkürzung der%} <is n="Vaiyākaraṇasiddhāntamañjūṣā">Vaiyāk.</is>'),
  ('{%Abkürzung des%} <is>Śabdend</is>.',
   '{%Abkürzung des%} <is n="Śabdendenduśekhara">Śabdend.</is>'),
  ('Titel einer {%Abkürzung des%} <is>Śāntip</is>.',
   'Titel einer {%Abkürzung des%} <is n="Śāntipurāṇa">Śāntip.</is>'),
  ('{%das abgekürzte%} <is>Śivap</is>.',
   '{%das abgekürzte%} <is n="Śivapurāṇa">Śivap.</is>'),
  ('{%die kürzere%} <is>Śaun</is>.',
   '{%die kürzere%} <is n="Śaunaka">Śaun.</is>'),
  ('{%ein abgekürzter%} <is>Āryas</is>.',
   '{%ein abgekürzter%} <is n="Āryasiddhānta">Āryas.</is>'),
  ('{%der Feind von%} L.',
   '{%der Feind von%} <is n="Laṅkā">L.</is>'),
  # 70%
  ('{%der Verbrenner von%} L.',
   '{%der Verbrenner von%} <is n="Laṅkā">L.</is>'),
  ('(<ab>vgl.</ab> <is>Kār.</is>',
   '(<ab>vgl.</ab> <is n="Kārikā">Kār.</is>'),
  ('{%giebt%} <is>Vid</is>. ',
   '{%giebt%} <is n="Vidūṣaka">Vid.</is> {%ein Zeichen%}'),
  ('<is>Muh</is>.); häufig <ab>personif.</ab>',
   '<is n="Muhūrta">Muh.</is>); häufig <ab>personif.</ab>'),
  ('(<is>Varāhamihira\'s</is>?)',
   '(<is>Varāhamihira</is>ʼs?)'),
   
  ('<is>Ujj</is>., {%wohin du zu gehen beabsichtigtest%}',
   '<is n="Ujjayinī">Ujj.</is>, {%wohin du zu gehen beabsichtigtest%}'),
  ('<ls><is>Kār.</is> 5</ls> aus <ls>SIDDH. K.</ls>',
   '<ls><is n="Kārikā">Kār.</is> 5</ls> aus <ls>SIDDH. K.</ls>'),
  ('<ls><is>Kār.</is> 6</ls> aus <ls>SIDDH. K.</ls>',
   '<ls><is n="Kārikā">Kār.</is> 6</ls> aus <ls>SIDDH. K.</ls>'),
  # 71%
  ('{%der Gatte der%} <is>Lop</is>.',
   '{%der Gatte der%} <is n="Lopāmudrā">Lop.</is>'),
  ('{%die Nachkommen des%} V. {%und%} <is>Bh</is>.',
   '{%die Nachkommen des%} <is n="Vaṅkara">V.</is> {%und%} <is n="Bhaṇḍīratha">Bh.</is>'),
  ('vakzyati#} <is>Kār.</is>',
   'vakzyati#} <is n="Kārikā">Kār.</is>'),
  ('{%vom lieben Kinde%} <is>Mad</is>.',
   '{%vom lieben Kinde%} <is n="Madirāvatī">Mad.</is>'),
  ('<is>Kār.</is> zu <ls>P. 2,1,32.</ls>',
   '<is n="Kārikā">Kār.</is> zu <ls>P. 2,1,32</ls>.'),
  ('<ls>ŚRUT. 43</ls>. <is>Kār.</is>',
   '<ls>ŚRUT. 43</ls>. <is n="Kārikā">Kār.</is> <ls>P. 7,2,10</ls>'),
  ('{%wiederholt die Worte des%} <is>Kal</is>.',
   '{%wiederholt die Worte des%} <ls>Kal. P.</ls>,'),
  ('<ls>P.</ls>, <ab>Sch.</ab> {#GozasyAnvavadizweva #}',
   '<ab>Sch.</ab> {#GozasyAnvavadizweva#}'),
  # 72%
  ('<ls><is n="Kārikā">Kār.</is> 5</ls> aus <ls>SIDDH. K.</ls> zu <ls>P. 7,2,10</ls>)',
   '<ls><is n="Kārikā">Kār.</is> 5</ls> aus <ls>SIDDH. K.</ls> zu <ls>P. 7,2,10</ls>)'),
  # 2026-06-19  end 
  #('', ''),
 ]
 newlines = []
 nchg = 0
 for iline,line in enumerate(lines):
  newline = line
  for old,new in replacements:
   newline = newline.replace(old,new)
  if newline != line:
   nchg = nchg + 1
  newlines.append(newline)
 print(f'{nchg} line(s) changed')
 return newlines

def adjust_lines0(lines):
 ans = lines
 lnum = 736895
 iline = lnum - 1
 assert ans[iline] == '<div n="1"> 1) <ab>Bein.</ab> <is>Kṛṣṇa</is>ʼs'
 ans[iline] = '<div n="1"> 1) <ab>Bein.</ab> <is>Kṛiṣṇa</is>ʼs'
 #ans[iline - 1] = ans[iline - 1] + ', <is>Vartt</is>. 1.'
 return ans
if __name__=="__main__":
 filein = sys.argv[1]  # base
 fileout = sys.argv[2] # adjusted base
 
 lines = read_lines(filein)
 lines0 = adjust_lines0(lines)
 #lines0 = lines
 lines1 = adjust_lines1(lines0)
 write_lines(fileout,lines1)
